---
title: "Syllabus -- 340"
description: "Syllabus and course policies for Jason Howald's Math 340"
format: html
---

{{< include ../_syllabus_objects/instructor.qmd >}}

{{< include ../_syllabus_objects/officehours.qmd >}}

## Course Information
Credit Hours: 3

Schedule: MWF 1:00-1:50, Carson 0204

Prerequisites: Calculus II with a minimal grade of 2.0

Required textbooks/materials: Write Your Own Proofs, by Babich and Person. Copies available from the department.

Course Description:  Elementary logic, including sentential calculus and mathematical induction. Basic properties of sets, relations and functions. Denumerable and non-denumerable sets. Designed as an introduction to the nature of mathematical proof. Required for Mathematics majors.

## Student Learning Objectives

The main objective of the course is 
to learn to write clear, rigorous mathematical proofs. This course 
partially satisfies the Connecting Clearly: 
Communication in the Major requirement for the Pathways program. It adopts a 
"communicating in the disciplines" model that transmits the skills required to both learn and create 
knowledge within the chosen academic field, and to develop a professional voice through opportunities 
to write and speak on substantive issues arising from the major. This course will focus on writing.

At the conclusion of the course the students will...

1. Identify at least two types of written communication specific to their discipline. (Applying)
2. Explain what sorts of rhetoric are generally considered effective within the types of discipline 
	specific communication they are studying. (Evaluating)  
3. Explain what sorts of evidence are generally considered valid within the types of discipline 
	specific communication they are studying. (Evaluating) 
4. Produce (and accept feedback on) substantive written and oral work of their own that applies 
	the understanding they have gained through analysis of models of the types of discipline-specific 
	communication. (Creating) 

These learning outcomes will be assessed throughout the course using homework assignments, 
in-class tests, and the final exam. Specifically, SLO #1 will be assessed on most homework assignments; 
SLO #2 on homework assignments and exam questions; SLO #3 on the final exam; and SLO #4 on various 
homework assignments.

In addition to the above outcomes, this course will provide students with an 
opportunity to develop proficiency in the following areas:

* Become independent learners, capable of doing and learning advanced mathematics on their own and in conjunction with others. 
* Know and use basic proof methods. 
* Recognize a correct mathematical proof. 
* Write correct mathematical proofs. 
* Understand and appreciate the role of mathematical language, notation in the development of mathematical concepts. 

## Grading 

We’ll have three midterms (date and time TBA) and one final exam (date and time TBA).
Homework will be written weekly paper work, submitted via Brightspace. 
Grade weighting: Homework: 35%, Exams: 15%, 15%, 15%, 20%.  Final grades will be assigned as follows: 90-100: 4.0, 87-89: 3.7, 83-86: 3.3, 80-82: 3.0, 77-79: 2.7, 73-76: 2.3, 70-72: 2.0, 67-69: 1.7, 63-66: 1.3, 60-62: 1.0, 0-59: 0.0. No grades will be dropped.

Attendance policy: Attendance is expected for all students, but not graded. Please inform your instructor if you have to miss class for any reason.

Late Work Policy: Students have limited opportunities to submit late work, and need permission to do so. 

Calendar of Topics and Assignments: See lecture notes (also shared) for details. 

## Appendices

{{< include ../_syllabus_objects/AI.qmd >}}

{{< include ../_syllabus_objects/oas.qmd >}}

{{< include ../_syllabus_objects/counseling.qmd >}}

{{< include ../_syllabus_objects/disruptive.qmd >}}

{{< include ../_syllabus_objects/food.qmd >}}

{{< include ../_syllabus_objects/land.qmd >}}

{{< include ../_syllabus_objects/success.qmd >}}

{{< include ../_syllabus_objects/support.qmd >}}

