### Student Support
Every student in this class is a valued individual. If you are struggling with issues outside of the classroom, please know that there are professionals both on and off campus who can assist you. If you need immediate assistance, please contact our campus Counseling Center (with free counseling) at (315) 267-2330 or visit their website. Links to other resources are provided below: 
•	[Title IX Coordinator](http://www.potsdam.edu/offices/hr/titleix), Van Housen Extension 392, (315) 267-2516, 
•	[Bias Incident Reporting](http://www.potsdam.edu/about/diversity/biasincident)
•	[Center for Diversity](http://www.potsdam.edu/studentlife/diversity), 223 Sisson Hall, (315) 267-2184
•	University Police, Van Housen Extension, (315) 267-2222 (number for non-emergencies; for an emergency please dial 911) 
•	[Student Conduct and Community Standards](http://www.potsdam.edu/studentlife/studentconduct/codeofconduct), 208 Barrington Student Union, 
•	Reachout (24-hour crisis hotline), (315) 265-2422
•	Renewal House (for victims of domestic violence), SUNY Potsdam Campus Office: Van Housen Extension 390 (open Wednesdays, 9-5:00), (315) 379-9845 (24-hour crisis hotline), Renewalhouse_campus@Verizon.net
•	[Career Services](https://www.potsdam.edu/studentlife/career-services), Lougheed Learning Commons

And please: if you see something, say something. If you see that someone that you care about is struggling, please encourage them to seek help. If they are unwilling to do so, Care Enough to Call has guidelines on whom to contact. Everyone has the responsibility of creating a college climate of compassion.

