---
title: "Homework Problems"
description: "Homework problems for the semester"
number-sections: true
format:
  html:
    smooth-scroll: true # Makes jumping to sections feel less jarring
  
engine: jupyter #Force jupyter notebook to invalidate cache.
---

# Introductory Ring Theory

## 8 and 9

Prove parts 8 and 9 from the list of properties in section 1.4 of the notes. 

## Evaluation 
Let ${\mathbb R}[x]$ be the ring of polynomials with real coefficients, let $c \in {\mathbb R}$, and
let $e_c:{\mathbb R}[x] \to {\mathbb R}$ be the evaluation map at $c$: $e_c(p) = p(c)$. 

1. Demonstrate that $e_c$ is a ring homomorphism.
2. Calculate the image of $e_c$, and prove that your answer is correct.
3. Calculate the kernel of $e_c$, and prove that your answer is correct.

## Kernel zero

Let $f:R \to S$ be a homomorphism of rings. Prove that $\ker(f) = \{0_R\}$ if and only if $f$ is 
injective. 

## Complex matrices

Let ${\mathbb C}$ be the ring of complex numbers, and let $R = \left \{\begin{bmatrix}a&-b\\b&a\end{bmatrix}\,\,|\,\, a, b \in {\mathbb R}\right\}$. 

1. For each ring, identify its zero and one. For each ring, define its addition and multiplication operations.
2. Define a map $f:{\mathbb C} \to R$ and prove that it is a ring homomorphism.
3. Calculate the image and kernel of $f$.

## Searching for elements

Give an example of each type of element in each ring, or state "impossible." No need for proof.

|  | ${\mathbb R}$ | ${\mathbb Z}$ | ${\mathbb Z}_{10}$ | $M^{2 \times 2}_{\mathbb R}$ | ${\mathbb R}[x]$|
|--|--|--|--|--|--|
| A unit (other than 1) in |
| A nilpotent in |
| A zerodivisor in |
| An irreducible in |

## Relativity 

Interpret this problem in ${\mathbb Z}[x]$, in ${\mathbb R}[x]$, in ${\mathbb C}[x]$, and in ${\mathbb Z}[i][x]$. You should get a variety of answers depending on the ring. 

Is $5x^2 + 5$ an irreducible element of the ring? If so, explain why. 
If possible, factor it into irreducible elements. 

## The Problem with $\sqrt{-5}$
In this problem we explore the ring $R = {\mathbb Z}[\sqrt{-5}] = \{a + b \sqrt{-5} | a, b \in {\mathbb Z}\}$.

1. Identify the $0$ and $1$ of $R$. Prove (based on the definition above) that $R$ is closed under addition and multiplication. Use the subring test to deduce that $R$ is a subring of ${\mathbb C}$.
2. To describe the units of $R$, we need something like a length function on it:  For $a+b\sqrt{-5} \in R$, we define $\|a+b\sqrt{-5}\|^2 = a^2+5b^2$.  (Note that this is just the complex square norm function restricted to $R$.)

  - Explain why $\| - \|^2$ is integer valued.
  - Prove that $\Vert v \Vert^2$ is multiplicative in the sense $\Vert vw\Vert^2 = \Vert v\Vert^2\Vert w\Vert^2$
  - Prove (from the previous) that if $v$ is a unit of $R$, then $\|v\|^2 = 1$.

3. Identify all units of $R$.
4. Once units are identified, we can prove that certain elements are irreducible. Demonstrate that $2$, $3$, $1+\sqrt{-5}$, and $1-\sqrt{-5}$ are all irreducible.
5. It will perhaps bother you to see that $2 \cdot 3 = (1+\sqrt{-5}) \cdot(1-\sqrt{-5})$. Among these irreducible factors of six, are any of them unit multiples of others? Why or why not? 

## $(R/I) / (J/I)$

Let $I \subseteq J \subseteq R$, where $I$ and $J$ are ideals and $R$ is a ring. Define $J/I$ to be $\{j+I | j \in J\}$.

1. Prove that $J/I$ is an ideal of $R/I$. 
2. Prove that $(R/I) / (J/I)$ is isomorphic to $R/J$.

## Patterns in ${\mathbb Z}[i]$

Find an infinite repeating pattern of points which, when removed from the lattice ${\mathbb Z}[i]$, do not permit five points in a row, horizontally, vertically, or diagonally, to be found among the remaining points. Minimize the number of points which must be removed. 

1. What proportion of the points of ${\mathbb Z}[i]$ must be removed to exclude five-in-a-row?
2. Sketch a picture of the points which must be removed. 
3. It's possible to choose your points so that they correspond to an ideal $I$ of ${\mathbb Z}[i]$. Is it principal? What is its generator?

## "the light gleams an instant, then it's night once more.” 

Prove that $R = {\mathbb Z}[x]/(x)$ is isomorphic to ${\mathbb Z}$

## Making a prime ideal

Let $R$ be a ring and let $f \in R$ be a nonzero nonnilpotent element. Let $S = \{1, f, f^2, f^3, \ldots\}$. Let $P$ be an ideal maximal among all ideals of $R$ disjoint from $S$. Prove that $P$ is a prime ideal. (Hint: Don't try to prove that $P$ is maximal.)

## Not prime any more

1. Give an example of a ring homomorphism $f:R \to S$ and a prime ideal $P$ of $R$, so that the extension $P^e$ is the unit ideal. 

2. Give an example of a ring homomorphism $f:R \to S$ and a prime ideal $P$ of $R$, so that the extension $P^e$ is a proper ideal (i.e., not the unit ideal), but is not prime. 

## Maximal implies prime

The notes give a rather roundabout demonstration that every maximal ideal $I$ of a commutative ring $R$ 
is prime. It depends on reasoning about the quotient $R/I$. Give a direct proof that every maximal ideal 
is prime, without resorting to the quotient ring $R/I$.

## cecece

Prove this proposition, which is given in the notes without careful proof: Let $f:R \to S$ be a ring homomorphism. Let $I$ be an ideal of $R$ and let $J$ be an ideal of $S$. Then

1. $I \subseteq I^{ec}$.
2. $J^{ce} \subseteq J$.
3. $I^{ece} = I^{e}$.
4. $J^{cec} = J^c$.

Hint: You may assume if $I_1 \subseteq I_2$ then $I_1^e \subseteq I_2^e$ and similarly 
if $J_1 \subseteq J_2$ then $J_1^c \subseteq J_2^c$. You should be able to deduce 3&4 from 1&2. 

## Polynomial Ring is a ring

Prove that the polynomial ring is a ring by proving the eight axioms. By far the hardest 
axiom is multiplicative associativity, which uses the convolutional multiplication rule 
twice. 

## Eisenstein Integers

The **Eisenstein Integers** ${\mathbb Z}[\omega] = \{x+y\omega | x, y \in {\mathbb Z}\}$ where $\omega = \frac{\sqrt{-3}+1}{2}$. Notice that the angle of the complex number $\omega$ is $60^\circ$. 

For this problem you may freely use the multiplicativity of complex norm: $|wz| = |w||z|$ for all complex numbers $w$, $z$. 

1. Sketch the set ${\mathbb Z}[\omega]$ in the plane, including various positive and negative values of $x$ and $y$. You should get a regular lattice of points. 
2. Let $f:{\mathbb Z}[\omega] - \{0\} \to {\mathbb N}$ by $f(a+bi) = a^2+b^2$. Calculate 
a formula for $f(x+y\omega)$ in terms of $x$ and $y$. 
3. Explain why $f(r) \geq 1$ for elements of this ring. 
4. Explain why $f(rs) \geq f(r)$. The symmetric statement $f(rs) \geq f(s)$ follows from commutativity.
5. What is the maximal distance between any point in the plane and the closest point on the lattice ${\mathbb Z}[\omega]$? Prove your answer geometrically. 
6. Let $a, b$ be nonzero elements of ${\mathbb Z}[\omega]$. Let $q = \left[\frac{b}{a}\right]$ and let $r = b-qa$. The notation $[z]$ means "the closest Eisenstein integer to $z$." Prove that 
   - $b = qa+r$
   - $r=0$ or $|r| < |a|$.  
7. Conclude -- what type of ring is ${\mathbb Z}[\omega]$?

## PID instability

Give an example of a PID $R$ and subring $S \subseteq R$ which is not a PID.

## UFD instability

1. Give an example of a UFD $R$ and a subring $S \subseteq R$ which is not a UFD.
2. Give an example of a UFD $R$ and a quotient ring $R/I$ which is not a UFD.

## Relatively prime in $K[x]$

Let $a(x)$, $b(x)$ be irreducible elements of $K[x]$, neither a multiple of the other. Prove that there exist $f(x)$, $g(x)$ in $K[x]$ so that 
$f(x)a(x)+g(x)b(x)=1$. (This is a polynomial identity, not an identity for one value of $x$.)