---
title: "11. Quantile Statistics"
description: "Calculating and understanding min, 25%, 50%, 75%, and max"
engine: jupyter #Force jupyter notebook to invalidate cache.
---


## Preparation
Reread 2.1.5 on box plots and quantile statistics.
Review vocabulary:
Percentile, Quartile, Quintile
Median, Q1, Q3, IQR

## True or False {.activity}
Among American households, about half earn more than the average income and about half earn less.

On a very easy ten point assignment, about half of students will score above average, and about half will score below average

## Mean isn't typical

**Mean** does a poor job describing "typical," because it pulls hard toward outliers. 

**Median** does a better job describing "typical," because it mostly ignores outliers. 

## What is the median?

The median is the middle value by count. Roughly speaking, half the data 
values are less than the median and half are greater.

Finding the median: 

- Sort data numerically
- Find the center. 
- If count is odd, median is the middle one.
- If count is even, median is average of middel two.

Example data values: 5, 7, 8, 9, **9**, **9**, 10, 10, 11, 12

<small>Description: Ten data points are presented in sorted order, starting with 5 and ending with 12. The middle two are accented in bold and are both 9.</small>

The median is 9

## What is the median?

1, 2, 3, 0, 1, 2, 9  ← Median is not zero. Sort first!

0, 1, 1, 2, 2, 3, 9  ← Median is 2.

0, 1, 1, 2, 2, 3, 96  ← Median is still 2. 

The median is insensitive to outliers and individual data errors. The mean is not. 
This is one reason the median is often preferred. 

## Using the median to understand your data. 

What is the median salary of MLB players? Use the mlb.csv dataset.

What is the median income of Americans? Use the acs12.csv dataset. 

What is the median birth weight of American babies? Use the births14.csv dataset.

In all these cases, the mean may be deceptive because it's influenced by outliers. 
The median better reflects what is typical.

## Median is more informative than Mean
Most reports on “typical” American finances use quantile statistics – median household income, median net wealth, median rent, median house price, etc.

In highly unequal societies, measures of wealth are strongly skewed right. Usually median is much smaller than mean.

In the U.S., *median* income is currently about 2/3 of the *average* income (Source: <a href="https://www.ssa.gov/oact/cola/central.html">SSA</a>).

No single statistic describes the distribution fully, but the median often does a better job capturing what’s typical or normal.

## Quartering the data

After sorting a data series, we can make equal quarters by further subdividing 
each half. Just like cutting an apple:

5, 7, **8**, 9, **9** | **9**, 10, **10**, 11, 12

<small>Description: Ten data points are presented in sorted order, starting with 5 and ending with 12. The middle two are accented in bold and are both 9. The third data point, an 8, central within the left half, is accented. The eighth data point, a 10, central within the right half, is also accented.</small>

From this division we can construct the five-number summary:

Min=5, Q1 = 8, Median = 9, Q3 = 10, Max = 12.

These numbers can also be obtained using .describe():

```{python}
#| eval: true
#| echo: true
import pandas as pd
x = pd.Series([5, 7, 8, 9, 9, 9, 10, 10, 11, 12], name='age')
x.describe()
```

## Notes on Q1 and Q3:

The five number summary is the foundation of the box plot.

Odd/even fussiness applies to halves as well.

It’s not literally true that a quarter of the data lies between Q1 and Q2. If $n=10$, how could it be? But such statements are usually nearly true for large and continuous datasets. 

Caution: Jupyter (pandas) uses a slightly fancier policy for quartering the apple. This can cause confusion. Lecture, textbook, and homework are in sync, but pandas is different. Note the 8.25 on the previous slide.

Caution: Median, 50%, and Q2 are all synonyms. Q1 and 25% are synonyms. 

## By hand? Ain’t nobody got time for that!

1. A data analyst needs to calculate Min, Q1, Median, Q3, and Max easily, quickly, and reliably, even for large datasets. How should this would be done? 

2. A certain online homework problem asks for Q1 and Q3 for a list of 27 numbers. There is no .csv file. How can we make Jupyter solve the problem? Construct a Series:

```{python}
#| eval: false
#| echo: true
import pandas as pd
x = pd.Series([18,19,17,20,25,18])
```




## Individual work

Solve Webwork problems in assignment 11.

Here's a quantile statistic: The top 1% of Americans control about as much wealth as the bottom 90% [source: Federal Reserve Economic Data (FRED)]. See what you can do about that.

