---
title: "Math 125"
description: "Probability and Statistics"
format: html
#listing:
#  - id: combined-listing
#    contents: 
#      - "syllabus.qmd"
#      - "slides/*.qmd"
#    type: table
#    fields: [title, description]
---

## Syllabus:

[Math 125 Syllabus](syllabus.html)

## Lectures & Handouts

| Topic | Slides (Interactive) | Handout (Printable) |
|:----------------|:---:|:---:|
| **0:** Welcome & Intro | [Slides [for Welcome]{.visually-hidden}](slides/0_welcome.html) | [Handout [for Welcome]{.visually-hidden}](slides/0_welcome.handout.html) |
| **1:** The Shape of Data | [Slides [for Shape of Data]{.visually-hidden}](slides/1_the_shape_of_data.html) | [Handout [for Shape of Data]{.visually-hidden}](slides/1_the_shape_of_data.handout.html) |
| **2:** Association & Correlation | [Slides [for Association]{.visually-hidden}](slides/2_association_and_correlation.html) | [Handout [for Association]{.visually-hidden}](slides/2_association_and_correlation.handout.html) |
| **3:** Correlation & Causation | [Slides [for Correlation]{.visually-hidden}](slides/3_correlation_is_not_causation.html) | [Handout [for Correlation]{.visually-hidden}](slides/3_correlation_is_not_causation.handout.html) |
| **4-5:** Sampling & Bias | [Slides [for Sampling]{.visually-hidden}](slides/4-5_samping_and_sample_bias.html) | [Handout [for Sampling]{.visually-hidden}](slides/4-5_samping_and_sample_bias.handout.html) |
| **6:** Controlled Experiments | [Slides [for Experiments]{.visually-hidden}](slides/6_controlled_experiments.html) | [Handout [for Experiments]{.visually-hidden}](slides/6_controlled_experiments.handout.html) |
| **7:** Histograms & Countplots | [Slides [for Histograms]{.visually-hidden}](slides/7_dataviz_histogram_and_countplot.html) | [Handout [for Histograms]{.visually-hidden}](slides/7_dataviz_histogram_and_countplot.handout.html) |
| **8:** Boxplots & Scatterplots | [Slides [for Boxplots]{.visually-hidden}](slides/8_dataviz_boxplot_and_scatterplot.html) | [Handout [for Boxplots]{.visually-hidden}](slides/8_dataviz_boxplot_and_scatterplot.handout.html) |
| **9-10:** Mean & Variance | [Slides [for Mean/Variance]{.visually-hidden}](slides/9_10_mean_variance_standard_deviation.html) | [Handout [for Mean/Variance]{.visually-hidden}](slides/9_10_mean_variance_standard_deviation.handout.html) |
| **11:** Quantile Statistics | [Slides [for Quantiles]{.visually-hidden}](slides/11_quantile_statistics.html) | [Handout [for Quantiles]{.visually-hidden}](slides/11_quantile_statistics.handout.html) |
| **12-13:** Probability & Counting | [Slides [for Prob/Counting]{.visually-hidden}](slides/12_13_probability_and_counting.html) | [Handout [for Prob/Counting]{.visually-hidden}](slides/12_13_probability_and_counting.handout.html) |
| **14-15:** Probability Laws | [Slides [for Prob Laws]{.visually-hidden}](slides/14_15_probability_laws.html) | [Handout [for Prob Laws]{.visually-hidden}](slides/14_15_probability_laws.handout.html) |
| **16-17:** Conditional Probability | [Slides [for Conditional Prob]{.visually-hidden}](slides/16_17_conditional_probability.html) | [Handout [for Conditional Prob]{.visually-hidden}](slides/16_17_conditional_probability.handout.html) |
<!--| **18-19:** Normal Distribution | [Slides [for Normal Dist]{.visually-hidden}](slides/18_19_the_normal_distribution.html) | [Handout [for Normal Dist]{.visually-hidden}](slides/18_19_the_normal_distribution.handout.html) |-->
<!--normal is unfinished-->


