---
title: "Complex Analysis"
description: "Lecture notes for Math 681, SUNY Potsdam"
number-sections: true
format:
  html:
    smooth-scroll: true 

engine: jupyter #Force jupyter notebook to invalidate cache.
---

<div style="display:none;">
$
\newcommand{\abs}[1]{\left| #1 \right|}
\newcommand{\modulus}[1]{\left| #1 \right|}
\newcommand{\norm}[1]{\left\| #1 \right\|}
\newcommand{\innerProd}[1]{\langle #1 \rangle}
$
</div>

# Dedication

To Dad,

my best teacher and my favorite student

# The Complex Number System

## Constructions of ${\mathbb C}$

The set of complex numbers ${\mathbb C}$ is defined by accepting
$\sqrt{-1}$, usually written $i$, into the community of numbers. Once we
accept $\sqrt{-1}$, we have to accept arithmetical combinations which
involve it, such as $5+6\sqrt{-1}$, usually written $5+6i$. We have to
accept division by $i$, which fortunately is the same as multiplication
by $-i$. (Since $-i\cdot i=1$, the reciprocal of $i$ is $-i$.) It turns
out that general combinations of the form $a+bi$ are "enough" in the
sense that for any two of them we can identify a sum, difference,
product, or quotient also of the form $a+bi$.

We therefore wish to define ${\mathbb C}$ to be "only" the set of
numbers $a+bi$. But in order to do so, we need to give an account of
what $a+bi$ represents. Some authors define ${\mathbb C}$ to be the set
of "formal sums" $a+bi$. This seems to avoid, rather than answer, the
basic question ("What does $a+bi$ mean?") by defining "$a+bi$" to be a
form representing its own form. It leaves many questions unanswered: Is
$3+1i$ identical with $3+i$? or $1+2+i$? or $i+3$? We feel these should
be the same, but they differ in form. If ${\mathbb C}$ is defined to be
a set of forms, these things should be unequal! Quite generally, to
define a thing as a "formal" \[form\] is to intentionally confuse its
nature with its method of expression, in order to avoid the real work of
describing its nature. We can do much better:



::: {#def-C .definition}
${\mathbb C}$ 
is defined to be the set of ordered pairs $(a,b)$:
$${\mathbb C} \equiv \{(a,b) \, | \, a, b \in {\mathbb R}\}$$ 
with associated addition and multiplication formulas:
$(a,b) + (c,d) = ((a+c)  , (b + d))$, and
$(a,b) * (c,d) = ((ac-bd) , (ad+bc))$.
:::


This definition is clear and rigorous, but it has two disadvantages:
First, ${\mathbb R}$ is not a subset of this set, but we want
${\mathbb R}\subset {\mathbb C}$. We solve this problem by identifying
(refusing to distinguish) $x \in {\mathbb R}$ with
$(x,0) \in {\mathbb C}$. (The alternative is to use
${\mathbb C}= ({\mathbb R}\times {\mathbb R}) - ({\mathbb R}\times \{0\}) \cup {\mathbb R}$
instead, but that forces the sum and product rules to break into cases.)

Next, the definition requires us to write complex numbers in the form
"$(2,5)$", which is strange and unnatural. We would rather write $2+5i$.
A sleight of hand solves the problem: First, we *define* $i$ to be the
complex number $(0,1)$. With the identifications $a = (a,0)$ and
$b=(b,0)$ in mind, we compute $a+bi=(a,0)+(b,0)(0,1) = (a,b)$, as
desired. Thus $a+bi =(a,b)$ is not a "shorthand" but a legitimate
computation.

There is another option for the definition, for those who know a little ring theory:



::: {#def-C-algebraic .definition}
${\mathbb C}$ is that quotient ring of
${\mathbb R}[i]$ (here, $i$ is used as an indeterminant variable, just
like the variable usually written $x$) obtained by modding out by the
principle ideal generated by $i^2+1$.
$${\mathbb C}= {\mathbb R}[i]/(i^2+1)$$
:::



This definition has many advantages: It explains the addition and
multiplication formulas, it makes it trivial to see that ${\mathbb C}$
is a ring, and pretty easy to show that ${\mathbb C}$ is a field. But
the elements of ${\mathbb R}[i]/(i^2+1)$ are cosets, and we really don't
want complex numbers to be cosets, so it adds an unnecessary level of
complication. Again we have the problem that ${\mathbb R}$ is not a
subset of ${\mathbb R}[i]/(i^2+1)$, but it is standard practice in
algebra to identify a ring $R$ with its image in $R[x]$ or $R/I$, and
these conventions give us ${\mathbb R}\subset {\mathbb R}[i]/(i^2+1)$.

::: {#thm-C-equivalent .theorem}
The definitions are equivalent in the sense that both
structures are fields and are isomorphic.
:::

::: {.proof}
Since $i^2+1 \in {\mathbb R}[i]$ is monic of degree $2$, every
element of ${\mathbb R}[i]/(i^2+1)$ can be written uniquely in the form
$a+bi$ (The linear polynomial remaining after polynomial long division
by $i^2+1$.) We may define
$\phi:{\mathbb R}[i]/(i^2+1) \to {\mathbb R}\times {\mathbb R}$ by
$\phi(a+bi) = (a,b)$. It's easy to check that addition and
multiplication are preserved. It follows that
${\mathbb R}\times {\mathbb R}$ is a ring (in the first place! We hadn't
yet checked it.) and is isomorphic to ${\mathbb R}[i]/(i^2+1)$. To show
that ${\mathbb R}[i]/(i^2+1)$ is a field, note that ${\mathbb R}[i]$ is
a PID and $i^2+1$ is irreducible, so $(i^2+1)$ is a maximal ideal. Thus
the quotient is a field. 
:::

The fact that it is a field indicates that it is a full number system --
no other combinations of $i$ are necessary. It's reassuring that
quotients $(a+bi)/(c+di)$ exist, but we also need to calculate them. To
find the reciprocal of a complex number $a+bi$, we apply the following
trick:



$$\frac{1}{a+bi} = \frac{a-bi}{(a+bi)(a-bi)} = \frac{a-bi}{a^2+b^2} = \frac{a}{a^2+b^2} + \frac{-b}{a^2+b^2} i$$

Note that the trick fails exactly when $a+bi=0$. The number $a-bi$ is
called the conjugate of $a+bi$. The conjugate function is usually
written with an overline: $\overline{a+bi} = a-bi$.

::: {#exr-factor-13 }
 (Factoring 13) The Gaussian integers are numbers of
the form $a+bi$ for $a, b \in {\mathbb Z}$. They form a ring, usually
written ${\mathbb Z}[i]$. They play the role of integers for the complex
numbers. Prove that the "prime" number $13$ is the product of two
smaller Gaussian integers. Here "smaller" means in norm: $w$ is smaller
than $z$ if $|w|<|z|$.
:::

::: {#exr-matrix-C }
 (Matrix representation) Show that the system of all
matrices of the form
$\left(\begin{array}{cc}\alpha & -\beta \\ \beta & \alpha \end{array}\right)$
(with $\alpha, \beta \in {\mathbb R}$) with matrix addition and
multiplication is isomorphic to the field of complex numbers.
Furthermore, show that any such matrix can be written in the form
$\left(\begin{array}{cc}r & 0 \\ 0 & r \end{array}\right)
\cdot\left(\begin{array}{cc}\cos(\theta) & -\sin(\theta) \\ \sin(\theta) & \cos(\theta) \end{array}\right)$
for some $r\in [0,\infty)$ and $\theta\in [0, 2\pi)$.
:::

## More operations

We have four more operations on complex numbers which help us understand
them in terms of real numbers:

::: {#def-conjugate-modulus-re-im .definition}
We define four special functions on ${\mathbb C}$:
For a complex number $z=a+bi$, we define:

1.  $\overline{z} = a-bi$. This is called the *conjugate* of $z$.

2.  $|z| = \sqrt{a^2+b^2}$. This is called the *modulus* of $z$.

3.  $\Re(z) = Re(z) = a$. This is called the real part of $z$.

4.  $\Im(z) = Im(z) = b$. This is called the imaginary part of $z$.
    Notice that the "imaginary part" is a real number!
:::

::: {#prp-mod-re-im-via-conjugate .proposition}
For any complex numbers $w$ and $z$:

1.  $|z|^2 = z \overline{z}$

2.  $Re(z) = \frac{1}{2}(z+\overline{z})$

3.  $Im(z) = \frac{1}{2i}(z-\overline{z})$

4.  $|wz| = |w||z|$.
:::

::: {#exr-prove-mod-re-im }
 Prove the above proposition by writing $z$ in the form
$z=a+bi$. (This technique -- proving things by writing $z$ in the form
$a+bi$ is one we wish to outgrow, and the statement of this proposition
will help us do so. We do not wish to constantly regard $z$ as two
variables to be independently manipulated!)
:::

So all four special functions can be expressed using the conjugate. What
makes conjugation so special? To start, it's an automorphism of
${\mathbb C}$:

::: {#exr-conjugation-automorphism }
 (Conjugation is an automorphism) Verify by direct
calculation, using the definitions of $+$ and $\cdot$, that
$z \mapsto \overline{z}$ is a field homomorphism from ${\mathbb C}$ to
${\mathbb C}$. In order to show that it is bijective, provide its
inverse function. Verify that conjugation fixes every element of
${\mathbb R}$.
:::

::: {#cor-conjugate-iso .corollary}
For complex numbers $w$ and $z$:

1.  $\overline{w\pm z} = \overline{w}\pm \overline{z}$

2.  $\overline{wz} = \overline{w}$ $\overline{z}$

3.  $\overline{w/z} = \overline{w}/\overline{z}$
:::

Of course the identity map $id:{\mathbb C}\to {\mathbb C}$ is also an
automorphism fixing ${\mathbb R}$. But there are no other such maps. In
the language of Galois Theory, conjugation is the single nontrivial
element of the Galois group of ${\mathbb C}$ over ${\mathbb R}$.

::: {#exr-galois-C-R }
 Prove that any field automorphism
$\phi:{\mathbb C}\to {\mathbb C}$ which fixes ${\mathbb R}$ must be
conjugation or the identity. (Hint: What can $\phi(i)$ be?)
:::

## Basic Inequalities and relations

Algebra is powerful, but we wish to study the analysis of ${\mathbb C}$.
Analysis begins with inequalities.

::: {#thm-rebounds .prop}
**Proposition 1.7**. *For any complex number $z$:
$$-|z| \leq Re(z) \leq |z| \hspace{3em}\text{ and}\hspace{3em} -|z| \leq Im(z) \leq |z|$$
...with equality, respectively, if $z$ is nonpositive real, nonnegative
real, nonpositive imaginary (i.e., $bi$ for $b \leq 0$), and nonnegative
imaginary.*
:::

::: {#exr-prove-re-im-inequalities }
 Prove the previous proposition by writing $z=a+bi$ and
using properties of real numbers $a$ and $b$.
:::

Metric topological reasoning requires a triangle inequality in
${\mathbb C}$:

::: {#prp-triangle-inequality .proposition}
**(Triangle Inequality)**
Let $w$ and $z$ be complex
numbers. Then:
1. $|w \pm z| \leq  |w|+|z|$ with equality if and only if $z=0$ or
    $w/z \in {\mathbb R}^\pm$

2.  $|w \pm z| \geq |w|-|z|$ with equality if and only if $z=0$ or
    $w/z \in {\mathbb R}^\mp$
:::

::: {.proof}
The modulus of a sum $|w+z|$ involves an inconvenient square
root of a sum. It can be avoided by reasoning about square modulus
instead:

$|w+z|^2 = (w+z)\overline{(w+z)} = w\overline{w} + z\overline{z} + w \overline{z}+\overline{w}z = |w|^2 + |z|^2 + 
w \overline{z}+\overline{w \overline{z}} = |w|^2 + |z|^2 + 2Re(w\overline{z})$

Now Proposition [1.7](#thm-rebounds){reference-type="ref"
reference="thm-rebounds"} allows us to relate $Re(w\overline{z})$ to
$|w\overline{z}| = |w||\overline{z}| = |w||z|$, obtaining:

$|w|^2 + |z|^2 - 2|w||z|\leq |w+z|^2 \leq |w|^2 + |z|^2 + 2|w||z|$, thus

$(|w|-|z|)^2 \leq |w+z|^2 \leq (|w|+|z|)^2$. All these values except
possibly the far left are positive real numbers, so we may drop the
squares:

$|w|-|z| \leq |w+z| \leq |w|+|z|$.

Again by Proposition [1.7](#thm-rebounds){reference-type="ref"
reference="thm-rebounds"}, equality holds, respectively, when
$w\overline{z}$ is nonpositive real, or nonnegative real, respectively.
If $z \neq 0$, $w \overline{z} = |z|^2 w/z$, and $|z|^2$ is necessarily
positive real.

This completes the proof for $|w+z|$. For the case $|w-z|$ simply apply
the first case with $-z$ in place of $z$. 
:::

::: {#exr-triangle-inequality-n-ary }
 Use the triangle inequality to prove that
$|z_1 + z_2 + \ldots + z_n| \leq |z_1| + |z_2| + \ldots + |z_n|$
:::

## Polar representation

Let $w = a+bi$ be a complex number. Let $r$ denote the distance from $0$
and $\theta$ denote the counterclockwise angle from the positive real
axis, in radians. Note that we have already discussed an operation on
$w$ that yields $r$, namely $r=|w|$. The operation which yields $\theta$
is called $\arg(w)$, but it is not well behaved because $\theta+n2\pi$
has the same geometric significance as $\theta$. Usually we insist
$\arg(w) \in [0, 2\pi)$(sometimes $(-\pi, \pi]$). This makes $\arg$ a
definitive function on ${\mathbb C}- \{0\}$, but doesn't make it
continuous.

Notice that $a = |w| \cos(\theta)$ and $b = |w| \sin(\theta)$, so
$w = |w| (\cos(\theta) + i\sin(\theta))$. The parenthesized portion is
called $\operatorname{cis}(\theta)$:

::: {#def-cis .definition}
$$\operatorname{cis}(\theta) \equiv_{\text{def}} \cos(\theta) + i \sin(\theta)$$
:::

Thus $w = |w|\operatorname{cis}(\theta)$.

::: {#prp-exponent-law-cis .prop}
The function
$\operatorname{cis}:{\mathbb R}\to {\mathbb C}$ has the following
properties

1.  $\operatorname{cis}(0)=1$

2.  $\operatorname{cis}(\alpha+\beta) = \operatorname{cis}(\alpha)\operatorname{cis}(\beta)$

3.  $\operatorname{cis}(\alpha-\beta) = \operatorname{cis}(\alpha) / \operatorname{cis}(\beta)$

4.  $\operatorname{cis}(n\alpha) = \operatorname{cis}(\alpha)^n$.

5.  $|\operatorname{cis}(\theta)| = 1$
:::

::: {.proof}
Parts 1 and 5 are obvious. 2 is essentially the angle sum
formulas for $\cos$ and $\sin$. (Digression: Proof of angle sum
formulas, using geometry: Represent the angle $\theta+\phi$ as on a unit
circle, then drop a perpendicular to the angle $\theta$, and from there
another perpendicular to $x$-axis, and calculate the height.) 3 follows
from 2. 4 follows from 2 with induction. 
:::

We would like to claim that
$\frac{d}{d\theta} \operatorname{cis}(\theta) = -\sin(\theta) + i\cos(\theta) = i\operatorname{cis}(\theta)$.
Compare to normal rules for differentiating exponential functions
$\frac{d}{dt} e^{kt} = ke^{kt}$, which reproduce the same function times
a constant. We can't explain the formula
$\frac{d}{d\theta} \operatorname{cis}(\theta) = i\operatorname{cis}(\theta)$
without a theory of derivatives of functions
$f:{\mathbb R}\to {\mathbb C}$. We are nevertheless tempted by this
derivative calculation and by parts 1-4 above to regard
$\operatorname{cis}$ as a kind of exponentiation. Later we will learn
that $\operatorname{cis}(\theta) = e^{i\theta}$, but we are not yet
ready to even define complex exponentiation. The students should
understand, however, that $\operatorname{cis}$ is a "temporary"
notation, to be replaced later. All of our theorems about
$\operatorname{cis}$ will be regarded, later, as theorems about
$e^{i\theta}$.

::: {#exr-triple-angle }
 Use the laws for $\operatorname{cis}(\theta)$ to
derive "triple angle formulas" for $\sin$ and $\cos$. *Do not* use the
angle sum formulas directly (although of course the proof of proposition
@prp-exponent-law-cis depends on them).
:::

::: {#exr-cis-group-homomorphism }
 The function $\operatorname{cis}$ is a group
homomorphism. What are its domain and range? (Tell each group by telling
the set and its operation.) What is its kernel?
:::

::: {#exr-sixth-roots-unity }
Find the sixth roots of unity. Give their values
arithmetically and include a picture of them in the complex plane.
Together they form a group, by proposition
@prp-exponent-law-cis (do not prove), isomorphic to what
familiar group? What is the operation of the group? What is the identity
of the group?
:::

## Geometry of operations

If ${\mathbb C}$ can be identified with ${\mathbb R}\times {\mathbb R}$,
then it is the domain of classical Euclidean geometry. Complex
operations should have geometric interpretations. What is the geometric
significance of addition? of multiplication?

Addition is vector addition, so it corresponds geometrically to the
parallelogram rule. Using polar coordinates, we can now derive the
geometric significance of multiplication: If
$w = |w| \operatorname{cis}(\alpha)$ and
$z = |z| \operatorname{cis}(\beta)$ are complex numbers, then
$wz = |w||z|\operatorname{cis}(\alpha)\operatorname{cis}(\beta) = |w||z|\operatorname{cis}(\alpha+\beta)$,
a complex number whose norm is the product, and whose argument is the
sum. In short, magnitudes multiply and angles add. Note that for any
fixed $w \in {\mathbb C}$, the map $z \mapsto wz$ is a fairly simple
transformation of the plane -- an expansion by a factor of $|w|$, and a
rotation by $\arg(w)$, fixing the origin.

We now summarize the geometric significance of each of the fundamental
operations on complex numbers:

1.  Addition can be interpreted as a parallelogram rule, as for vectors.

2.  Subtraction can be interpreted as a parallelogram rule with a
    reversal, as for vectors.

3.  Multiplication requires multiplication of moduli and addition of
    angles.

4.  Division requires division of moduli and subtraction of angles.

5.  Modulus represents distance from $0$.

6.  Conjugation is a vertical flip over the real axis.

7.  Real part and imaginary part are horizontal and vertical coordinate.

## The Riemann Sphere

For real functions, we often attach $\infty$ and $-\infty$ to the system
${\mathbb R}$, but not algebraically: $8+\infty$ is not defined. We do
attach them topologically, though: $\lim_{a \to \infty} f(x)$ and
$\lim_{a \to 0} f(x) = \infty$ are both defined. Topologically speaking,
the extended real line is a compactification of ${\mathbb R}$, a
topological extension space which is compact.

The extension of ${\mathbb C}$ is similar in that it is topological, and
causes these limits to be defined. It is different in the following
ways:

1.  There is only one infinity. The alternative was not two, but
    infinitely many, one for each direction of escape! (This
    "alternative" comment is open-ended. It could suggest spaces
    isomorphic to $P^2_{\mathbb R}$, a closed unit disk, or even the
    Stone-Cech compactification.)

2.  We often allow a substantial amount of arithmetic with infinity:
    $a * \infty = \infty$ (for nonzero $a$) , $a / \infty =0$, and
    $a+\infty = a-\infty = \infty$. In fact the only arithmetical forms
    we don't allow are $\infty \pm \infty$, $\infty / \infty$,
    $0 * \infty$, $0/0$. We even allow $a/0 = \infty$ and
    $b/\infty = 0$. However, we cannot do these things without spoiling
    the *field structure* of ${\mathbb C}$, so the extended system is
    not a good algebraic structure. The guiding principle is whether or
    not a potential operation $a \star b$ is continuous near infinity,
    zero, or wherever, as a function of both of its inputs. To explain
    this we need to have a topology in place which allows us to define
    continuity.

3.  We use a sphere model to picture ${\mathbb C}\cup \{\infty\}$, and
    linear projection to explain the correspondence. Therefore we need
    to:

4.  define a topological structure on the Riemann sphere and show it
    topologically equivalent to the sphere. We can do this via standard
    compactifications. (illustrated b/c you haven't seen
    compactifications!)

5.  We use coordinatized analytic geometry to compare the sphere to the
    Riemann Sphere in a nontrivial way.

### The projection

We define a map $p$ from $S^2 - \{(0,0,1)\}$ to ${\mathbb C}$ by
projection from the north pole, identifying ${\mathbb C}$ with the $x-y$
plane in ${\mathbb R}^3$ (That is, $a+bi$ is identified with
$(a,b,0) \in {\mathbb R}^3$). We wish to find a formula for this
projection map, in both directions. Let us write $(x_1, x_2, x_3)$ for
an arbitrary point on $S^2$, subject of course to the condition
$x_1^2+x_2^2+x_3^2=1$, and let us write $z = a+bi$ for an arbitrary
point on ${\mathbb C}$, which we identify with the vector
$(a,b,0) \in {\mathbb R}^3$. Since $(x_1, x_2, x_3)$ is on the line
connecting $(0,0,1)$ to $(a,b,0)$, we have some $t$ for which
$t(0,0,1) + (1-t)(a,b,0) = (x_1, x_2, x_3)$. We see immediately that
$t=x_3$, so $a = \frac{x_1}{1-x_3}$ and $b = \frac{x_2}{1-x_3}$. This
gives the formula for $z = a+bi$ in terms of $(x_1, x_2, x_3)$:
$$z = a+bi = p(x_1, x_2, x_3) = \frac{x_1 + i x_2}{1-x_3}$$

We wish to also provide a formula for the inverse function. This is
harder because we must solve for $x_1$, $x_2$, and $x_3$ in terms of
$z = a+bi$. We begin by taking square moduli of the equation above.
(Note the denominator $1-x_3$ is a real constant.)



\begin{aligned}
|z|^2 &= \frac{x_1^2 + x_2^2}{(1-x_3)^2} \\
&= \frac{1-x_3^2}{(1-x_3)^2} & \text{ (because $(x_1, x_2, x_3)$ is on the sphere.)} \\
&= \frac{1+x_3}{1-x_3} & \text{ (cancel after factoring $1-x_3^2$) } \\
\end{aligned}

We multiply by $1-x_3$ to solve for $x_3$:

$$|z|^2 - |z|^2x_3 = 1+x_3 \hspace{2em} \text{ and } \hspace{2em} x_3 = \frac{|z|^2 - 1}{|z|^2+1}$$

It follows that the denominator $1-x_3$ is equal to
$1-x_3 = \frac{2}{|z|^2+1}$. Since $x_1 = a(1-x_3)$ and $x_2 = b(1-x_3)$
we now have:

$$x_1 = \frac{2a}{\modulus{z}^2+1} \hspace{3em} x_2 = \frac{2b}{\modulus{z}^2+1} \hspace{3em} x_3 = \frac{\modulus{z}^2-1}{\modulus{z}^2+1}$$

$$p^{-1}(z) = \left(\frac{2a}{\modulus{z}^2+1}, \frac{2b}{\modulus{z}^2+1}, \frac{\modulus{z}^2-1}{\modulus{z}^2+1}\right)$$



The maps $p$ and $p^{-1}$ above are continuous and give a topological
homeomorphism between ${\mathbb C}$ and $S^2 - \{(0,0,1)\}$. Notice that
the algebra above fails if $1-x_3=0$. There is only one such point on
the sphere, namely the north pole itself $(0,0,1)$. Here the geometry of
the "unique" line through the north pole and *itself* also fails, but
this is our intention. The coordinate $x_3$ is an *increasing* function
of $|z|$, taking values in $[-1,1)$, and that regions
$B(0,M) \subseteq {\mathbb C}$ correspond to regions
$\left \{(x_1,x_2,x_3) \in S^2 | x_3 < \frac{M^2-1}{M^2+1}\right \}$. As
$|z|$ grows larger, $x_3$ approaches $1$. The set
${\mathbb C}\cup \{\infty\}$ is not a topological space in any
reasonable way, but the completed set $S^2$ is. By extending $p$ and
$p^{-1}$ so identify $p(0,0,1) = \infty$ and $p^{-1}(\infty) = (0,0,1)$,
we can assign a topology to ${\mathbb C}\cup \{\infty\}$ homeomorphic to
that of $S^2$, making $p$ a homeomorphism by fiat.

::: {#exr-automorphisms-riemann-sphere }
For each of the functions from ${\mathbb C}$ to
${\mathbb C}$, find a formula for the corresponding function from $S^2$
to $S^2$ (in $x_1, x_2, x_3$ coordinates.) You can do this by creating
the composition $p^{-1}\circ f \circ p$ of maps
$S^2 \to {\mathbb C}\to {\mathbb C}\to S^2$ and simplifying
algebraically.

For each function, describe how the resulting spherical function can be
interpreted as a geometric motion on the sphere.

1.  $f(z) = \overline{z}$

2.  $g(z) = -z$

3.  $h(z) = 1/z$
:::

::: {#exr-riemann-sphere-circles}
(hard) Prove that circles on $S^2$ correspond, by
stereographic projection, to circles and lines on ${\mathbb C}$. Which
circles on $S^2$ correspond to lines on ${\mathbb C}$? Explain with
proof.
:::

::: {#exr-riemann-sphere-distance }
(hard). Let $w, z \in {\mathbb C}$ and let $d(w, z)$
denote the distance between the points corresponding to $w$ and $z$ on
$S^2$. Prove:
$$d(w,z) = \frac{2\modulus{w-z}}{\sqrt{1+\modulus{w}^2}\sqrt{1+\modulus{z}^2}}$$
:::

# Metric Spaces and the Topology of ${\mathbb C}$

## Metric Spaces

::: {#def-metric-space .definition}
A **metric space** is a set $X$ together with a
function $d:X \times X \to {\mathbb R}$ (called a **distance function**
or *metric*) so that

1.  (Zero) $d(x,y)=0$ iff $x=y$

2.  (Nonnegative) $d(x,y) \geq 0$

3.  (Symmetry) $d(x,y) = d(y,z)$

4.  (Triangle inequality) $d(x,z) \leq d(x,y) + d(y,z)$
:::

The two main examples are ${\mathbb R}$ with distance function
$d(x,y) = |y-x|$ (absolute value) and ${\mathbb C}$ with distance
function $d(w,z) = |z-w|$. These two alone justify the abstraction
above, but there are countless other important metric spaces. Note that
we have proven the triangle inequality for ${\mathbb C}$.

Some discussion: Analysis is often a game of estimation, defined by
proving that some absolute difference $|P-Q|$ is less than
$\varepsilon$. Any proof that $|P-Q| < \varepsilon$ with *arbitrary*
$\varepsilon>0$ is a roundabout way to prove the equality $P=Q$. The
role of the triangle inequality is to estimate by waypoints: If $P$ is
nearly $P'$, which is close to $Q'$, which is about $Q$, we find a way
to prove $|P-P'|<\varepsilon/3$, $|P'-Q'|<\varepsilon/3$, and
$|Q'-Q|<\varepsilon/3$. The combination of these facts to say
$|P-Q|<\varepsilon$ is the triangle inequality. Such a proof is usually
written this way:
$|P-Q| = |P-P'+P'-Q'+Q'-Q|  \leq_{\text{(triangle inequality)}}  |P-P'|+|P'-Q'|+|Q'-Q| 
< \varepsilon/3 + \varepsilon/3 + \varepsilon/3 = \varepsilon$. Note
that the first step seems "magical" until we become accustomed the
trick.

::: {#def-open-ball .definition}
An **open ball** $B(x,\varepsilon)$ in a metric
space $X$ is a set of the form $\{y\in X | d(x,y)<\varepsilon\}$. A
**closed ball** is similar:
$\overline{B}(x, \varepsilon) = \{ y \in X | d(x,y)\leq \varepsilon\}$.
:::

::: {#def-open .definition}
A set $A$ is **open** if every point $a \in A$ is
contained in some open ball $a \in B(a,\varepsilon) \subseteq A$. A set
is **closed** if its complement is open.
:::

The terms *open* and *closed* are oddly chosen, since a set can be both,
or neither. Perhaps whoever chose these terms was unfamiliar with doors.

::: {#prp-metric-open .proposition}
The set of open sets in a metric space $(X,d)$
satisfies the axioms for open sets in an abstract topology. That is,

1.  $\emptyset$ and $X$ are open sets.

2.  Unions of arbitrary families of open sets are open.

3.  Intersections of finite families of open sets are open.
:::

::: {#prp-metric-closed .proposition}
The set of closed sets in a metric space $(X,d)$
satisfies the axioms for closed sets in an abstract topology. That is,

1.  $\emptyset$ and $X$ are closed sets. 

2.  Intersections of arbitrary families of closed sets are closed.

3.  Unions of finite families of closed sets are closed.
:::



::: {#def-iota .definition}
**(Iota notation)**
We write the symbol
"$\iota$" (a Greek iota),
pronounced "that" or "the unique," to refer to some definite thing by
means of a property that it alone has. The complete notation treats $\iota$
as a quantifier:
$$ \iota x \enspace P(x) $$
and means the unique value of $x$ such that $P(x)$. If no such value or multiple
values exist, we interpret $\iota x$ as an error and say that $ \iota x \enspace P(x) $ 
does not exist.
:::

For example,
"$\iota x \enspace x^3 = 64$" means "the
unique $x$ whose cube is $64$," which of course is $4$:
$(\iota x \enspace x^3 = 64) = 4$. On the contrary,
"$\iota x \enspace x > 0$" fails to refer to
anything. This should remind the reader of standard limit notation,
which can also fail to refer to any answer if a limit "is not defined" or
"does not exist". In fact, limits can be described as a special case of
$\iota$-notation, and we will often define limits below using $\iota$.

The notation "$\iota$" is Bertrand
Russell's notation for definite description, but our policy for
interpretation differs from Russell's. The symbol
$\iota x$ acts like a quantifier in that
it anticipates a statement involving $x$, but a statement
$\iota x  P(x)$ is grammatically a noun
clause, not a complete statement.

::: {#def-sequence-convergence .definition}
**(Sequence convergence)**
Let $(x_n)_{n \in {\mathbb N}}$ be a sequence in a metric space $X$. The
limit of the sequence is defined to be
$$\lim_{n\to \infty} x_n \equiv \iota L \enspace \forall \varepsilon>0 \enspace \exists N \enspace \forall n > N \enspace |x_n - L|< \varepsilon$$ 
equivalently,
$$\lim_{n\to \infty} x_n \equiv \iota L \enspace\forall \text{ open } U \ni L \enspace \exists N \enspace \forall n>N \enspace x_n \in U$$ 
:::

Of course the limit of a
sequence may or may not exist. If it exists we say that $x_n$ is
convergent and that it converges to $L$. We write $x_n \to L$. (If a
limit is *bad*, like $\lim_{n \to \infty} (-1)^n$, we contend that it
lacks *existence*, not *definition*. Any sequential limit in a metric
space is "defined" in the literal sense that a definition is provided
above and an alternate definition would conflict. This author's position
-- that a notation can be "defined" but not refer to an existent thing
-- is not standard.)



::: {#exr-equivalence-sequence-convergence }
 Prove the implied equivalence in the previous
definition
:::

::: {#prp-sequentially-closed-open .proposition}
**(Sequentially closed and open)**
Let $X$ be a metric
space. A set $A \subseteq X$ is closed if and only if for any convergent
sequence $(x_n) \subseteq A$, the limit $\lim_n x_n \in A$. On the other
hand, a set $A$ is open if and only if no sequence outside $A$ converges
to a point of $A$.*
:::

The reader should beware that in nonmetric topologies, convergence of
sequences does not characterize open and closed sets.

::: {#def-interior .definition}
Let $A \subseteq X$ be a subset of a metric space.
The **interior** of $A$, written $A^0$ is, equivalently,

1.  $\bigcup \{U\,|\,U \subseteq A, U \text{ open}\}$

2.  $\{x \in X \,|\, x \in U \subseteq A \text{ for some open $U$}\}$

3.  $\{x \in X \,|\, B(x,\varepsilon) \subseteq A \text{ for some $\varepsilon>0$}\}$
:::

::: {#exr-equivalences-interior}
 Prove the implied equivalences in the previous
definition
:::

::: {#def-closure .definition}
Let $A \subseteq X$ be a subset of a metric space.
The **closure** of $A$, written $\overline{A}$ is, equivalently,

1.  $\bigcap \{C\,|\,C \supseteq A, C \text{ closed}\}$

2.  $\{x \in X \,|\, U \cap A \neq \emptyset  \text{ for every open $U \ni x$}\}$

3.  $\{x \in X \,|\, B(x,\varepsilon) \cap A \neq \emptyset \text{ for every $\varepsilon>0$}\}$

4.  $\{x \in X \,|\, x \text{ is the limit of some sequence $(x_n)$ in $A$}\}$
:::

::: {#exr-equivalences-closure}
 Prove the implied equivalences in the previous
definition
:::

In general $A^0 \subseteq A \subseteq \overline{A}$. Any open set equals
its interior, and any closed set equals its closure.

## Continuity

::: {#def-continuous .definition}
A function $f: (X,d) \to (Y,\rho)$ from one metric
space to another is **continuous** if, equivalently,

1.  $\forall x_0 \in X \enspace \forall \varepsilon>0 \enspace \exists \delta>0 \enspace \forall x\in X \enspace d(x,x_0)<\delta \to \rho(f(x),f(x_0)) < \varepsilon$

2.  For any open set $U \subseteq Y$, $f^{-1}(U)$ is open.

3.  For any closed set $C \subseteq Y$, $f^{-1}(C)$ is closed.

4.  For any convergent sequence $(x_n)$, $\lim_n f(x_n) = f(\lim_n x_n)$
:::

::: {#exr-equivalences-continuity}
 Prove the implied equivalences in the previous
definition
:::

Sequential limits are identified by some integer input (the index) which
goes to infinity. A sequence is just a function of such an input. We
also have limits in which some input $x$, varying in a metric space $X$,
approaches a fixed point $x_0$. Thus we define the limit of a (not
necessarily continuous!) function defined on $X$.

::: {#def-limit-function .definition}
Let $f: (X,d) \to (Y,\rho)$ be a function from a
metric space to another. Let $x_0 \in X$. We define the limit:
$$\lim_{x \to x_0} f(x) \equiv_{def} \iota y_0 \in Y \enspace \forall \varepsilon>0 \enspace \exists \delta >0 \enspace \forall x \in X \enspace 0<d(x,x_0)<\delta \to \rho(f(x),y_0)<\varepsilon$$
:::

As in basic Calculus, the limit $\lim_{x \to x_0} f(x)$ may or may not
exist. Note that this empowers us to discuss $\lim_{x \to x_0} f(x)$
when $f:{\mathbb R}\to {\mathbb R}$, $f:{\mathbb C}\to {\mathbb C}$,
$f:{\mathbb R}\to {\mathbb C}$, or $f:{\mathbb C}\to {\mathbb R}$. All
four cases will be important.

::: {#def-continuous-at .definition}
A function $f$ is **continuous at $x_0$** if
$\lim_{x \to x_0} f(x) = f(x_0)$.
:::

Note that continuity at $x_0$ does not require continuity, not even in a
neighborhood of $x_0$. But if $f$ is continuous at every point, it is
continuous.

If we have a sequence $\{f_n\}$ of functions and a sequence $(x_m)$ of
inputs, we may take limits in two ways:
$\lim_{n \to \infty} \lim_{m \to \infty} f_n(x_m)$ and
$\lim_{m \to \infty} \lim_{n \to \infty} f_n(x_m)$. Limits of this type
do not always commute, and we must use caution to distinguish them
carefully.

## Connectedness

::: {#def-clopen .definition}
A set $U$ in a metric space $(X,d)$ is **clopen**
if it is both open and closed.
:::

::: {#def-connected .definition}
A metric space $X$ is **disconnected** if it is the
union of two nonempty disjoint open sets. Equivalently, if it has a
clopen set other than $\emptyset$ and $X$. A subset $A \subset X$ is
**disconnected** if the metric space $(A,d)$ is disconnected. A set is
**connected** if it is not disconnected.
:::

::: {#prp-interval-connected .proposition}
Intervals in ${\mathbb R}$ (i.e., sets of the
form $(a,b)$, $[a,b]$, $[a,b)$, or $(a,b]$, where $a$ might be $-\infty$
and $b$ might be $+\infty$) are connected, and every connected set is an
interval.
:::

::: {#prp-image-connected .proposition}
Let $f:X \to Y$ be a continuous map of metric spaces, with
$X$ connected. Then $f(X)$ is connected.
:::

## Compactness

::: {#def-compact .definition}
A topological space $A$ is called **compact** if,
equivalently,

1.  Every open cover $A = \bigcup_{\alpha \in I} U_\alpha$ has a finite
    subcover $A = \bigcup_{i=1}^n U_{\alpha_i}$.

2.  Every family $\mathcal F$ of closed subsets of $A$ with the finite
    intersection property (i.e., any finite subfamily has nonempty
    intersection) has nonempty intersection (i.e.,
    $\bigcap \mathcal F \neq \emptyset$).

If $A \subset X$ is a subset of a larger topological space $X$, we call
$A$ compact if it is compact in the subspace topology.
:::

::: {#exr-equivalences-compactness}
 Prove the implied equivalence in the previous
definition
:::
 
This equivalence is easier than it looks, little more than DeMorgan's
laws.

::: {#thm-compact-closed .theorem}
Let $K \subseteq X$ be compact in a metric space
$X$. Then $K$ is closed.
:::

::: {.proof}
If $x \notin K$, then $K$ has an open cover of the form
$\{X - \overline{B(x,\varepsilon)} | \varepsilon>0\}$. Any finite
subcover of that yields a ball $B(x,\varepsilon)$ disjoint from $K$.
:::

::: {#prp-closed-in-compact .proposition}
If $C \subseteq K \subseteq X$, with $C$ closed
and $K$ compact, then $C$ is compact.
:::

::: {#prp-image-compact .proposition}
Let $f:X \to Y$ be a continuous function, and
$K \subseteq X$ compact. Then $f(K)$ is compact.
:::

::: {#prp-product-compact .proposition}
The product $X \times Y$ (in the product
topology) of two compact spaces $X$ and $Y$ is compact.
:::

::: {#thm-heine-borel-1D .theorem}
**(Heine-Borel Theorem, 1D)**
Let $K \subseteq {\mathbb R}$. Then $K$ is compact if and only if it is
closed and bounded.
:::

::: {.proof}
Let $K$ be compact. Then it is closed, by 
@thm-compact-closed. Boundedness is trivial. Conversely,
it suffices to show that $[a,b]$ is compact, since $K$ is a closed
subset of some closed interval. Let
$[a,b] \subseteq \bigcup \mathcal U$, where $\mathcal U$ is a family of
open sets. We use a connectedness argument. Let
$$C = \{c \in [a,b] \,|\, [a,c]\text{ can be covered by a finite subcollection of } {\mathcal U}\}$$
If $[a,c]$ is finitely covered, then we have
$c \in B(c,\varepsilon) \subseteq U_c \in \mathcal U$, and for any
$c' \in B(c,\varepsilon)$, $[a,c']$ is finitely covered by the same
cover. So $C$ is open. On the other hand, if $[a,c]$ is not finitely
covered, then $c \in B(c,\varepsilon) \subseteq U_c \in \mathcal U$. If
any $c' \in B(c,\varepsilon)$ were such that $[a,c']$ were finitely
coverable, then $[a,c]$ could be finitely covered by adding the cover
element $U_c$. So $[a,b] - C$ is also open. Since $a \in C$,
connectedness yields $[a,b] = C$ as desired. 
:::

::: {#thm-heine-borel-nD .theorem}
**(Heine-Borel Theorem)**
Let $K \subseteq {\mathbb R}^n$. Then $K$ is compact if and only if it is
closed and bounded.
:::

::: {.proof}
If $K$ is closed and bounded, it's a subset of some interval
product $[a_1, b_1] \times
\ldots \times [a_n, b_n]$, which is compact by the previous two
statements. 
:::

**Caution:** For many students, "closed and bounded" is conceptually
easier than "compact" and the Heine-Borel theorem sounds like permission
not to grapple with the subtleties of open covers. Please note that
"compact" is a question of general topology, but "bounded" is
meaningless in nonmetric spaces. Moreover, simple metric spaces other
than ${\mathbb R}^n$ often have closed bounded noncompact sets. The
Heine-Borel property is a specialized result for a specialized space and
shouldn't underpin one's concept of compactness!

## Completeness

Consider the sequence $x_n = 1/n$ in the space ${\mathbb R}$ and also in
the space ${\mathbb R}- \{0\}$. In the former, it converges to zero, but
in the latter it is a divergent sequence. In ${\mathbb R}- \{0\}$, there
is no way to measure how close $x_n$ gets to $0$, but we can say that
the sequence terms get close to one another. The Cauchy criterion
expresses that the terms of a sequence get close to each other. Of
course it is strongly related to convergence. (In fact, Cauchy called
this condition "convergence"!)

::: {#def-cauchy .definition}
Let $x_n$ be a sequence in a metric space. We call
$x_n$ **Cauchy** if
$$\forall \varepsilon>0 \enspace \exists N \enspace \forall m>N \enspace \forall n>N \enspace d(x_m, x_n) < \varepsilon$$
:::

Note that the definition of convergence depends on the limit point,
which may not be known, whereas the Cauchy condition depends only on the
terms of the sequence.

::: {#prp-convergent-cauchy .proposition}
Every convergent sequence is Cauchy.
:::

::: {#exr-cauchy-convergent }
Prove the previous proposition.
:::

Returning to the sequence $x_n = 1/n$, we see that it converges in
${\mathbb R}$, so it is Cauchy. Despite being Cauchy, it does not
converge in ${\mathbb R}- \{0\}$, and this can be considered a "flaw"
with the metric space ${\mathbb R}- \{0\}$. Spaces without such problems
are called complete:

::: {#def-complete-metric .definition}
Let $X$ be a metric spaces. We call $X$
**complete** if every Cauchy sequence in $X$ converges.
:::

::: {#prp-R-complete .proposition}
${\mathbb R}$ is complete.
:::

::: {.proof}
Let $x_n$ be a Cauchy sequence in ${\mathbb R}$. Since $x_n$ is
Cauchy, it is bounded in some interval $[a,b]$. For each $N$, let $C_N$
be the closure of the tail sequence $\{x_N, x_{N+1}, \ldots\}$ in
${\mathbb R}$. The sequence $(C_N)$ is a decreasing sequence of nonempty
closed sets in a compact set, so there is some $L \in \bigcap C_N$. Now
for any $\varepsilon>0$ we may choose $N$ so that for all larger $n,m$
we have $|x_m-x_n| < \varepsilon/2$. But the tail sequence
$\{x_N, x_{N+1}, \ldots\}$ has within it some
$x_n\in B(L, \varepsilon/2)$. By the triangle inequality,
$\{x_N, x_{N+1}, \ldots\} \subseteq B(L, \varepsilon)$. 
:::

::: {#cor-Rn-complete .corollary}
${\mathbb R}^n$ and ${\mathbb C}$ are complete.
:::

::: {.proof}
A Cauchy sequence $(v_n)$ in ${\mathbb R}^n$ has as its
coordinates $n$ Cauchy sequences on ${\mathbb R}$. They converge
individually, producing a vector to which $(v_n)$ converges. 
:::

::: {#exr-closed-in-complete }
 Prove that a closed subset of a complete metric space
is complete.
:::

## Uniform convergence and continuity

A sequence of functions $f_n$ on a space $X$ produces, for each point
$x \in X$, a sequence $f_n(x)$. Pointwise convergence refers to the
individual convergence of such sequences:

::: {#def-converge-pointwise .definition}
Let $f_n:X \to Y$ be a sequence of functions. We
say $f_n$ **converges pointwise** to $f$ if, for each point $x \in X$,
$\lim_{n \to \infty} f_n(x) = f(x)$. That is,

$$\forall x \in X \enspace \forall \varepsilon>0 \enspace \exists N \enspace \forall n>N \enspace \rho(f(x), f_n(x))< \varepsilon$$
:::

Now if each function $f_n$ is continuous, it's natural to expect that
the limit function $f$ is also continuous, but this need not be the
case:

::: {#exm-convergent-powers .example}
Let $f_n:[0,1] \to {\mathbb R}$ by $f_n(x) = x^n$.
Then the sequence of functions converges pointwise to the
(discontinuous) function $f:[0,1] \to {\mathbb R}$ which is identically
zero except $f(1)=1$.
:::



There is a stronger form of convergence, however, which makes things
work out better:

::: {#def-converge-uniformly .definition}
Let $(f_n)$ be a sequence of functions. We say that
$(f_n)$ **converges uniformly** to $f$ if
$$\forall \varepsilon>0 \enspace \exists N \enspace \forall n>N \enspace \forall x \in X \enspace \rho(f(x), f_n(x))< \varepsilon$$
:::

The only difference between this definition and the previous is the
relative ordering of "$\forall x \in X$" and "$\exists N$". Thus the
difference between pointwise convergence and uniform convergence is that
uniform convergence allows us to choose $N$, depending on
$\varepsilon>0$, but *not* depending on $x$. Abstractly,
"$\exists N \forall x \, P(N,x)$" implies
"$\forall x \exists N \, P(N,x)$", so uniform convergence implies
convergence. The example above, restricted to the interval $[0,1/2]$
converges uniformly because $|f_n(x)| \leq 2^{-n}$. The point of this
refined notion of convergence is that the uniform limit of continuous
functions is continuous:

::: {#thm-ULimitContinuousContinuous .theorem}
Let $(f_n)$ be a sequence of continuous functions
converging uniformly to $f$. Then $f$ is continuous.
:::

::: {.proof}
In spirit, continuity boils down to the estimation
$f(x) \approx f(x_0)$. Our strategy is to estimate
$f(x) \approx f_n(x) \approx f_n(x_0) \approx f(x_0)$. Let
$\varepsilon>0$. By uniform convergence, choose $N$ so that
$$\forall n>N \enspace \forall x \in X \enspace \rho(f(x), f_n(x))< \varepsilon/3$$
Fix some $n>N$. Let $x_0$ be fixed. By the continuity assumption on
$f_n$, choose $\delta>0$ so that
$$\text{for given } x_0 \in X \enspace \forall x \in X \enspace \text{ if }d(x_0, x)< \delta \text{ then } \rho(f_n(x), f_n(x_0)) < \varepsilon/3$$
Now for given $x_0 \in X$ and for any $x \in X$ we have by the triangle
inequality for $\rho$:
$$\text{ if }d(x_0, x)< \delta \text{ then }  \rho(f(x),f(x_0)) \leq \rho(f(x),f_n(x))+\rho(f_n(x),f_n(x_0))+ \rho(f_n(x_0),f(x_0)) = \frac{\varepsilon}{3} +\frac{\varepsilon}{3}+\frac{\varepsilon}{3} = \varepsilon$$ 
as desired. 
:::



While we're interchanging quantifiers, we would like to point out a
stronger form of *continuity* in which we convert
$\forall x_0 \enspace \exists \delta$ to
$\exists \delta \enspace \forall x_0$:

::: {#def-uniformly-continuous .definition}
Let $f:X \to Y$. We say that $f$ is **uniformly
continuous** if
$$\forall \varepsilon>0 \enspace \exists \delta>0 \enspace \forall x_0 \in X \enspace \forall x\in X \enspace d(x,x_0)<\delta \to \rho(f(x),f(x_0)) < \varepsilon$$
:::

Given the terminology, the following theorem is obligatory:

::: {#thm-ULimitUContinuousUContinuous .theorem}
Let $(f_n)$ be a sequence of uniformly continuous
functions converging uniformly to $f$. Then $f$ is uniformly
continuous.
:::



::: {.proof}
In the proof of theorem @thm-ULimitContinuousContinuous, 
strike out "Let $x_0$ be fixed" and replace "given $x_0$" with "any $x_0$".
:::

::: {#thm-continuous-compact-Ucontinuous .theorem}
If $f:X \to Y$ is continuous on a **compact** domain
$X$, then $f$ is uniformly continuous.
:::

::: {.proof}
Let $\varepsilon>0$. For each $z \in X$, using continuity,
choose $B(z, \delta_z)$ so that for any $y \in B(z, 2\delta_z)$ we have
$\rho(f(y),f(z))<\varepsilon/2$. Find a finite subcover of the open
cover $\{B(z, \delta_z)\}$, and let $\delta_0$ be the minimum of all
$\delta_z$ in the subcover. Now let $x, y \in X$ be arbitrary with
$d(y,x)<\delta_0$. There is some $z$ (from the finite subcover) with
$d(y,z) \leq \delta_z$, so also
$d(x,z) \leq \delta_0 + \delta_z \leq 2 \delta_z$ so
$\rho(f(y),f(x)) \leq \rho(f(y),f(z))+ \rho(f(z),f(x)) \leq \varepsilon/2 + \varepsilon/2 = \varepsilon$ as desired. 
:::



::: {#exr-non-uniform-convergent-counterexample }
By example, prove that a sequence of uniformly
continuous functions on a compact domain can converge, *not uniformly*,
to a uniformly continuous function.
:::

Next we introduce absolute convergence:

::: {#def-absolutely-convergent .definition}
We call the series $\sum_{n=0}^\infty a_n$ of
complex numbers **absolutely convergent** if the series
$\sum_{n=0}^\infty |a_n|$ converges.
:::

Here "absolute" refers to the absolute value function, but in
${\mathbb C}$ the function $|a_n|$ is usually called modulus. Of course
absolute convergence implies convergence. It's possible to deduce this
from the M-test using constant functions $f_n(z) = a_n$, but a
straightforward proof is more informative:



::: {.proof}
For $\varepsilon>0$ choose $N$ so that for all $n>m>N$ we have
$\sum_{k=m+1}^n |a_k|< \varepsilon$. This is possible because
$\sum_{n=0}^\infty |a_n|$ converges, so its partial sum sequence is
Cauchy. Then by the triangle inequality,
$\left|\sum_{k=m+1}^n a_k\right| < \varepsilon$. This shows that the
sequence of partial sums
$\left(\sum_{k=0}^N a_k \right)_{N \in {\mathbb N}}$ is Cauchy, so
converges. 
:::

The proof of the M-test uses an infinitary triangle inequality, so we
start with that:

::: {#prp-infinitary-triangle-inequality .proposition}
Let $(z_n)$ be a sequence of complex numbers. Then
$$\left|\sum_{n=1}^\infty z_n \right| \leq \sum_{n=1}^\infty \left|z_n\right|$$
:::



::: {.proof}
$$\left|\sum_{n=1}^\infty z_n\right| = \left|\lim_N \sum_{n=1}^N z_n\right| =\lim_N \left|\sum_{n=1}^N z_n\right| \leq \lim_N \sum_{n=1}^N \left|z_n\right|  = \sum_{n=1}^\infty \left|z_n\right|$$
...because $|-|$ is continuous and
$a_n \leq b_n \to \lim a_n \leq \lim b_n$. 
:::

The next theorem is fundamental to our use of power series.

::: {#thm-WeierstrassMTest .theorem}
**(Weierstrass M-test)**
Let $u_n: X \to {\mathbb C}$ be
a sequence of functions having
$\forall x\in X \enspace |u_n(x)| \leq M_n$ for a sequence of bounds
$M_n$. If $\sum_{n=1}^\infty M_n <\infty$, then $\sum_{n=1}^\infty u_n$
converges uniformly and absolutely on $X$.
:::



::: {.proof}
First, fix $x$. Absolute convergence of
$\sum_{n=1}^\infty u_n(x)$ follows from the comparison test since
$|u_n(x)| \leq M_n$. This shows that $\sum_{n=1}^\infty u_n(x)$
converges pointwise to a function we call $f(x)$.

For uniform convergence, let $\varepsilon>0$. Choose $N$ so that
$\sum_{n=N+1}^\infty M_n < \varepsilon$ and let $n>N$. Then for any $x$
we have
$$\left|f(x) - \sum_{i=1}^n u_i(x)\right| =  \left|\sum_{i=n+1}^\infty u_i(x)\right| \leq \sum_{i=n+1}^\infty \left|u_i(x)\right| \leq \sum_{i=n+1}^\infty M_i < \varepsilon$$
as desired. 
:::



::: {#exr-Weierstrass-on-ball }
 Let $f(z) = \sum_{n=0}^\infty a_n z^n$ be a power
series whose (complex) coefficients $a_n$ are bounded above in the sense
that $|a_n| \leq B \in {\mathbb R}$ for some $B$. Prove that the sum
$\sum_{n=0}^\infty a_n z^n$ is uniformly convergent on any disk
$B(0, r)$ with $0<r<1$.
:::

# Analytic Functions

## Derivatives and Limits

We define the derivative of a complex-valued function exactly as one
would expect:

::: {#def-derivative .definition}
Let $f: {\mathbb C}\to {\mathbb C}$. The
**derivative** of $f$ is defined to be:
$$f'(z_0) = \lim_{h \to 0} \frac{f(z_0+h)-f(z_0)}{h}$$ 
Equivalently (with $z = z_0+h$):
$$f'(z_0) = \lim_{z \to z_0} \frac{f(z)-f(z_0)}{z-z_0}$$
When the derivative exists, we say that $f$ is **differentiable** at $z_0$.
:::

If we unpack this definition we have:



$$f'(z_0)=\iota L \in {\mathbb C}\enspace \forall \varepsilon>0 \enspace \exists \delta >0 \enspace \forall z \in {\mathbb C}\enspace 0<|z-z_0|<\delta \to \left|\frac{f(z)-f(z_0)}{z-z_0} -L\right|<\varepsilon$$

The key difference here is "$\forall z \in {\mathbb C}$" instead of
"$\forall z \in {\mathbb R}$" (which, given the implication, amounts to
$\forall z \in B(z_0, \delta)$ instead of
$\forall z \in (z_0-\delta, z_0+\delta)$). This is a much larger,
two-dimensional set of $z$ values which must satisfy the condition
$\left|\frac{f(z)-f(z_0)}{z-z_0}-L\right|<\varepsilon$. We will see,
thanks to this small change, that differentiability is a much stronger
condition on complex functions than it is on real functions. For
example, if $f$ is differentiable, then its derivative $f'$ is likewise
differentiable, and so on.

For now, we distinguish between three conditions later proven
equivalent:



::: {#def-differentiable .definition}
Let $U \subseteq {\mathbb C}$ be an open set. We say
that $f: U \to {\mathbb C}$ is **differentiable** if $f'(z)$ exists for
all $z \in U$. We say that $f$ is **continuously differentiable** if $f$
is differentiable and $f'$ is a continuous function. We say that $f$ is
**infinitely differentiable** if all higher derivatives $f^{(n)}(z)$
exist.
:::

*Much* later, we will prove that these conditions are all equivalent,
and replace these terms with the single term **analytic**. For now we
use the more direct language.

We begin with an easy example from which we will later generate more.

::: {#thm-derivative-linear .example}
If $f(z) = mz+b$
(where $m$, $b$ are complex constants) then $f'(z) = m$
:::

::: {.proof}
The expression $\frac{f(z)-f(z_0)}{z-z_0}$ is always $m$,
independent of both $z$ and $z_0$, so the limit exists and equals $m$.
:::

Before we can prove the various derivative rules, we need some limit
laws:



::: {#thm-limit-rules .theorem}
**(Limit Rules)**
Let $X$ be a metric space and let
$f, g : X \to {\mathbb C}$ or ${\mathbb C}^n$. (Note this includes the
case $f,g:X \to {\mathbb R}$.) The following equations are true provided
their right hand sides exist.

1.  $\lim_{x \to x_0} f(x) \pm g(x) = \lim_{x \to x_0} f(x) \pm \lim_{x \to x_0} g(x)$

2.  $\lim_{x \to x_0} f(x)g(x) = \lim_{x \to x_0} f(x) \cdot \lim_{x \to x_0} g(x)$

3.  $\displaystyle \lim_{x \to x_0} f(x)/g(x) = \frac{\lim_{x \to x_0} f(x)}{\lim_{x \to x_0} g(x)}$

4.  If $\square:{\mathbb C}^2 \to {\mathbb C}$ is a continuous binary operation then
    $\lim_{x \to x_0} f_1(x) \square f_2(x) = \lim_{x \to x_0} f_1(x) \square \lim_{x \to x_0} f_2(x)$

5.  If $\lim_{x \to x_0} g(x) = y_0$ and $f$ is continuous at $y_0$,
    then $\lim_{x \to x_0} f(g(x)) = f(y_0)$
:::

::: {.proof}
First we prove 5. Let $\varepsilon > 0$. Choose $\rho>0$ so
that $|y - y_0|<\rho \to |f(y)-f(y_0)|< \varepsilon$. Choose $\delta>0$
so that $0<|x-x_0|<\delta \to |g(x)-y_0|<\rho$. We may substitute
$y=g(x)$ and chain together the implications:
$0<|x-x_0|<\delta \to |f(g(x))-f(y_0)|< \varepsilon$ as desired.

Applying 5 with $g(x) = (f_1, f_2)$ and $f=\square$ yields 4. It remains
to prove the continuity of arithmetical operations. In each case we
assume $a \square b = c$ and $\varepsilon>0$, and give a neighborhood
$U = B(a, \delta_1) \times B(b,\delta_2) \subseteq {\mathbb C}\times {\mathbb C}$
so that $\square(U) \subseteq B(c, \varepsilon)$. For addition and
subtraction we may take $B(a, \varepsilon/2) \times B(b,\varepsilon/2)$,
by the triangle inequality. For multiplication suppose hypothetically
$\delta_1>0$ and $\delta_2>0$ are already chosen. If
$(x,y) \in B(a, \delta_1) \times B(b,\delta_2)$ then
$\modulus{xy-ab} \leq \modulus{xy-bx+bx-ab} \leq \modulus{x}\modulus{y-b} + \modulus{b}\modulus{x-a}
< \modulus{x}\delta_2 + \modulus{b}\delta_1 \leq \modulus{x-a+a}\delta_2 + \modulus{b}\delta_1
\leq \delta_1\delta_2 + \modulus{a}\delta_2 + \modulus{b}\delta_1$.
We use this computation to guide our choices of $\delta_1$ and
$\delta_2$. We may make
$\modulus{b}\delta_1 \leq {\varepsilon}/3$ by
choosing
$\delta_1 = \frac{{\varepsilon}}{3\modulus{b}}$
(or $1$ if $b=0$). We may then assure that the other two terms are each
less than or equal to ${\varepsilon}/3$ by choosing
$\delta_2 = \min(\frac{{\varepsilon}}{3\delta_1},\frac{{\varepsilon}}{3\modulus{a}})$.
(Or simply $\delta_2 = \frac{{\varepsilon}}{3\delta_1}$ if
$a=0$.)



We can deduce the division law from the multiplication law if we can
show that $r(x) = 1/x$ is a continuous function at any $x_0 \neq 0$. Let
${\varepsilon}>0$ and suppose $\delta$ somehow already
chosen, with $\modulus{x-x_0}<\delta$. Then
$$\modulus{\frac{1}{x} - \frac{1}{x_0}} = \modulus{\frac{x_0-x}{xx_0}} < \modulus{\frac{\delta}{(x-x_0 + x_0)x_0}} = {\frac{\delta}{\modulus{x-x_0 + x_0}\modulus{x_0}}} \leq {\frac{\delta}{\modulus{\modulus{x_0}-\delta}\modulus{x_0}}} =\frac{\delta}{(\modulus{x_0}-\delta)\modulus{x_0}}$$
provided $\modulus{x_0}-\delta$ is positive. If
$\delta < \frac{\modulus{x_0}}{2}$ it is, and we may
furthermore continue
$$\leq \frac{\delta}{\frac{\modulus{x_0}}{2} \modulus{x_0}} = \frac{2\delta}{|x_0|^2} \leq^? \varepsilon$$
Therefore if $\delta = \min(\frac{x_0}{2}, \frac{{\varepsilon}|x_0|^2}{2})$
we have our result. 
:::

::: {#exr-limit-compositions }
 Let $f$ be a function and let $g$ be a continuous
function. Consider the limits $\lim_{x \to x_0} f(g(x))$ and
$\lim_{y \to g(x_0)} f(y)$. Does either limit's existence imply the
other's? Explain with proof. If they both exist are they necessarily
equal? Explain with proof.
:::



::: {#exr-differentiability-conjugate-modulus }
 Assess whether each function is differentiable. Answer
with proof.

1.  $f(z) = \overline{z}$, at any point $z\in {\mathbb C}$.

2.  $f(z) = \modulus{z}^2$, at any point
    $z \in {\mathbb C}$. (Hint: Consider $z=0$ and $z \neq 0$ as
    separate cases.)

3.  $f(z) = \frac{1}{z}$.
:::

We may now begin the theory of differentiable functions in earnest.

::: {#prp-differentialbe-continuous .proposition}
If $f$ is differentiable, then $f$ is continuous.
:::

::: {.proof}
$$\lim_{w \to z} f(w)-f(z) = \lim_{w \to z} \frac{f(w)-f(z)}{w-z} \cdot (w-z) = f'(z)\lim_{w \to z}(w-z) = 0$$ 
:::

::: {#thm-linear-approximation .theorem}
**(Linear Approximation)**
Let $f$ be a complex function
defined in a neighborhood of a point $z$. Then $f$ is differentiable at
$z$ if and only if there is a linear function $L$ and an "error"
function $g$ with $f = L+g$, $g(z) = 0$, and
$\lim_{w\to z}\frac{g(w)}{w-z}  = 0$.
:::

::: {.proof}
A function $f$ is differentiable at $z$ exactly when there is a
value $m$ so that $\lim_{w \to z} \frac{f(w)-f(z)}{w-z} - m=0$
Equivalently $\lim_{w \to z} \frac{f(w) - f(z)- m(w-z)}{w-z} =0$. Notice
that $L(w) = f(z)+m(w-z)$ is linear and the numerator suffices for
$g(w)$. Conversely if $f=L+g$ as above, then
$f'(z) = L'(z)+g'(z) = m + 0 = m$, so $f'(z)$ exists. 
:::



::: {#exr-limit-ratio-linear-approx }
 Compare the following two statements about limits:
\begin{align}
    \lim_{w \to z} g(w)  =& 0 \enspace \text{ versus}\\
    \lim_{w \to z} \frac{g(w)}{w-z}  =& 0        
\end{align}
One of these statements is logically *stronger*, meaning
that it implies the other. Let us call the stronger statement "S" and
the weaker "W".

1.  Which is which?

2.  Prove $S \to W$.

3.  Illustrate $\neg (W \to S)$ by counterexample (and prove it's a
    counterexample).

4.  Let $f$ be a complex function defined in a neighborhood of a point
    $z$. Now $f$ is differentiable at $z$ if and only if there is a
    linear function $L$ and an "error" function $g$ with $f = L+g$ and
    \[S\] and $g(z) = 0$. What familiar condition on $f$ is equivalent
    to the above, if we replace $S$ with $W$? Answer without proof.
:::




::: {#thm-derivative-rules .theorem}
**(Derivative Rules)**
Let $f,g:U \to {\mathbb C}$. The
following equations are true provided the right hand sides exist:

1.  (sum/difference rule)
    $\frac{d}{dz}(f(z) \pm g(z)) = f'(z)\pm g'(z)$

2.  (constant multiple rule) $\frac{d}{dz}(kf(z)) = kf'(z)$

3.  (product rule)
    $\frac{d}{dz}(f(z) \cdot g(z)) = f'(z) g(z) + f(z) g'(z)$

4.  (quotient rule)
    $\frac{d}{dz}(f(z)/g(z)) = \frac{f'(z)g(z)-f(z)g'(z)}{(g(z))^2}$

5.  (chain rule) $\frac{d}{dz}(f(g(z))) = f'(g(z))g'(z)$
:::




::: {.proof}
The proofs are the same as for real functions
$f:{\mathbb R}\to {\mathbb R}$, but since students may not have seen
proof-based calculus, we provide them.

1.  $\frac{d}{dz}(f(z) + g(z)) =
            \lim_{w \to z} \frac{f(w) + g(w) - f(z)-g(z)}{w-z} =
            \lim_{w \to z} \frac{f(w) - f(z)}{w-z} + \lim_{w \to z} \frac{g(w) - g(z)}{w-z} = f'(z)+g'(z)$

2.  Exercise (below).

3.  
\begin{align}
    \frac{d}{dz}(f(z)g(z)) &= \lim_{w \to z} \frac{f(w)g(w)-f(z)g(z)}{w-z} \\
        &= \lim_{w \to z} \frac{f(w)g(w)-f(z)g(w)+f(z)g(w)-f(z)g(z)}{w-z}\\
        &= \left(\lim_{w \to z} \frac{f(w)-f(z)}{w-z} g(w)\right) + \left(\lim_{x \to z}f(z)\frac{g(w)-g(z)}{w-z}\right)\\
        &= f'(z)g(z) + f(z)g'(z)
\end{align}

4.  Exercise (below).

5.  The most attractive demonstration of the chain rule is sadly wrong. It goes like this: 
\begin{align}
        \frac{d}{dz}(f(g(z))) &= \lim_{w \to z} \frac{f(g(w))-f(g(z))}{w-z} \\
        &= \lim_{w \to z} \frac{f(g(w))-f(g(z))}{g(w)-g(z)} \cdot \lim_{w \to z}\frac{g(w)-g(z)}{w-z} \text{ but see below}\\
        &= f'(g(z)) \cdot g'(z)        
\end{align} 
    The problem is that the introduced denominator
    $g(w)-g(z)$ may be zero, even though $w-z$ is not. We therefore
    replace the fraction $\frac{f(g(w))-f(g(z))}{g(w)-g(z)}$ with a
    piecewise defined function designed to deal with that possibility:
\begin{align}
    \frac{d}{dz}(f(g(z))) &= \lim_{w \to z} \frac{f(g(w))-f(g(z))}{w-z} \label{eqn:Chain1}\\
    &= \lim_{w \to z} \left[\left\{\begin{array}{ll}\frac{f(g(w))-f(g(z))}{g(w)-g(z)}  & \text{ if $g(w) \neq g(z)$} \\
    f'(g(z))& \text{ if $g(w) = g(z)$} \end{array} \right\} \cdot \frac{g(w)-g(z)}{w-z}\right] \label{eqn:Chain2}\\
    &= f'(g(z)) \cdot g'(z)
\end{align}

Notice that the equality holds true when $g(w)=g(z)$, because both
sides are zero. To evaluate the limit
we used the product law and a continuity
argument: The piecewise part may be regarded as the composition of
$w \mapsto g(w)$ (continuous at $w=z$) with the function
$x \mapsto  \left\{
    \begin{array}{ll}
    \frac{f(x)-f(g(z))}{x-g(z)}  & \text{ if $x \neq g(z)$} \\
    f'(g(z)) & \text{ if $x = g(z)$} 
    \end{array}
     \right.$, 
which is continuous at $x=g(z)$ by the definition of the derivative
$f'(g(z))$.
:::




::: {#exr-q-symmetric-cts-1v }
 The chain rule makes implicit use of the important
function $q(w,z)$, which we will revisit in section 3.4.

$$q(w,z) = \left\{
    \begin{array}{ll}
        \frac{f(w)-f(z)}{w-z} & \text{ if } w \neq z \\
        f'(z) & \text{ if } w=z
    \end{array} \right\}
$$ 
However, in the chain rule prove we have the substitution $q(w,g(z)).$

Prove:

1.  The function $q$ is symmetric: $q(w,z) = q(z,w)$.

2.  If $f(z)$ is differentiable on $U \subseteq C$, then $q(w,z)$ is a
    continuous function of $w$ for each fixed $z \in U$ and vice versa.
:::

::: {#exr-derivative-constant-multiple-quotient-rules }
 Prove parts 2 and 4 of the previous theorem. For the
quotient rule, use common denominator and take inspiration from the
product rule.
:::



Our last derivative rule is for inverse functions:

::: {#thm-derivative-inverse .theorem}
Let $g(f(z))=z$ for all $z \in G$ (open), $f$
continuous at $z$. Then $$f'(z) = \frac{1}{g'(f(z))}$$ provided the
right hand side exists.
:::

::: {.proof}
The chain rule suffices if we assume $f'(z)$ exists, but we
wish to prove it exists. We need to partly mimic that proof:
$$1 = \frac{d}{dz} g(f(z)) = \lim_{w \to z} \frac{g(f(w))-g(f(z))}{w-z} = \lim_{w \to z} \frac{g(f(w))-g(f(z))}{f(w)-f(z)}\frac{f(w)-f(z)}{w-z}$$
Note: Since $g(f(z))=z$ in $G$, we know $f$ is injective on $G$ (open),
so the introduced denominator $f(w)-f(z)$ is nonzero. Now
$\lim_{w \to z} \frac{g(f(w))-g(f(z))}{f(w)-f(z)}$ is $g'(f(z))$, as in
the chain rule proof, and is presumed nonzero. We may divide both sides
by this limit and apply the quotient law for limits to conclude. 
:::

::: {#cor-derivative-inverse .corollary}
If $g:X \to Y$ ($X \subseteq {\mathbb C}$,
$Y \subseteq {\mathbb C}$) is a differentiable bijection with nonzero
derivative and continuous right inverse function $f$ (so
$g \circ f = \operatorname{id}$). Then $f$ is also differentiable, and
$f'(z) = \frac{1}{g'(f(z))}$ for all $z \in Y$.
:::

We would like to apply the previous theorem to square roots, but first
we must discuss the square root of a complex number. Notice that any
complex number $z$ can be written in the form
$r \operatorname{cis}(\theta)$, with $r\geq 0$ and
$\theta \in (-\pi, \pi]$ (or alternatively $[0, 2\pi)$). Then let
$w = \sqrt{r}\operatorname{cis}(\theta/2)$. Explicitly as a function of
$z$, we have
$w = \sqrt{\modulus{z}} \operatorname{cis}(\arg(z)/2)$,
where $\arg(z)$ is an **argument function**, or angle, of $z$. From the
properties of the function $\operatorname{cis}$ (@prp-exponent-law-cis), 
we see that $w^2 = z$ and it's
legitimate to write $w = \sqrt{z}$. Since $(\sqrt{z})^2 = z$, we appear
to be in the situation of 
@thm-derivative-inverse, but only if we can say $\sqrt{z}$ is
continuous.

Notice that $\operatorname{cis}(\theta) = \cos(\theta) + i\sin(\theta)$
is continuous by sum and multiple rules, since $\cos$ and $\sin$ are
continuous. Furthermore $r = \modulus{z}$ is a continuous
function of $z$, and $\sqrt{-}$ is continuous on $[0,\infty)$. It
follows that $f(z)=\sqrt{z}$ is continuous whenever $\arg(z)$ is
continuous.

::: {#prp-arg-continuity .proposition}
Let $\arg:{\mathbb C}- \{0\} \to (-\pi,\pi]$ with
$\arg(r\operatorname{cis}(\theta)) = \theta$ whenever
$\theta \in (-\pi, \pi]$. Then $\arg$ is continuous at $z$ when
$\arg(z)$ is in the interior of the range and discontinuous at $z$ when
$arg(z)$ is on the boundary. The statement remains true if the range
$(-\pi, \pi]$ is replaced with any other halfopen interval of length
$2\pi$.
:::

::: {.proof}
Let $\theta_0 = \arg(z)$. If $\theta_0 \in (-\pi, \pi)$, let
$\arg(z) \in B(\theta_0 , {\varepsilon}) \subseteq (-\pi,\pi)$.
Then $\arg^{-1}(B(\theta_0,{\varepsilon}))$ is the wedge
$\{r \operatorname{cis}(\theta) | \theta \in B(\theta_0 ,{\varepsilon})\}$,
which is an open set containing $z$. On the other hand if
$\arg(z) = \theta_0 = \pi$, then $z$ is negative real and every
neighborhood $B(z,\delta)$ contains points $y$ with negative argument,
so $\arg^{-1}(B(\theta_0, 1))$ is not open.

To elaborate, notice that by restriction $\arg(z):S^1 \to (-\pi, \pi]$.
This map has compact domain but noncompact image, so it *must* be
discontinuous somewhere. 
:::



Returning to the square root, we see that
$w = \sqrt{z} = \sqrt{\modulus{z}} \operatorname{cis}(\arg(z)/2)$
is discontinuous exactly when $z$ is negative real. A technical argument
shows that it is continuous at $z=0$ as well. The derivative formula
$\frac{d}{dz}\sqrt{z} = \frac{1}{2\sqrt{x}}$ is valid for all $z$ except
negative reals, where $\sqrt{z}$ is discontinuous, and zero, where $z^2$
has zero derivative. A different choice of range for $\arg(z)$ gives a
different square root function, but always one discontinuous on an open
ray from the origin.

::: {#exr-argument-sum-law }
 Recall that the kernel of the $\operatorname{cis}$ map
is known. Let $w, z \in {\mathbb C}$. By using polar coordinates for $w$
and $z$, prove that $\arg(wz) = \arg(w)+\arg(z) + 2 \pi n$ for some
$n \in {\mathbb Z}$. Here the $2 \pi n$ term records the inherent
ambiguity of angle measure. Except for this term, the law should remind
you of a logarithmic function.
:::

## Cauchy Riemann Equations and Harmonic Functions

Because a single complex number determines two real numbers, its real
and imaginary part, a function $f:{\mathbb C}\to {\mathbb C}$ can be
thought of as a function with two real inputs and two real outputs, or
even two distinct functions $u(x,y) = Re(f(x+iy))$ and
$v(x,y) = Im(f(x+iy))$, so that $f(x+iy) = u(x,y) + i v(x,y)$, where
$u:{\mathbb R}^2 \to {\mathbb R}$ and $v:{\mathbb R}^2 \to {\mathbb R}$.
This perspective is arguably more complicated, but allows us to relate
properties of complex functions to the multivariable calculus of real
functions. The first application of this line of thinking is called the
Cauchy Riemann Equations

::: {#prp-cauchy-riemann-equations .proposition}
**(Cauchy-Riemann Equations)**
Let $f(z) = f(x+iy) = u(x,y) + iv(x,y)$ be a complex function differentiable
at $z \in {\mathbb C}$ (where $u:{\mathbb R}^2 \to {\mathbb R}$ and
$v:{\mathbb R}^2 \to {\mathbb R}$). Then at $z$:

$$\frac{\partial u}{\partial x} = \frac{\partial v}{\partial y}  \enspace \text{ and } \enspace \frac{\partial u}{\partial y} = -\frac{\partial v}{\partial x}$$
:::

::: {.proof}
If the limit $f'(z) = \lim_{h \to 0} \frac{f(z+h)-f(z)}{h}$
exists, then it must agree with limits in which the variable $h$ remains
purely real or purely imaginary. So if $f'(z)$ exists, then

$$f'(z) =  \lim_{\substack{h \to 0 \\ h \in {\mathbb R}}} \frac{f(z+h)-f(z)}{h} =  \lim_{\substack{h \to 0 \\ h \in {\mathbb R}}} \frac{f(z+ih)-f(z)}{ih}$$

If $f'(x+iy) = u(x,y) + iv(x,y)$ then each limit is a combination of
partial derivatives of $u$ and $v$:

$$f'(z) = \frac{\partial u}{\partial x} + i \frac{\partial v}{\partial x} =  \frac{1}{i} \left(\frac{\partial u}{\partial y} + i \frac{\partial v}{\partial y}\right)$$

Setting the real parts equal yields the first Cauchy Riemann equation,
and setting imaginary parts equal yields the second. 
:::



If the function $f:{\mathbb C}\to {\mathbb C}$ is a *twice*
differentiable, then the Cauchy Riemann equations apply to its
derivative
$f'(z) = \frac{\partial u}{\partial x} + i \frac{\partial v}{\partial x}$.
This means

$$\frac{\partial}{\partial x} \frac{\partial u}{\partial x} = \frac{\partial}{\partial y}\frac{\partial v}{\partial x} \enspace \text{ and } \enspace \frac{\partial}{\partial y} \frac{\partial u}{\partial x} = - \frac{\partial}{\partial x}\frac{\partial v}{\partial x}$$

Applying the same to the other formula
$if'(z) = \frac{\partial u}{\partial y} + i \frac{\partial v}{\partial y}$
produces

$$\frac{\partial}{\partial x} \frac{\partial u}{\partial y} = \frac{\partial}{\partial y}\frac{\partial v}{\partial y} \enspace \text{ and } \enspace \frac{\partial}{\partial y} \frac{\partial u}{\partial y} = - \frac{\partial}{\partial x}\frac{\partial v}{\partial y}$$

Equating mixed partial derivatives and adding these equations yields:

$$\frac{\partial^2}{\partial x^2} u + \frac{\partial^2}{\partial y^2} u  = 0  \enspace \text{ and } \enspace \frac{\partial^2}{\partial x^2} v + \frac{\partial^2}{\partial y^2} v = 0$$

That is, the real and imaginary parts of a twice differentiable complex
function are harmonic, in the following sense.

::: {#def-laplace-operator .definition}
The second order differential operator above is
called the **Laplace operator**, typically written
$$\nabla^2 =\frac{\partial^2}{\partial x^2} + \frac{\partial^2}{\partial y^2}$$
A function $u$ for which $\nabla^2 u =0$ is called a 
**harmonic function**.
:::

The operator $\nabla^2$ calculates an overall concavity in two
dimensions. Harmonic functions lack local minima and maxima and have an
overall curvature which is balanced at every point between positive and
negative. A harmonic function is a solution to the constant-time version
of the heat equation. That is, a harmonic function can describe the
temperature function of a body whose temperature is not changing with
time.

## Power Series

Using @thm-derivative-linear and the combinations of @thm-derivative-rules 
we can quickly prove that all polynomials are differentiable, 
and that their derivatives are
calculated exactly as one would expect:

::: {#prp-derivative-polynomial .proposition}
The derivative of $\displaystyle \sum_{n=0}^N a_nz^n$
is $\displaystyle \sum_{n=0}^N a_n n z^{n-1}$
:::

We would like to extend this example to include infinite sums, but first
we must consider matters of convergence.

::: {#def-power-series .definition}
A **power series** is a function of $z$ of the form
$$f(z) = \sum_{n=0}^\infty a_nz^n \text{, or more generally } f(z) = \sum_{n=0}^\infty a_n(z-a)^n$$
When $\sum_{n=0}^\infty a_nz^n$ converges we say $f$ converges at $z$.
The set of $z$ at which $f$ converges is called the domain of
convergence.
:::

The generalization to sums of the form $\sum a_n (z-a)^n$ is unnecesary
in the case of polynomials because powers $(z-a)^n$ may be simply
expanded. In the case of series, the generalization is valuable because 
such expansion introduces convergence
problems. For example, what is the constant term of
$\sum_{n=0}^\infty 1(z+1)^n$ after expansion?

::: {#exm-geometric-series .example}
The function $f(z) = \sum_{n=0}^\infty z^n$ is a
**geometric series**. It converges uniformly on any region $B(0,r)$ with
$0<r<1$, but if $|z| \geq 1$ it diverges. (More generally,
$\sum_{n=0}^\infty (z-a)^n$ converges uniformly on $B(a,r)$ and diverges
when $|z-a|\geq1$.)
:::

::: {.proof}
Let $0<r<1$. On $B(0,r)$ we have $|z| <r$ so $|z^n| < r^n$. The
values $r^n$ satisfy the requirements of the Weierstrass M-test 
@thm-WeierstrassMTest because
$\sum_{n=0}^\infty r^n = \frac{1}{1-r}$, so $\sum_{n=0}^\infty z^n$ is
uniformly convergent on $B(0,r)$. If on the other hand $|z|\geq1$, then
the terms of $\sum_{n=0}^\infty z^n$ do not even approach zero, so the
series diverges. 
:::

We sometimes prove convergence or divergence of series by comparison to
a geometric series. This technique is at the heart of the root test:

::: {#thm-root-test .theorem}
**(Cauchy's Root Test)**
Let $\sum_{n=0}^\infty a_n$ be a
series, and let $C=\limsup |a_n|^{1/n}$.

1.  If $C<1$ then the series absolutely converges.
2.  If $C>1$ then the series diverges.
:::

::: {.proof}
In the first case, we have $\limsup |a_n|^{1/n}<1$, so we may
choose $s$ with $\limsup |a_n|^{1/n}<s<1$. For all but finitely many $n$
we have $|a_n|^{1/n}<s$, so $|a_n|<s^n$. Thus
$\sum_{n=0}^\infty |a_n| < \sum_{n=0}^\infty s^n + [\text{something finite}]$
and $\sum a_n$ is absolutely convergent.

In the second case, we have $1<\limsup |a_n|^{1/n}$. This time we choose
$s$ with $1<s<\limsup |a_n|^{1/n}$, and as before $|a_n|>s^n$ for
infinitely many $n$. Then the terms $a_n$ do not even approach zero, so
$\sum_{n=0}^\infty a_n$ diverges. 
:::

::: {#thm-Cauchy-Hadamard-radius .theorem}
**(Cauchy-Hadamard test)**
Let $f(z) = \displaystyle \sum_{n=0}^\infty a_n(z-a)^n$ be a power series.
Let $$R = 1/\limsup |a_n|^{1/n} \hspace{3em}
\text{(with $R=\infty$ if the $\limsup$ is $0$.)}$$ Then $f(x)$
converges uniformly and absolutely on any region $B(a,r)$ with $0<r<R$,
but if $|z-a| > R$ it diverges.
:::



::: {.proof}
As in the proof of the root test, we may choose $s$ so that
$1/R = \limsup |a_n|^{1/n} < s < 1/r$, and for all but finitely many $n$
we have $|a_n|^{1/n} < s$ and $|a_n| < s^n$. For these $n$, and for all
$z \in B(a,r)$, $|a_n(z-a)^n| < s^nr^n = (sr)^n$, so the $M$-test gives
uniform and absolute convergence.

If on the other hand $|z-a|>R$, then
$C=\limsup |a_n(z-a)^n|^{1/n} = |z-a|\limsup |a_n|^{1/n} = |z-a|/R>1$,
so the root test guarantees divergence. 
:::

Although the Hadamard test is powerful, the ratio test is often easier
to use. Before we prove it we need a technical lemma:

::: {#lem-ratio-to-root .lemma}
Let $a _n$ be a sequence of positive real numbers. If
$\lim_{n \to \infty} \frac{a_{n+1}}{a_n} = L$ then
$\lim_{n \to \infty} a_n^{1/n} = L$.
:::

::: {.proof}
Let $b_n = \ln_{\mathbb R}(a_n)$, where $\ln_{\mathbb R}$ is
the ordinary real natural logarithm function. We must prove that if
$\lim_{n \to \infty} b_{n+1} - b_n = K$ then
$\lim_{n \to \infty} \frac{b_n}{n} = K$. (These are equivalent since
$e^x$ and $\ln_{\mathbb R}$ are continuous.)

First, assume $K=0$, and let ${\varepsilon}>0$. Choose $N$
beyond which $b_{n+1} - b_n< {\varepsilon}/2$, and let $n>N$.
We compute:
$\frac{b_n}{n} = \frac{b_n-b_N}{n}+\frac{b_N}{n} \leq \frac{(n-N){\varepsilon}/2}{n}+ \frac{b_N}{n}
    \leq {\varepsilon}/2+ \frac{b_N}{n}$. Thus if
$n>\max(N, 2b_N/{\varepsilon})$ we have
$\frac{b_n}{n} < {\varepsilon}$ as desired.

If $K \neq 0$, we apply the previous case to the modified sequence
$b_n-nK$. 
:::

::: {#thm-ratio-test .theorem}
**(Ratio Test)**
Let $f(z) = \sum_{n=0}^\infty a_n(z-a)^n$ be a power series. If
$\lim_{n \to \infty} \left|\frac{a_{n}}{a_{n+1}}\right|$ exists then it
equals the radius of convergence of $f$.
:::

::: {.proof}
Apply @lem-ratio-to-root to the sequence $|a_n|$
and then use @thm-Cauchy-Hadamard-radius.
:::

::: {#exr-power-series-radii-convergence }
 Give examples, with proof, of a power series ...

1.  ...with infinite radius of convergence.

2.  ...with radius of convergence equal to $11$.

3.  ...with zero radius of convergence.
:::



::: {#thm-sum-product-series .theorem}
Let $A = \sum_{n=0}^\infty a_n$ and
$B = \sum_{n=0}^\infty b_n$ be convergent series in ${\mathbb C}$.

1. $\sum_{n=0}^\infty ka_n = kA$.

2.  $\sum_{n=0}^\infty a_n +b_n = A+B$.

3.  $\sum_{n=0}^\infty c_n = AB$ where $c_n = \sum_{k=0}^na_kb_{n-k}$,
    provided at least one series converges absolutely.
:::

::: {.proof}
The first two are straightforward, but the third is delicate.
Let $A_N = \sum_{n=0}^N a_n$ and $B_N = \sum_{n=0}^N b_n$.

1.  An easy exercise.

2.  $\sum_{n=0}^\infty (a_n +b_n) = \lim_N \sum_{n=0}^N (a_n +b_n) = 
        \lim_N \left(A_N +B_N \right) = 
        \lim_N A_N +\lim_N B_N =A+B \text{ as desired.}$

3.  [Link to Figure](https://www.geogebra.org/geometry/pqezymss)

    Let $N \in {\mathbb N}$, to be specifically chosen later.

\begin{align}
    \left | AB - \sum_{n < N} c_n \right | 
    &= \left | \sum_{i < N} a_i B + \sum_{i \geq N} a_i B - \sum_{i+j < N} a_i b_j \right | \\
    &= \left | \sum_{i < N} a_i \left (B - \sum_{j < N-i} b_j \right ) + \sum_{i \geq N} a_i B  \right | \\
    &= \left | \sum_{i < N}  \left ( a_i \sum_{j \geq N-i} b_j  \right ) + \sum_{i \geq N} a_i B  \right | \\
    & \leq  \sum_{i \leq N}   |a_i| \left | \sum_{j \geq N-i} b_j  \right | + \sum_{i \geq N} |a_i| |B|
\end{align}

    In the right term, $|B|$ is a fixed value and the tail
    $\sum_{i \geq N} |a_i|$ is small for large $N$ by absolute
    convergence. In the left term, we can control $|a_i|$ if $i$ is
    large and $|\sum_{j \geq N-i} b_j |$ if $i$ is small (so that $j$ is
    large). Therefore we split the sum in half. Let $0 \leq M < N$. Here
    $M$ will also be specifically chosen later. We continue\...

    $$=  \overbrace{\sum_{0 \leq i < M}   |a_i| \left | \sum_{j \geq N-i} b_j  \right |}^{\alpha} + \overbrace{\sum_{M \leq i < N}   |a_i| \left | \sum_{j \geq N-i} b_j  \right |}^{\beta} + \overbrace{\sum_{i \geq N} |a_i| |B|  \\}^{\gamma}$$

    Without further delay let $\varepsilon > 0$.

    We control term $\beta$ first. The sequence
    $\left |\sum_{j \geq N-i} b_j\right|$ (as a function of $N$) converges
    to $0$, so it has an upper bound $U_B$ , independent of $N$ and $M$.
    As a function of $N$, the convergent sequence
    $\sum_{i \geq N} |a_i|$ is Cauchy, so its differences
    $\sum_{M \leq i < N} |a_i|$ can be made small by choosing $M$
    sufficiently large. Choose $M$ so that (for all $N>M$) we have
    $\sum_{M \leq i < N} |a_i| < \frac{\varepsilon}{3U_B}$. For this $M$
    and for any $N>M$ we have $\beta < \frac{\varepsilon}{3}$

    Next we control term $\alpha$. Having chosen $M$ we may treat
    $\sum_{0 \leq i < M}  |a_i|$ as a constant $V_A$. Again because the
    sequence $\left |\sum_{j \geq N-i} b_j\right|$ converges to $0$, we may
    choose $K$ so that if $N-i>K$ then
    $\left | \sum_{j \geq N-i} b_j\right|<\frac{\varepsilon}{3V_A}$. Now
    for any $N>K+M$, we have $N-i>K$ and so
    $\alpha < \frac{\varepsilon}{3}$.

    Finally we control term $\gamma$, in which $|B|$ is a fixed
    constant. We assume $|B| \neq 0$, the contrary case being trivial.
    Since the series $\sum a_i$ is absolutely convergent there is some
    $G$ so that if $N>G$ then
    $\sum_{i \geq N} |a_i| < \frac{\varepsilon}{3|B|}$, and
    $\gamma < \frac{\varepsilon}{3}$.

    If $N > \max(K+M, G)$ then
    $\left | AB - \sum_{n < N} c_n \right | < \varepsilon$ as required.
:::




::: {#thm-sum-product-power-series .theorem}
Let $f(z) = \sum_{n=0}^\infty a_n(z-a)^n$ and
$g(z)= \sum_{n=0}^\infty b_n(z-a)^n$ be power series with radius of
convergence at least $R$. Then (the series below converge on $B(a,R)$
and)

1.  $\sum_{n=0}^\infty (ka_n)(z-a)^n = kf(z)$.

2.  $\sum_{n=0}^\infty (a_n+b_n)(z-a)^n = f(z)+g(z)$.

3.  $\sum_{n=0}^\infty c_n(z-a)^n = f(z)g(z)$ where
    $c_n = \sum_{k=0}^n(a_kb_{n-k})$.
:::

::: {.proof}
All three parts follow from @thm-sum-product-series.
:::

::: {#exr-product-series-counterexample }
 (Hard) Find series $A = \sum_{n=0}^\infty a_n$ and
$B=\sum_{n=0}^\infty b_n$, both convergent but neither absolutely
convergent, for which $\sum_{n=0}^\infty c_n$ does not converge to $AB$.
(Hints: Choose $\sum a_n$ and $\sum b_n$ real and alternating but
decreasing in absolute value. This will guarantee their convergence but
leave many options to violate absolute convergence (a condition you must
avoid in light of @thm-sum-product-series. Argue that
$c_n = \sum_{k=0}^na_kb_{n-k}$ is a sum with positive terms. Bound them
below, deduce a lower bound for $c_n$, and force $\sum c_n$ to diverge.)
:::

::: {#exr-power-series-multiplication-practice }
 Calculate a power series for $\frac{1}{(1-z)^2}$ by
the series multiplication rule, and find its radius of convergence.
:::

::: {#def-formal-derivative .definition}
Let $f(z) = \sum_{n=0}^\infty a_n(z-a)^n$ be a
power series. The **formal derivative** is the power series
$$\sum_{n=0}^\infty a_n n (z-a)^{n-1}$$
:::

We wish to show that the formal derivative equals the derivative, but
first we need to check its convergence:

::: {#thm-formal-derivative-radius-convergence .theorem}
Let $\sum_n a_n(z-a)^n$ be a power series. Then the
formal derivative $\sum_n na_n(z-a)^{n-1}$ has the same radius of
convergence.
:::



::: {.proof}
First notice that $\sum_n na_n(z-a)^{n-1}$ converges iff
$\sum_n na_n(z-z_0)^{n}$ converges, because $z-z_0$ is a constant
multiple in the sum on $n$. It's more convenient to use the Hadamard
test on the latter:

$$\limsup \sqrt[n]{|na_n|} = \limsup \sqrt[n]{n}\sqrt[n]{|a_n|}  = \lim_n \sqrt[n]{n} \limsup \sqrt[n]{|a_n|} = \limsup \sqrt[n]{|a_n|}$$

This is a valid limit law when the limit is defined. The limit
$\lim_n \sqrt[n]{n}$ can be evaluated by @lem-ratio-to-root.
:::

::: {#cor-formal-antiderivaitve-radius-convergence .corollary}
As above, the formal antiderivative has the same
radius of convergence.
:::

::: {.proof}
The formal antiderivative of $f$ has some radius of
convergence, which matches that of *its* formal derivative by @thm-formal-derivative-radius-convergence, which of course is
$f$.
:::

::: {#thm-formal-derivative-is-derivative .theorem}
The formally derived series converges to the
derivative inside the radius of convergence $B(a,R)$.
:::



::: {.proof}
For simplicity we assume $a=0$. Let
$f(z) = \displaystyle\sum_{n=0}^\infty a_nz^n$. We write $f_1$ for the
formally derived series and $f'$ for the derivative.

To show $f_1(z)=f'(z)$ need to show that the difference
$\frac{f(w)-f(z)}{w-z}  - f_1(z)$ approaches $0$ as $w \to z$. Assume
$w,z \in B(0,s)$ where $s < R$. Let $f(z) = s_n(z) + R_n(z)$, where
$s_n(z) = \displaystyle\sum_{k=0}^{n-1} a_nz^n$. Note
$f'(z) = \frac{d}{dz} \lim_n s_n(z)$ whereas
$f_1 = \lim_n \frac{d}{dz} s_n(z)$, so our obligation here is a case of
interchanging limits.

\begin{align}
\frac{f(w)-f(z)}{w-z}  - f_1(z) &= \frac{s_n(w)+R_n(w)-s_n(z)-R_n(z)}{w-z}  - f_1(w)\\
&= \frac{s_n(w)-s_n(z)}{w-z} - f_1(z) + \frac{R_n(w)-R_n(z)}{w-z} \\
&= \left(\frac{s_n(w)-s_n(z)}{w-z} - s'_n(z)\right) + (s'_n(z) -f_1(z)) + \frac{R_n(w)-R_n(z)}{w-z}
\end{align}

Let $\varepsilon>0$ and fix $z \in B(a,s)$. We will bound each of the
three terms by $\varepsilon/3$. We need only find one $n$ for which this
is possible, since the left side of the equation is independent of $n$.
The last term is hardest:

\begin{align}
\left|\frac{R_n(w)-R_n(z)}{w-z}\right| &= \left|\frac{\sum_{k=n}^\infty a_k (w^k-z^k)}{w-z}\right| \\
&= \left|\sum_{k=n}^\infty a_k (w^{k-1} + zw^{k-2} + \ldots + z^{k-1})\right| \\ 
&= \sum_{k=n}^\infty \left| a_k (w^{k-1} + zw^{k-2} + \ldots + z^{k-1})\right| \\ 
&\leq  \sum_{k=n}^\infty |a_k| k s^k
\end{align}

The last expression is the tail of a series (the formal derivative power
series at $z=s$, times $s$) known convergent by @thm-formal-derivative-radius-convergence. Thus for $n$
sufficiently large the third term can be made less than $\varepsilon/3$,
for *all* $w \in B(a,s)$.

As for the second term $(s'_n(z) -f_1(z))$, $f_1(z)$ is by definition
$\lim_{n \to \infty} s'_n(z)$, so for $n$ large enough it can be made
less than $\varepsilon/3$, independent of $w$.

Now fix $n$ for which the last two terms are small as described. The
first term $\frac{s_n(w)-s_n(z)}{w-z} - s'_n(z)$ is the difference
between a function and its limit as $w$ approaches $z$, so for $w$ in
some neighborhood $B(z,\delta)$ it can be bounded (in absolute value) by
$\varepsilon/3$.

We've shown that for $\varepsilon>0$, we can find some $n$ and
$\delta>0$ so that if $0 <|w-z|<\delta$ then
$\left|\frac{f(w)-f(z)}{w-z}  - f_1(z) \right|<\varepsilon$. We
disregard $n$ since the expression doesn't depend on $n$, and conclude
that $\lim_{w \to z} \frac{f(w)-f(z)}{w-z} = f_1(z)$ as desired. 
:::



::: {#cor-formal-antiderivative-is-antiderivative .corollary}
Let
$f(z) = \displaystyle\sum_{n=0}^\infty a_n(z-a)^n$ be a power series
with radius of convergence $R$. Then the formal antiderivative is an
antiderivative on $B(a,R)$.
:::

::: {.proof}
Compare the derivative and the formal derivative of the formal
antiderivative of $f$. 
:::

::: {#exr-derivative-series-counterexample }
@thm-formal-derivative-is-derivative
proves that
$\lim_{n \to \infty} \frac{d}{dz} s_n(z)$ equals
$\frac{d}{dz} \lim_{n \to \infty} s_n(z)$ for certain functions $s_n$.
In this exercise you show that the equality is not a generic law. Find
functions $s_n: {\mathbb R}\to {\mathbb R}$ or
$s_n: (a,b) \to {\mathbb R}$ and $z$ in their domain for which the
limits:
$$\lim_{n \to \infty} \frac{d}{dz} s_n(z) \text{ and } \frac{d}{dz} \lim_{n \to \infty} s_n(z)$$
exist and are unequal.
:::

::: {#exr-power-series-via-differentiation }
Calculate a power series for $\frac{1}{(1-z)^2}$ by
the series differentiation rule, and find its radius of convergence.
Compare to the previous problem.
:::

Power series give us a versatile example of analytic functions. We will
show (much) later that, conversely, all analytic functions are locally
equal to power series.

At this point our general theory of analytic functions is quite strong,
but our variety of examples is not. Next we use power series to
introduce complex versions of three important real-valued functions.

::: {#def-exp-cos-sin .definition}
We define: 
\begin{align}
        e^z \equiv & \sum_{n=0}^\infty \frac{z^n}{n!} = 1 + z + \frac{z^2}{2} + \frac{z^3}{6} + \frac{z^4}{24} + \ldots \\
        \cos(z) \equiv & \sum_{\substack{n=0 \\ n \text{ even}}}^\infty \frac{(-1)^{\frac{n}{2}}z^n}{n!} = 1 - \frac{z^2}{2} + \frac{z^4}{24} - \frac{z^6}{720} + \ldots \\
        \sin(z) \equiv & \sum_{\substack{n=1 \\ n \text{ odd}}}^\infty \frac{(-1)^{\lfloor\frac{n}{2}\rfloor}z^n}{n!} = x - \frac{z^3}{6} + \frac{z^5}{120} - \frac{z^7}{5040} + \ldots 
\end{align}
:::



::: {#prp-exp-cos-sin-convergence .proposition}
Each function $e^z$, $\cos(z)$, and $\sin(z)$ has
infinite radius of convergence.
:::

::: {.proof}
For $e^x$, the ratio test @thm-ratio-test
gives $\lim_n \modulus{\frac{a_n}{a_{n+1}}} = \lim_n (n+1) = \infty$.
The ratio test doesn't apply for $\cos$ and $\sin$ because their zero
terms, but its use for $e^x$ allows us to conclude that
$\limsup \modulus{\frac{1}{n!}}^{1/n} = 0$, and the
$\limsup$'s for $\cos$ and $\sin$ must agree with this result, so by
Cauchy-Hadamard they also have infinite radius of convergence. 
:::

::: {#thm-properties-exp-cos-sin .theorem}
**(Properties of $e^z$, $\cos(z)$, and $\sin(z)$)**
The functions $e^z$, $\cos(z)$, and $\sin(z)$ have the following
properties:

1.  Exponent laws: For any $w, z \in {\mathbb C}$:
    a.  $e^0=1$
    b.  $e^{w+z} = e^we^z$ 
    c.  $e^{w-z} = e^w/e^z$
    d.  $e^{nz} = (e^z)^n$ for all $n \in {\mathbb N}$. 
2.  Interrelationships:
    a.  Euler's Formula: $e^{iz} = \cos(z) + i\sin(z)$ for all
        $z \in {\mathbb C}$. 
    b.  $e^{a+ib} = e^a\operatorname{cis}(b) = e^a(\cos(b)+i\sin(b))$
        for all $a, b \in {\mathbb R}$ 
    c.  $\cos(z) = \frac{1}{2}(e^{iz} + e^{-iz})$ 
    d.  $\sin(z) = \frac{1}{2i}(e^{iz} - e^{-iz})$ 
3.  Symmetries: For all $z \in {\mathbb C}$:
    a.  $e^z = e^{z+2\pi i}$ 
    b.  $\cos(z) = \cos(z+2\pi)$ 
    c.  $\sin(z) = \sin(z+2\pi)$ 
    d.  $\cos(-z)=\cos(z)$ 
    e.  $\sin(-z)=-\sin(z)$ 
4.  Derivatives:
    a.  $\frac{d}{dz} e^z = e^z$
    b.  $\frac{d}{dz} \cos(z) = -\sin(z)$
    c.  $\frac{d}{dz} \sin(z) = \cos(z)$
:::



::: {.proof}
The derivative formulas are straightforward consequences of
@thm-formal-derivative-is-derivative, and the value of each
function at $0$ is trivial. 

The alert reader may worry that we are
equivocating by using the symbols $\sin(x)$, $\cos(x)$ and $e^x$ with
two different meanings, especially in 2b.,
where $\operatorname{cis}(t)$ is defined in terms of prior knowledge
$\sin$ and $\cos$. Writing the "new" functions in bold, we calculate the
derivatives of the functions:
$$\frac{\bm{e^t}}{e^t} \,\, \text{ and } \,\, \frac{\bm{\cos(t)} + i \bm{\sin(t)}}{\cos(t) + i \sin(t)}$$
Derivative laws give zero in each case, so each ratio is constant.
Evaluating at $t=0$ shows the constant is $1$, so the functions agree.
This shows that the newly defined complex exponential and trigonometric
functions, restricted to ${\mathbb R}$, agree with their original
versions.

Parts 1b.  and 2a. 
are the most significant, and most of the
other properties follow from these.

First we prove 1b:
$$e^{a+b} = \sum_{n=0}^\infty \frac{(a+b)^n}{n!} =\sum_{n=0}^\infty \sum_{k=0}^n \frac{a^kb^{n-k}}{k!(n-k)!} = \left(\sum_{n=0}^\infty \frac{a^n}{n!}\right)\left(\sum_{n=0}^\infty \frac{b^n}{n!}\right) = e^ae^b$$
Note the use of the binomial formula and @thm-sum-product-power-series.

To prove 2a., simply insert $iz$ into the series for $e^z$
and substitute $i^2 = -1$, $i^3 = -i$, $i^4 = 1$, etc. The even terms
make $\cos(z)$, and the odd terms make $i\sin(z)$. Notice that this
requires Theorem
@thm-sum-product-power-series for the validity of
term-by-term addition of series.

The equation $e^0=1$ is obvious, and the other exponent laws follow
easily from 1b. Equation
2b.,
sometimes used as a definition of $e^{a+ib}$, follows from
1a. and 2a.

The symmetries 3d. and 3e. follow by direct substitution into the series.
Combined with Euler's formula
2a. for $e^{iz}$ and $e^{-iz}$ we obtain
3b. and
3c. Next
3a. follows from
2b.
and the periodicities of the *real* functions $\cos$ and $\sin$. (I
would prefer to give a self-contained argument, not dependent on prior
knowledge of $\cos$ and $\sin$, but this would require a rigorous
definition of $\pi$ and would take us far afield! See Spivak's Calculus
for this argument.) Using 3a, we deduce 3b from 2c and 3c from 2d. 
Note that we have assumed the periodicity of the ordinary real 
$\cos$ and $\sin$ to prove the periodicity of these functions' 
complex extensions.
:::



::: {#exr-angle-sum }
Prove the angle sum formulas for arbitrary complex
$a$ and $b$ 
$$\cos(a+b)  = \cos(a)\cos(b)-\sin(a)\sin(b)$$
$$\sin(a+b)  = \sin(a)\cos(b)+\cos(a)\sin(b)$$
Note: This is a simple
consequence of Euler's identity. Can you prove it directly from the
power series definitions?
:::



We're ready now to face the challenge of the logarithm. Of course the
job of $\log(z)$ is to invert the function $e^z$, but since 
$e^z = e^{z+2\pi i}$, the function $e^z$ is far from injective.
We must restrict its domain. In particular, the domain must not include
$z$ and $z+2\pi i$ for any $z$. This suggests the restriction
$D = \{a+bi | b \in (-\pi,\pi]\}$. Soon we'll show that $e^z$ is injective
on $D$.

Let us set $w = e^z$, where $z=a+bi \in D$ and try to solve for $z$:
\begin{align}
    w &= e^z \\
    w &= e^a\operatorname{cis}(b) \\
    \modulus{w} &= \modulus{e^a} \cdot 1 \\ 
    \ln_{\mathbb R}(\modulus{w}) &= a
\end{align}
where of course
$\ln_{\mathbb R}$ is the real natural logarithm function. Returning to
$w = e^a\operatorname{cis}(b)$ and taking arguments, we have
$\arg(w) = \arg{\operatorname{cis}(b)} = b$ (since $e^a$ is a positive
real, and since $b \in (-\pi,\pi]$). Thus
$z = a+bi = \ln_{\mathbb R}(\modulus{w})  +i \arg(w)$. This
leads us to the following definition and proposition:



::: {#def-logarithm .definition}
Let $z \in {\mathbb C}$. We define the
**complex logarithm** $\log:{\mathbb C}\to \{a+bi | b \in (-\pi,\pi]\}$ of $z$
by the formula:

$$\log(z) \equiv \ln_{\mathbb R}(\modulus{z})  +i \arg(z)$$
where $\arg$ is an argument function.
:::

Notice that the ambiguity of $\arg$ is built into $\log$. We can redefine
$\log$ using any argument function (for example taking values in $[0,2\pi)$), making appropriate changes below.

::: {#prp-log-continuous-derivative .proposition}
The function $\log(z)$ is undefined at $0$ and
discontinuous exactly where $\arg(z)$ is (i.e., the negative reals).
Where continuous, the function has derivative $\log'(z) = 1/z$. For all $z$ we
have $e^{\log(z)} = z$, and whenever $Im(z) \in (-\pi,\pi]$ we have
$\log(e^z) = z$.
::: 

::: {.proof} 
At $z=0$, $\ln_{\mathbb R}(\modulus{z})$ is
undefined. Everywhere else, $\ln_{\mathbb R}(\modulus{z})$
is continuous, so all discontinuities come from the term $i\arg(z)$. For
any $z$,
$e^{\log(z)} = e^{\ln_{\mathbb R}(\modulus{z})  +i \arg(z)} = e^{\ln_{\mathbb R}(\modulus{z})} \operatorname{cis}(\arg(z))  = \modulus{z} \operatorname{cis}(\arg(z)) = z$.
For $b \in (-\pi,\pi]$, we have
$\log(e^{a+bi}) = \log(e^a \operatorname{cis}(b)) = \ln_{\mathbb R}(\modulus{e^a})  +i \arg(\operatorname{cis}(b)) = a + ib$
as desired. 
:::



It's useful to look closely at the discontinuities of $\log$. As $z$
crosses the negative real line, its argument $\arg(z)$ jumps from nearly
$-\pi$ to $\pi$, and the imaginary part of $\log(z)$ does the same. By
choosing a different argument function, say $\arg_2$ with range
$[0,2\pi]$, we obtain a modified logarithm $\log_2(z)$, now
discontinuous along the positive reals. On the upper half plane
($Im(z) > 0$) we have $\arg_2(z) = \arg(z)$, so $\log_2(z) = \log(z)$.
But on the lower half plane ($Im(z) < 0$) $\arg_2(z) = \arg(z) + 2\pi$,
so $\log_2(z) = \log(z) + 2 \pi i$. The problem of the discontinuities
of the logarithm is not to be blamed on the negative real axis, but is
more essential: For any logarithm function, as $z$ moves
counterclockwise around the origin, $Im(\log(z))$ increases continuously
with $\theta$ until, after one full rotation, $\log(z)$ has "gained"
$2\pi i$ and must snap back to its starting value.

Notice that the function $1/z$ is analytic on ${\mathbb C}- \{0\}$, and
$\log(z)$ is nearly but not quite an antiderivative on this region,
because $\log(z)$ is discontinuous on $(-\infty,0)$. This is the best we
can do: Later we'll prove $1/z$ has no antiderivative on its entire
domain.

::: {#exr-logarithmic-derivative }
Let $f(x)$ be a differentiable function. For which
$x$ is it true that $\frac{d}{dx} \log(f(x)) = \frac{f'(x)}{f(x)}$?
Answer with proof.
:::



::: {#exr-log-rules }
The rules of logarithms are usually stated for
positive real numbers: For $a, b \in (0, \infty)$:

1.  $\ln_{\mathbb R}(1)=0$

2.  $\ln_{\mathbb R}(ab)=\ln_{\mathbb R}(a)+\ln_{\mathbb R}(b)$

3.  $\ln_{\mathbb R}(a/b)=\ln_{\mathbb R}(a)-\ln_{\mathbb R}(b)$

4.  $\ln_{\mathbb R}(a^n)=n\ln_{\mathbb R}(a)$

Everything hinges on the product law
$\ln_{\mathbb R}(ab) = \ln_{\mathbb R}(a)+\ln_{\mathbb R}(b)$.

1.  Give a complex counterexample (using the function $\log$) to the
    product law for logarithms (Hint: It's the fault of the range of the
    argument function!)

2.  As functions of $z$ for fixed $b$, prove that $\log(zb)$ and
    $\log(z)+\log(b)$ agree at $z=1$.

3.  As functions of $z$ for fixed $b$, compare the derivatives of
    $\log(zb)$ and $\log(z)+\log(b)$. On what set does each function
    have undefined derivative?

4.  Assuming $\Re(b)>0$, prove that $\log(zb)$ and $\log(z)+\log(b)$
    agree for all $z$ with $\Re(z)>0$.
:::

::: {#exr-estimate-e }
Use the definition of $e^z$ to estimate the value of
$e$.
:::

::: {#exr-general-exponentials }
The general exponential function $a^z$ is often
defined by the formula $$a^z \equiv_{def}  e^{z \log(a)}$$ (To remember
the formula, just apply rules of logarithms to $a^z = e^{\log(a^z)}$.)
Now let $a$ be an arbitrary complex number. Prove that the exponential
function $a^z$ satisfies the sum law for exponential functions
$a^{w+z} = a^wa^z$. Calculate $(1+i)^i$.
:::

## Derivatives and Difference quotients

We now pause to analyze the difference quotient function. For this
section, we let $f:X \to {\mathbb C}$ be a function defined and
differentiable on $X \subseteq {\mathbb C}$ (or indeed
$f:X \to {\mathbb R}$ with $X \subseteq {\mathbb R}$). We define
$q(w,z)$ by the formula:

$$q(w,z) = \left\{\begin{array}{ll} \frac{f(w)-f(z)}{w-z}  & \text{ if $w \neq z$} \\ f'(z)& \text{ if $w= z$} \end{array} \right\}$$

Notice that $q(w,z)$ is the difference quotient function, completed
along the diagonal with its natural limit. Thus, $q(w,z)$ (above) is a
continuous function of $w$ for each fixed $z \in X$ and vice versa.
However, this does not automatically mean that
$q:X \times X \to {\mathbb C}$ is continuous. Furthermore note that $q$
is symmetric in the sense that $q(w,z) = q(z,w)$.

::: {#thm-small-derivative-small-q .theorem}
Let $X$ be an open convex subset of ${\mathbb C}$ or
${\mathbb R}$, and let $f:X \to {\mathbb C}$ be differentiable with
$\modulus{f'}<\varepsilon$. Then
$\forall w \neq z \in X \enspace 
    \modulus{ \frac{f(w)-f(z)}{w-z}}<\varepsilon$.
:::

::: {.proof}
We prove a sort of transitivity along straight lines: Assume
$\modulus{q(w,m)}< {\varepsilon}$,
$\modulus{q(m,z)}< {\varepsilon}$, and $m$ is
between $w$ and $z$ on a straight line segment in ${\mathbb C}$. Then
$$\modulus{q(w,z)} = \left|\frac{f(w)-f(z)}{w-z}\right| \leq \frac{|f(w)-f(m)| +|f(m)-f(z)|}{|w-m|+|m-z|} < {\varepsilon}$$

by the triangle inequality in the numerator and "triangle equality" for
$|w-z|$. By basic properties of fractions, this is between
$\modulus{q(w,m)}$ and $\modulus{q(m,z)}$, so
it too is less than ${\varepsilon}$.

From here we need only topology. Fix $z \in X$. Let 
$S = \{w | q(w,z)<{\varepsilon}\}$. This is open because $q(w,z)$ is a 
continuous function of $w$. If any $w \in X-S$, then we may choose 
such a $w$ as close as possible to $z$. By convexity, $z$ and $w$ 
are connected by a straight line segment $I$. 
Since $\modulus{f'(w)}<\varepsilon$, we have a neighborhood 
$B(w,\delta)$ on which $\norm{q(w,x)}<\varepsilon$.
Choose $m \in I \cap B(w,\delta)$ between $z$ and $w$, and we 
have a contradiction to the transitivity condition above.
:::



::: {#cor-zero-derivative-locally-constant .corollary}
If $f:U \to {\mathbb C}$ is differentiable with
zero derivative then $f$ is locally constant in the sense that
$\forall z \in U \enspace \exists \delta>0 \enspace f$ is constant on
$B(z,\delta)$.
:::

::: {.proof}
@thm-small-derivative-small-q
 applies for all
$\varepsilon>0$. 
:::

::: {#cor-zero-derivative-constant .corollary}
If $f:U \to {\mathbb C}$ is differentiable with
zero derivative and $U$ is connected, then $f$ is constant.
:::

::: {.proof}
Choose $z_0 \in U$ and let $c = f(z_0)$. Then
$U = f^{-1}(c) \cup f^{-1}({\mathbb C}-\{c\})$. The first set is open by
@cor-zero-derivative-locally-constant, and the second is open
by continuity. By connectedness, the latter set must be empty, so $f$ is
constant. 
:::

::: {#cor-antiderivative-uniqueness .corollary}
Let $f:U \to {\mathbb C}$, with $U$ open and
connected. If $f$ has an antiderivative, then it is unique up to
constant.
:::

::: {.proof}
If $F_1$ and $F_2$ are antiderivatives of $f$, then $F_1-F_2$
has zero derivative, so is constant. 
:::

From @thm-small-derivative-small-q we also deduce:

::: {#cor-estimate-derivative-estimate-q .cor}
Let $X$ be an open convex subset of ${\mathbb C}$
or ${\mathbb R}$, and let $f:X \to {\mathbb C}$ be differentiable with
$f'\in B(m,{\varepsilon})$, with $m \in {\mathbb C}$. Then
$\forall w \neq z \in X \enspace 
    \frac{f(w)-f(z)}{w-z} \in B(m,{\varepsilon})$.
:::

::: {.proof}
Apply @thm-small-derivative-small-q to the function
$f(x)-mx$. 
:::

If furthermore $f'$ is a continuous function, then $q(w,z)$ is 
not only continuous in each variable, but also a continuous 
function of two variables.

::: {#thm-q-continuous .theorem}
Let $f:X \to {\mathbb C}$, where $X$ is an open
subset of ${\mathbb C}$ or ${\mathbb R}$. If $f'$ is defined and
continuous on $X$, then the function
$$q(w,z) = \left\{\begin{array}{ll}\frac{f(w)-f(z)}{w-z}  & \text{ if $w \neq z$}\\ f'(z)& \text{ if $w= z$} \end{array} \right.$$
is a continuous function from $X \times X$ to ${\mathbb C}$.
:::

::: {.proof}
We prove continuity at an arbitrary point $(z_0,w_0)$. If
$w_0 \neq z_0$ then in a neighborhood of $(z_0,w_0)$ we have
$q(w,z) =  \frac{f(w)-f(z)}{w-z}$, which is continuous since both $f(z)$
and $\frac{1}{w-z}$ are. If $w_0=z_0$, let ${\varepsilon}>0$.
Let $m = f'(z_0) = q(w_0,z_0)$. Choose $\delta>0$ so that
$\modulus{w-z_0}<\delta \to f'(w) \in B(m,{\varepsilon})$
by continuity of $f'$. Since $B(z_0,\delta)$ is convex, 
@cor-estimate-derivative-estimate-q applies,
so for all $(w, z) \in B(z_0,\delta) \times B(z_0,\delta)$ we have
$q(w,z) \in B(m,{\varepsilon})$. Therefore $q$ is
continuous. 
:::

Any continuous function will be uniformly continuous on compact sets. If
$X$ is furthermore compact we get a very useful tool which allows us to
uniformly estimate $\frac{f(z)-f(w)}{z-w}$ using the derivative
$f'(z_0)$ at a different, but nearby point $z_0$:

::: {#thm-uniform-approximation-of-q .theorem}
**(Uniform approximation of the difference quotient)**
Let $f:K \to {\mathbb C}$, where $K$ is a compact
subset of ${\mathbb C}$ or ${\mathbb R}$. If $f'$ is defined and
continuous on some open superset $U$ of $K$, then
$$\forall {\varepsilon}>0 \enspace \exists \delta>0 \enspace \forall z_0 \in K \enspace \forall w \neq z\in B(z_0, \delta) \cap K \to \modulus{\frac{f(z)-f(w)}{z-w} - f'(z_0)} < {\varepsilon}$$
:::

::: {.proof}
We apply the uniform continuity of
$q(w,z) = \left\{\begin{array}{ll}\frac{f(w)-f(z)}{w-z}  & \text{ if $w \neq z$}\\ f'(z)& \text{ if $w= z$} \end{array} \right\}$ on the domain
$K \times K$ to learn:
$$\forall {\varepsilon}>0 \enspace \exists \delta>0 \enspace \forall (w_0, z_0) \in K\times K \enspace \forall (w,z) \in K\times K \enspace d((w_0,z_0), (w,z))< \delta \to \modulus{q(w, z) - q(w_0,z_0)}< {\varepsilon}$$
Here $d((w_0,z_0), (w,z)) = \max(\modulus{w_0-w},\modulus{z_0-z})$.
The desired formula is obtained by taking the special case $w_0=z_0$ and
noting that when $w_0=z_0$ the condition $w \neq z\in B(z_0, \delta)$
implies the condition $d((w_0,z_0), (w,z))< \delta$. 
:::



@thm-uniform-approximation-of-q plays a role in our integration theory similar
to the mean value theorem in a theory based within ${\mathbb R}$. 

::: {#exr-q-discontinuity-counterexample }
A standard example of a function
$f:{\mathbb R}\to {\mathbb R}$ with discontinuous derivative is:
$$f(x) = \begin{cases}x^2 \sin(1/x) & \text{ if } x \neq 0 \\ 0 & \text{ if } x =0 \end{cases}$$

1.  Prove that $f$ is differentiable (everywhere) but $f'$ is
    discontinuous.

2.  Justify: $q(w,z): {\mathbb R}\times {\mathbb R}\to {\mathbb R}$ is
    continuous in $w$ for fixed $z$ and continuous in $z$ for fixed $w$.

3.  Prove: $q(w,z)$ is discontinuous at $(0,0)$.
:::

# Integration

## Motivation

### The Riemann Integral on ${\mathbb R}$

We wish to define a theory of complex integration which directly
generalizes the real integral $\int_a^b f(x) dx$. It isn't obvious how
the theory should change to accommodate the complex numbers, and the
basic definitions are a bit mysterious to the beginner. So we begin with
a conversation designed to review real integration and motivate new
definitions.

The real (definite) integral $\int_a^b f(x) dx$ is meant of course to
measure the signed area under the curve $f(x)$ between $x=a$ and $x=b$.
It requires remarkably sophisticated geometry to directly define "area"
in a way that applies to the great variety of graphs of everyday
functions, so instead we approximate the area using rectangles, and
define the integral to be the limit of rectangular approximations, as
rectangles narrow toward zero width:

::: {#def-real-integral-naive .definition}
**(Real integral -- incomplete definition)**
Let $f:{\mathbb R}\to {\mathbb R}$ be a function. The **definite integral of
$f$ from $a$ to $b$** is defined to be
$$\int_a^b f(x) dx \equiv_{\text{def}} \lim \sum_{i=1}^{m} f(\tau_i)(t_{i} - t_{i-1})$$
:::

We have divided the interval $[a,b]$ into $m$ parts
$a=t_0<t_1<\ldots<t_m=b$ and placed sample points $\tau_i$ into these
parts. Geometrically, $t_i-t_{i-1}$ measures the width of the $i$'th
rectangle and $f(\tau_i)$ its height. Often it is presumed that the
rectangle boundaries $t_i$ are evenly spaced, so $(t_i-t_{i-1})$ is a
constant width, which then must be $\frac{b-a}{m}$. Note that there is
an arbitrariness in the argument of $f$: We could take $f(t_i)$ ("right
hand rule"), $f(t_{i-1})$ ("left hand rule"), $f(\frac{t_i+t_{i-1}}{2})$
("midpoint rule") or more generally any $f(\tau_i)$ with
$t_{i-1} \leq \tau_i \leq t_i$.

What sort of limit is meant in the definition of the real integral?
Superficially, this is easy: To make the rectangles ever narrower, we
mean the limit as ${m \to \infty}$ with equal width rectangles.

What could be wrong with that? For practical purposes, some integrals
are much easier to calculate using strategically unequal widths. For
example, to calculate $\int_1^b \frac{1}{x} dx$, a subdivision in which
$t_i = b^{i/m}$ gives each rectangle equal area. On a more theoretical
note, assuming that $a$ and $b$ are rational, setting
$\tau_i = a+i\frac{b-a}{m}$ commits us to only evaluating the function
$f:[a,b] \to {\mathbb R}$ at rational inputs. It seems improper that
"most" of the values $f(x)$ of $f$, that is the values at irrational
$x$, should be disregarded in the definition of $\int_a^b f(x) dx$.

These are reasons to consider more general arrangements of points
$a=t_0<t_1<\ldots<t_m=b$, and more general sample points $\tau_i$: We
call this data a *partition.*

::: {#def-partition .definition}
A **partition** $P$ of a closed interval $[a,b]$ is
a finite set of points $a<t_0<t_1<\ldots<t_m=b$, called the
**endpoints** of $P$. A **tagged partition** is a partition as above,
together with a list of **tags** $\tau_1, \ldots \tau_m$, so that
$t_{i-1}\leq \tau_i \leq t_i$. We say $\tau_i$ **tags** the interval
$[t_{i-1}, t_i]$ for $P$.
:::

The intervals $[t_{i-1}, t_i]$ divide $[a,b]$ into regions on which
we'll draw rectangles. The tags $\tau_i$ are sample points: We evaluate
$f$ at $\tau_i$ to assess the height of the rectangle based on
$[t_{i-1},t_i]$. Incorporating this useful generalization into our
definition of the integral gives us an immediate problem interpreting
the limit, because we can no longer regard $t_i$ and $\tau_i$ as
functions of $m$. To describe the limit "as the rectangles get
narrower," we measure the **norm** of a partition to be the maximum
width of its intervals.

::: {#def-partition-norm .definition}
Let $P$ be a partition of $[a,b]$ with endpoints
$a<t_0<t_1<\ldots<t_m=b$. The **norm** of $P$ is the maximum width:
$$||P|| \equiv_{\text{def}} \max\{t_i-t_{i-1} : 1\leq i\leq m\}$$
:::

::: {#def-real-integral-partitions .definition}
**(Real integral -- partitions definition)**
Let $f:{\mathbb R}\to {\mathbb R}$ be a function. The **definite integral of
$f$ from $a$ to $b$** is defined to be 
$$\int_a^b f(x) dx \equiv_{\text{def}} \lim_{\norm{P} \to 0} \sum_{i=1}^{m} f(\tau_i)(t_{i} - t_{i-1})$$
If the limit exists, we say that $f$ is **Riemann integrable.**
:::

...but this is a new kind of limit entirely, demanding a new
definition.

::: {#def-partition-limit .definition}
Let $\phi$ be a function from tagged partitions of
$[a,b]$ to ${\mathbb R}$ (or ${\mathbb C}$). We define:
$$\lim_{\norm{P} \to 0} \phi(P) \equiv_{\text{def}} \iota L \enspace \forall \varepsilon>0 \enspace \exists \delta >0 \enspace \forall \text{ tagged partitions } P \text{ on } [a,b] \enspace \big(\norm{P}<\delta \to |\phi(P)-L|<\varepsilon\big)$$
:::

Note that the codomain of $\phi$ can be changed to any metric space by
replacing $|\phi(P)-L|$ with $d(\phi(P),L)$.

### Complex integrals

Let's consider an integral $\int_a^b f(z) dz$, where
$f:{\mathbb C}\to {\mathbb C}$ is a complex function and
$a, b \in {\mathbb C}$ are complex numbers. To mimic the work above we
would introduce waypoints $a=z_0, z_1,\ldots, z_n=b$, and sample points
$\tau_i$. Our waypoints $z_n$ can no longer be ordered because
${\mathbb C}$ has no order structure. We can no longer insist that
$z_{i-1} \leq \tau_i \leq z_i$ for the same reason, but let us ignore
this problem for now. We could, however, generalize the idea of
partition norm to be $\max_i \modulus{z_i-z_{i-1}}$. But
after all this we would still discover an intractable difficulty: For
many very reasonable functions such as $f(z) = 1/z$, the limit of sums
$\sum_{i=1}^{m} f(\tau_i)(z_{i} - z_{i-1})$ depends on how the points
$z_i$ meander in two dimensions from $a$ to $b$, and straight line paths
are not always possible. We must therefore separate the question of
subdivision from the question of how these points wander around in the
complex plane. We define an object called a *path* (written $\gamma$)
which exactly prescribes these wanderings. Then the integral depends not
only on endpoints $a$ and $b$ but on the path $\gamma$.

::: {#def-path .definition}
A **path** is a continuous function
$\gamma:[a,b] \to {\mathbb C}$ from a closed interval to ${\mathbb C}$.
A path is **closed** if $\gamma(a)=\gamma(b)$.
:::

This frees us to return to ordinary, real tagged partitions: If $P$ is a
partition of the domain $[a,b]$ of a path $\gamma$, then
$\{\gamma(t_i)\}$ will be the needed finite sequence of waypoints in
${\mathbb C}$, and $\gamma(\tau_i)$ will be the required sample points.
We now define the path integral of a complex function.

::: {#def-path-integral .definition}
**(Path integral)**
Let $f:{\mathbb C}\to {\mathbb C}$
be a function, and $\gamma:[a,b] \to {\mathbb C}$ a path. The **path
integral of $f$ along $\gamma$** is defined to be
$$\int_\gamma f(z) dz \equiv_{\text{def}} \lim_{\norm{P} \to 0} \sum_{i=1}^{m} f(\gamma(\tau_i))(\gamma(t_{i}) - \gamma(t_{i-1}))$$
where the limit is over tagged partitions $P$ of $[a,b]$.
:::

::: {#exr-path-integral-constant-function }
 Prove directly from the previous definition that when
$f$ is the constant function $f(z)=k$, then
$\int_\gamma f(z) dz = k(\gamma(b)-\gamma(a))$. (You may take for
granted that the limit in this new sense of a constant is that
constant.)
:::



::: {#exr-integrability-chi-Q }
 Let $\chi_{\mathbb Q}:{\mathbb R}\to {\mathbb R}$ by
$\chi_{\mathbb Q}(x) = \left\{\begin{array}{lr} 1 & \text{ if } x \in {\mathbb Q}\\ 0 & \text{ if } x \notin {\mathbb Q}\end{array}\right.$

1.  Show that $\chi_{\mathbb Q}$ is integrable (i.e., the integral limit
    exists) on $[0,1]$, and calculate its integral, using the definition
    $$\int_a^b f(x) dx \equiv_{\text{def}} \lim_{m \to \infty} \sum_{i=1}^{m} f(\tau_i)(t_{i} - t_{i-1})$$
    where $t_i = \frac{i(b-a)}{m}$ and $\tau_i=t_i$.

2.  Show that $\chi_{\mathbb Q}$ is not integrable on $[0,1]$ using the
    (more sophisticated) partition-based definition
    $$\int_a^b f(x) dx \equiv_{\text{def}} \lim_{\norm{P} \to 0} \sum_{i=1}^{m} f(\tau_i)(t_{i} - t_{i-1})$$
    where $t_i$ and $\tau_i$ come from the partition $P$.
:::

::: {#exr-integral-unbounded }
 Prove that if $f:[a,b] \to {\mathbb R}$ is unbounded,
then $\int_a^b f(x) dx$ does not exist. (This should bother you when you
remember your improper integrals!)
:::

Since the function $f:{\mathbb C}\to {\mathbb C}$ enters into the right
hand side only to form the composition
$f \circ \gamma:[a,b] \to {\mathbb C}$, we have an obvious
generalization in which $f \circ \gamma$ is replaced with an arbitrary
function on $[a,b]$:

::: {#def-riemann-stieltjes-integral .definition}
**(Riemann-Stieltjes integral)**
Let $f:[a,b] \to {\mathbb C}$ be a function, and
$\gamma:[a,b] \to {\mathbb C}$ a function (usually a path). The
**Riemann-Stieltjes integral of $f$ with respect to $\gamma$** is
defined to be
$$\int_a^b f d\gamma = \int_a^b f(t) d\gamma(t) \equiv_{\text{def}} \lim_{\norm{P} \to 0} \sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1}))$$
where the limit is over tagged partitions $P$ of $[a,b]$.
:::



This is a rich and interesting generalization of the Riemann integral,
even in case $\gamma:[a,b] \to {\mathbb R}$ is a nonincreasing (not
necessarily continuous) real valued function. In that case, the
Riemann-Stieltjes integral acts like a weighted integral of $f$, in
which portions of $[a,b]$ are given more weight in proportion to
$\gamma'$ (if indeed $\gamma$ is differentiable). Jump discontinuities
of $\gamma$ give nonzero weight, in the sense of integration, to single
points of $[a,b]$.

::: {.note}
**Note:** 
If $\gamma(t) = t$ in the Riemann-Stieltjes integral,
then $\int_a^b f(t) dt = \int_a^b f d\gamma$

If $\gamma$ is a path, then
$$\int_\gamma f(z) dz = \int_a^b (f \circ \gamma) d\gamma$$

By studying the Riemann-Stieltjes integral, we are developing a common
foundation of both complex path integrals and ordinary Riemann
integration.
:::



::: {#exr-integral-examples }
 Let $\gamma:[0,1] \to {\mathbb C}$ be a straight line
path from $1$ to $i$. Give an explicit equation for $\gamma$.

1.  Calculate $\int_\gamma |z|^2 dz$, by converting the integrand to a
    real-valued function of a real variable $t \in [0,1]$ and using real
    methods.

2.  Calculate $\int_\gamma z^2 dz$. In this case the integrand is
    complex. Expand and separate it into real and imaginary part, and
    reduce the problem to two real integrals.
:::

## Limit properties of functions on partitions

We wish to prove a criterion for existence of the Riemann-Stieltjes
integral. The integral is a limit as $\norm{P} \to 0$,
and it's convenient to develop the properties of such limits:

::: {#def-partition-refines .definition}
Let $P$ and $Q$ be partitions of $[a,b]$ (tagged or
not). We say that $Q$ **refines** $P$, and write $P \preccurlyeq Q$, if
the endpoints $\{t_i\}$ of $P$ form a subset of the endpoints $\{s_j\}$
of $Q$. (Note: For $P \preccurlyeq Q$, we require no relationship
between tags. Some authors do!)
:::

Note that when $P \preccurlyeq Q$, $Q$ is greater in terms of *more
division points*, but $P$ usually has wider intervals.

::: {#prp-partition-limit-sup .proposition}
Let $\phi(P)$ be a function from tagged
partitions $P$ of $[a,b]$ to ${\mathbb R}$ with $\phi$ increasing in the
sense that if $P \preccurlyeq Q$ then $\phi(P) \leq \phi(Q)$. If
$\displaystyle \lim_{\norm{P} \to 0} \phi(P)$ exists
then it equals $\sup_P(\phi(P))$
:::



::: {.proof}
Let $L = \lim_{\norm{P} \to 0} \phi(P)$. Let
$Q$ be any partition. Let $\varepsilon >0$. Choose $\delta>0$ for
$\varepsilon$ in the definition of the limit. Choose some refinement
$Q \preccurlyeq R$ with $\norm{R}<\delta$. Then
$\phi(Q) \leq \phi(R) < L+\varepsilon$. Since $\varepsilon$ was arbitary,
$\phi(Q) \leq L$ for all $Q$ and $\sup_P(\phi(P)) \leq L$. Since
$\phi(P)$ can be made arbitarily close to $L$,
$\sup_P(\phi(P)) \geq L$. 
:::

::: {#def-partition-cauchy .definition}
Let $\phi(P)$ be a function from tagged partitions
$P$ of $[a,b]$ to a metric space $X$ (usually ${\mathbb C}$). We say
that $\phi$ is **Cauchy** if:
$$\forall {\varepsilon}>0 \enspace \exists \delta>0 \enspace \forall \text{ tagged partitions } P, Q \text{ with } \norm{P} <\delta \text{ and } P \preccurlyeq Q  \text{ we have } d(\phi(P),\phi(Q))<{\varepsilon}$$
:::

::: {#thm-cauchy-partition-converges .theorem}
Let $\phi(P)$ be a function from tagged partitions
$P$ of $[a,b]$ to a complete metric space $X$. Then $\phi$ is Cauchy if
and only if
$\displaystyle \lim_{\norm{P} \to 0} \phi(P)$ exists.
:::



::: {.proof}
If $\lim_{\norm{P} \to 0} \phi(P) = L$, let
${\varepsilon}>0$ and choose $\delta>0$ so that
$\norm{P}<\delta$ implies
$d(\phi(P),L) < {\varepsilon}/2$. Now if $P \preccurlyeq Q$
then $\norm{Q}<\delta$ and
$d(\phi(P),\phi(Q)) \leq d(\phi(P),L) + d(\phi(Q),L) < {\varepsilon}/2+{\varepsilon}/2 = {\varepsilon}$.

Conversely let $\phi$ be Cauchy. Construct a sequence of partitions
$P_0 \preccurlyeq 
    P_1 \preccurlyeq P_2 \preccurlyeq \ldots$ with
$\lim_n \norm{P_n} = 0$. For example, subdivide
$[a,b]$ into $2^n$ equal intervals, tagged at midpoints. Then the
sequence $(\phi(P_n))$ is Cauchy in the usual sense, so has a limit $L$.
To see that $\lim_{\norm{P} \to 0} \phi(P) =L$, let
${\varepsilon}>0$. Choose $\delta$ for
${\varepsilon}/3$ in the Cauchy criterion for $\phi$, and
choose $N$ so that for $n>N$ we have
$\norm{P_n}<\delta$ and
$d(\phi(P_n),L)<{\varepsilon}/3$. To show partition
convergence, let $\norm{Q}<\delta$. Choose some $n>N$
and a joint refinement filter $R$ so that $P_n \preccurlyeq R$ and
$Q \preccurlyeq R$. Then the Cauchy criterion applies to both
$d(\phi(Q),\phi(R))$ and $d(\phi(R),\phi(P_n))$, so:
$$d(\phi(Q),L) \leq  d(\phi(Q),\phi(R)) +d(\phi(R),\phi(P_n))  +d(\phi(P_n),L)  \leq {\varepsilon}/3+{\varepsilon}/3+{\varepsilon}/3 = {\varepsilon}$$ 
:::

## Existence of Integrals

Now we have some headache: There are some *very* strange continuous
functions $\gamma:[a,b] \to {\mathbb C}$: Maps whose images have
infinite length, whose images are fractals (e.g., the Koch curve), or
even two-dimensional images (e.g., the Peano space-filling curve). None
of these sets are convenient domains of integration, so we must identify
a subclass of "reasonable" curves, in particular those of finite length
in a sense we call "bounded variation."

::: {#def-variation .definition}
Let $\gamma:[a,b] \to {\mathbb C}$ be a function.
The **variation** of $\gamma$ on a partition $P$ with endpoints
$\{a=t_0< \ldots< t_m=b\}$ is the total distance along the $m$ straight
line segments connecting $\gamma(t_0), \ldots , \gamma(t_m)$:
$$v(\gamma;P) \equiv_{\text{def}} \sum_{i=1}^m \modulus{\gamma(t_i)-\gamma(t_{i-1})}$$
The **total variation** of $\gamma$ is the supremum over all partitions
$P$ of $[a,b]$: $$v(\gamma) \equiv_\text{def} \sup_P v(\gamma ; P)$$ If
$V(\gamma)$ is finite, we say $\gamma$ has **bounded variation**.
:::

We will show that if $f$ is continuous and $\gamma$ has bounded
variation, then the integral $\int_a^b f(t) d\gamma(t)$ exists.
Integrals over paths of unbounded variation sometimes do not exist.

::: {#prp-variation-increasing .proposition}
$v(\gamma,P)$ is an increasing function of $P$ in
the sense that if $P \preccurlyeq Q$ then
$v(\gamma,P) \leq v(\gamma,Q)$
:::

::: {.proof}
Let $P$ have endpoints $\{t_i\}_{i=0}^m$ and let $Q$ have
endpoints $\{s_j\}_{j=0}^n$. Apply the triangle inequality to
$\modulus{\gamma(t_i)-\gamma(t_{i-1})} = \modulus{\gamma(s_{j_i})- \gamma(s_{j_i-1})+\gamma(s_{j_i-1}) \ldots - \gamma(s_{j_{i-1}})}$. 
:::

::: {#cor-variation-limit .cor}
Let $\gamma:[a,b] \to {\mathbb C}$ be a function.
If $\lim_{\norm{P} \to 0} v(\gamma,P)$ exists then it
equals $v(\gamma)$.
:::



We are now ready to prove the existence of the integral:

::: {#thm-integral-continuous-exists .theorem}
Let $\gamma:[a,b] \to {\mathbb C}$ have bounded
variation, and let $f:[a,b] \to {\mathbb C}$ be continuous. Then
$\int_a^b f(t) d\gamma(t)$ exists.
:::

::: {.proof}
The integral is a limit as $\norm{P} \to 0$,
and of course we plan to use the Cauchy criterion. Let
${\varepsilon}>0$. Since $f$ is continuous on a compact set,
it is uniformly continuous and we may choose $\delta>0$ so that whenever
$\modulus{x-y}<\delta$ then
$\modulus{f(x)-f(y)}<\frac{{\varepsilon}}{v(\gamma)}$.
Here $v(\gamma)$ is the variation of $\gamma$, presumed finite. Let
$P \preccurlyeq Q$ be partitions of $[a,b]$, where $P$ has endpoints
$t_i$ and tags $\tau_i$ and $Q$ has endpoints $s_j$ and tags $\sigma_j$,
and assume $\norm{P} <\delta$. Since $Q$ refines $P$,
each $t_i$ is equal to some $s_j$. Say $t_i = s_{k_i}$. The difference
$\modulus{\sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1})) - \sum_{j=1}^{m'} f(\sigma_j)(\gamma(s_{j}) - \gamma(s_{j-1}))}$
can be reorganized by expanding each single term
$f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1}))$ to a subsum
$\sum_{j=k_{i-1}+1}^{k_i} f(\tau_i)(\gamma(s_j) - \gamma(s_{j-1}))$ We
let $\tau'_j = \tau_i$ for all $j$ in this range, so that the term
$f(\tau_i)$ can be expressed as a function of $j$. Thus:

\begin{align}
    \sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1})) &= \sum_{i=1}^m \sum_{j=k_{i-1}+1}^{k_i} f(\tau'_j)(\gamma(s_j) - \gamma(s_{j-1}))\\
    &= \sum_{j=1}^{m'} f(\tau'_j)(\gamma(s_j) - \gamma(s_{j-1}))\\
\end{align}

The watchful reader will notice that the sum above is not a normal
partition estimate to an integral because $\tau'_j$ is not necessarily
in the range $[s_{j-1},s_j]$. Nevertheless we may combine the two sums:

\begin{align}
    \modulus{\sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1})) - \sum_{j=1}^{m'} f(\sigma_j)(\gamma(s_{j}) - \gamma(s_{j-1}))} &= \\
    \modulus{\sum_{j=1}^{m'} f(\tau'_j)(\gamma(s_j) - \gamma(s_{j-1})) -  f(\sigma_j)(\gamma(s_{j}) - \gamma(s_{j-1}))} &=
    \modulus{\sum_{j=1}^{m'} (f(\tau'_j)- f(\sigma_j))(\gamma(s_j) - \gamma(s_{j-1}))}  \\
    &\leq \sum_{j=1}^{m'} \modulus{f(\tau'_j)- f(\sigma_j)}\modulus{\gamma(s_j) - \gamma(s_{j-1})} \\
    &< \sum_{j=1}^{m'} \frac{{\varepsilon}}{v(\gamma)}\modulus{\gamma(s_j) - \gamma(s_{j-1})}  \leq {\varepsilon}
\end{align}

We conclude that the function
$\sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1}))$ is a Cauchy
function of the partition $P$, so it converges. That is, the integral
$\int_a^b f(t) d\gamma(t)$ exists. 
:::



::: {#thm-Riemann-integral-exists .cor}
Let $f:[a,b] \to {\mathbb C}$ be continuous. Then
$\int_a^b f(t) dt$ exists.
:::

::: {.proof}
$\gamma(t)=t$ has bounded variation $v(\gamma)=b-a$. 
:::

::: {#exr-lipschitz-integrability }
 A function $h:X \to {\mathbb C}$ (with
$X \subseteq {\mathbb C}$) is called **Lipschitz** if it has bounded
difference quotients: That is, there is a constant $M$ so that for all
$x \neq y \in X$ $\modulus{\frac{h(y)-h(x)}{y-x}}<M$. Prove
that if $f:[a,b] \to {\mathbb C}$ and $\gamma:[a,b] \to {\mathbb C}$ are
both Lipschitz, then $\int_a^b f d\gamma$ exists. (Hint: Not from the
definitions!)
:::

The next theorem is easy but extremely useful:

::: {#thm-ML-inequality .theorem}
**(ML inequality)**
Let $f:[a,b] \to {\mathbb C}$ be
continuous. Let $|f| \leq M$ on $[a,b]$, and let $L = v(\gamma)$. Then
$\modulus{\int_a^b f(t) d\gamma} \leq ML$.
:::

::: {.proof}
Notice the integral exists by @thm-integral-continuous-exists.
For any partition $P$ we have
$$\modulus{\sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1}))} \leq \sum_{i=1}^{m} M\modulus{\gamma(t_{i}) - \gamma(t_{i-1})} \leq Mv(\gamma) \leq ML$$
:::

::: {#cor-limit-commutes-integral .cor}
Let $g(z,w)$ be a continuous function of two
variables on $U \times im(\gamma)$, where $\gamma$ is continuous and
bounded variation. Let $z_0 \in U$. Then
$$\lim_{z \to z_0} \int_\gamma g(z,w) dw = \int_\gamma \lim_{z \to z_0}  g(z,w) dw = \int_\gamma g(z_0,w) dw$$
:::

::: {.proof}
Choose a ball $\overline{B(z_0,\rho)} \subseteq U$ and choose
$\delta<\rho$ for $\frac{{\varepsilon}}{v(\gamma)}$ in the
uniform continuity of $g$ on the compact set
$\overline{B(z_0,\rho)} \times im(\gamma)$. Then when
$\modulus{z-z_0}<\delta$ the ML inequality gives:

$$\modulus{\int_\gamma g(z,w) dw - \int_\gamma g(z_0,w) dw } = \modulus{\int_\gamma g(z,w) - g(z_0,w) dw} \leq \frac{{\varepsilon}}{v(\gamma)} v(\gamma) = {\varepsilon}$$ 
:::

::: {#thm-integral-additivity .theorem}
**(Additivity properties of Riemann-Stieltjes integral)**
Let $f, g: [a,b] \to {\mathbb C}$ be continuous, let
$\gamma, \sigma:[a,b] \to {\mathbb C}$ be bounded variation, and let
$c_1,c_2 \in {\mathbb C}$. Then

1.  $\int_a^b (c_1f+c_2g) d\gamma = c_1\int_a^b f d\gamma + c_2\int_a^b g d\gamma$

2.  $\int_a^b f d(c_1\gamma+c_2\sigma) = c_1\int_a^b f d\gamma + c_2 \int_a^b f d\sigma$

3.  $\int_a^{b'} f d\gamma = \int_a^b f d\gamma +  \int_b^{b'} f d\gamma$
:::

::: {.proof}
(Parts 1 and 2 are routine. Part 3 is subtle because an
arbitrary partition $P$ of the interval $[a,b']$ may not have $b$ as an
endpoint.) 
:::

::: {#exm-differentiable-unbounded-variation .example}
**(Differentiability does not guarantee bounded variation.)**
Let 
$$\gamma(t) = \left\{\begin{array}{lr} t^2 \cos(\frac{1}{t^2}) & \text{ if } t \neq 0 \\ 0 & \text{ if } t=0 \end{array} \right\}$$ 
Then $\gamma$ is everywhere differentiable, $\gamma'$ is
discontinuous at $0$, and $\gamma$ has unbounded variation on any
neighborhood of $0$.
:::

::: {.proof}
By the usual differentiation rules, if $t \neq 0$ then
$\gamma'(t)= 2t \cos(\frac{1}{t^2}) + \frac{2}{t} \sin(\frac{1}{t^2})$,
which is unbounded in a neighborhood of $0$. Furthermore $\gamma'(0) =0$
because $-t^2 \leq \gamma(t) \leq t^2$. Thus $\gamma'$ is everywhere
defined but discontinuous at $0$.

Next consider $v(\gamma,P)$ where $P$ is a partition of $[a,b]$, $a<0<b$
having endpoints rigged to make the cosine $\pm 1$:
$$a < 0 < \frac{1}{\sqrt{\pi M}} <\frac{1}{\sqrt{\pi (M-1)}} < \ldots < \frac{1}{\sqrt{\pi N}} < b$$
(Note if $b>0$ we may choose $0<<N<M$ so that
$\frac{1}{ \sqrt{\pi N}} < b$. For simplicity take both $M$ and $N$
even.) The corresponding values of $\gamma$ are:
$$\gamma(a), 0, \frac{1}{\pi M}, \frac{-1}{\pi (M-1)},\frac{1}{\pi (M-2)}, \ldots, \frac{-1}{\pi (N+1)},\frac{1}{\pi N}, \gamma(b)$$
Because the harmonic series diverges, $v(\gamma,P)$ can be made
arbitrarily large by choosing $M$ sufficient large. 
:::

The previous example indicates that we need a stronger condition than
differentiability to guarantee bounded variation:

::: {#def-smooth-path .definition}
Let $\gamma:[a,b] \to {\mathbb C}$ be a function.
We call $\gamma$ **smooth** if $\gamma$ is differentiable and $\gamma'$
is continuous.
:::

::: {#thm-smooth-bounded-variation .prop}
If $\gamma:[a,b] \to {\mathbb C}$ is smooth, then
$\gamma$ has bounded variation and moreover
$v(\gamma) = \int_a^b \modulus{\gamma'(t)} dt$.
:::



::: {.proof}
We claim that the integral exists and for any
${\varepsilon}>0$ there is a $\delta>0$ so that if
$\norm{P}<\delta$ then both

$$\modulus{\sum_{i=1}^m \modulus{\gamma(t_i)-\gamma(t_{i-1})}- {\sum_{i=1}^{m} \modulus{\gamma'(\tau_i)}(t_{i} - t_{i-1})}} < {\varepsilon}/2 \hspace{1cm} \text{ and } \hspace{1cm} \modulus{{\sum_{i=1}^{m} \modulus{\gamma'(\tau_i)}(t_{i} - t_{i-1})}-  \int_a^b \modulus{\gamma'(t)} dt}<{\varepsilon}/2$$

Together these will establish that
$\lim_{\norm{P} \to 0} \sum_{i=1}^m \modulus{\gamma(t_i)-\gamma(t_{i-1})}= \int_a^b \modulus{\gamma'(t)} dt$,
after which @cor-variation-limit applies.

By @thm-Riemann-integral-exists
we know that
$\int_a^b \modulus{\gamma'(t)} dt$ exists. The righthand
inequality then follows by the definition of the integral.

For the lefthand inequality, let $P$ be a partition with endpoints $t_i$
and tags $\tau_i$. 
\begin{align}
    \modulus{\sum_{i=1}^m \modulus{\gamma(t_i)-\gamma(t_{i-1})} -
    \sum_{i=1}^{m} \modulus{\gamma'(\tau_i)}(t_{i} - t_{i-1})}
    =& \modulus{\sum_{i=1}^m \left(\modulus{\frac{\gamma(t_i)-\gamma(t_{i-1})}{t_{i} - t_{i-1}}} - \modulus{\gamma'(\tau_i)} \right)(t_i - t_{i-1})}\\
    \leq& \sum_{i=1}^m \modulus{\frac{\gamma(t_i)-\gamma(t_{i-1})}{t_{i} - t_{i-1}} - \gamma'(\tau_i)}(t_i - t_{i-1})
\end{align}
Now let ${\varepsilon}>0$. Using @thm-uniform-approximation-of-q
we can choose $\delta$ so that for any partition $P$ with
$\norm{P}<\delta$ we have
$\modulus{\frac{\gamma(t_i)-\gamma(t_{i-1})}{t_{i} - t_{i-1}} - \gamma'(\tau_i)} < \frac{{\varepsilon}}{2(b-a)}$.
The difference above is then less than ${\varepsilon}/2$. 
:::

::: {#exr-compute-variations }
 Compute the total variation $v(\gamma)$ for each of
the paths below.

1.  $\gamma(t) = Re^{it}$ on $[0,2\pi]$, where $R>0$.

2.  $\gamma(t) = mt+b$ on $[a,b]$, where $m,b \in {\mathbb C}$

3.  $\gamma(t) = \lfloor t/2 \rfloor$ on $[0,5]$.
:::

If $\gamma$ is smooth, then $d\gamma$ may be replaced with
$\gamma'(t)dt$ (as in traditional $u$-substitution), converting the
Riemann-Stieltjes integral to a traditional Riemann integral:

::: {#thm-Riemann-Stieltjes-smooth-Riemann .theorem}
Let $\gamma:[a,b] \to {\mathbb C}$ be smooth, and let
$f:[a,b] \to {\mathbb C}$ be continuous. Then
$$\int_a^b f d\gamma = \int_a^b f(t) \gamma'(t) dt$$
:::

::: {.proof}
Since $\gamma$ is smooth, it has bounded variation by
@thm-smooth-bounded-variation.
Therefore both integrals exist
by @thm-integral-continuous-exists
and @thm-Riemann-integral-exists
Let $P$ be a partition with
endpoints $t_i$ and tags $\tau_i$ and consider the difference between
the sums:
$$\sum_{i=1}^{m} f(\tau_i)(\gamma(t_{i}) - \gamma(t_{i-1}))  - \sum_{i=1}^{m} f(\tau_i)\gamma'(\tau_i)(t_{i} - t_{i-1})$$
Regrouping gives:
$$=\sum_{i=1}^{m} f(\tau_i)\left(\frac{\gamma(t_{i}) - \gamma(t_{i-1})}{t_{i} - t_{i-1}} - \gamma'(\tau_i)\right)(t_i-t_{i-1})$$

Let ${\varepsilon}>0$. Since $f$ is continuous on a compact
set we may bound it: $\modulus{f}<B$. Again by @thm-uniform-approximation-of-q,
we choose $\delta$ so that whenever $\norm{P}<\delta$
we have
$\modulus{\frac{\gamma(t_{i}) - \gamma(t_{i-1})}{t_{i} - t_{i-1}} - \gamma'(\tau_i)}<\frac{{\varepsilon}}{B(b-a)}$,
which makes the modulus of the sum less than ${\varepsilon}$
as required. 
:::

Next we prove a substitution theorem:

::: {#thm-Riemann-Stieltjes-substitution .theorem}
Let $\gamma:[a,b] \to {\mathbb C}$ and
$f:[a,b] \to {\mathbb C}$ be continuous. Let $\phi:[c,d] \to [a,b]$ be
continuous, nondecreasing, and onto. Then
$$\int_c^d (f \circ \phi)(t) d(\gamma \circ \phi)(t) = \int_a^b f(t) d\gamma(t)$$
provided the right hand side exists.
:::

::: {.proof}
Let ${\varepsilon}>0$. Since
$I = \int_a^b f(t) d\gamma(t)$ exists, we may choose $\rho>0$ according
to the definition of the integral, so that for any partition $P$ of
$[a,b]$ with $\norm{P}<\rho$ we have
$\modulus{I- \sum_{i=1}^m f(\tau_i)(\gamma(t)_i-\gamma(t_{i-1})) }<{\varepsilon}$.
Next choose $\delta$ for $\rho$ in the definition of absolute continuity
of $\phi$, so that
$\modulus{s-s'}<\delta \to \modulus{\phi(s)-\phi(s')} < \rho$.
Now if $Q$ partitions $[c,d]$ with endpoints $s_i$, tags $\sigma_i$, and
$\norm{Q}<\delta$, consider the integral estimate
using $Q$:
$$\sum_{i=1}^m f(\phi(\sigma_i))(\gamma(\phi(s_i))-\gamma(\phi(s_{i-1})))$$
This *is* an integral estimate using a partition "$\phi(Q)$" of $[a,b]$
having endpoints $\phi(s_i)$ and tags $\phi(\sigma_i)$, and
$\norm{\phi(Q)}<\rho$ by construction, so it is in
$B(I,{\varepsilon})$ as required. (If $\phi$ is not
injective, we may need to drop multiple copies of $\phi(s_i)$ to get a
partition, but this does not affect the sum.) 
:::

Recall that our interest in Riemann-Stieltjes integrals originated with
path integrals
$\int_{\gamma} f \equiv_{def} \int_a^b f(\gamma(t)) d\gamma(t)$. Let us
collect together our knowledge about this special case:

::: {#thm-path-integral-summary .theorem}
**(Path Integral Summary)**
Let $\gamma:[a,b] \to {\mathbb C}$ be a function and
let $f$ be defined on $\gamma([a,b])$.

1.  If $f$ is continuous and $\gamma$ is smooth then $\int_\gamma f$
    exists.
2.  If $\phi:[c,d] \to [a,b]$ is continuous, nondecreasing, and onto,
    then $\int_{\gamma \circ \phi} f = \int_\gamma f$ provided the right
    hand side exists.

3.  If $f$ is continuous and
    $\gamma$ is smooth then the path integral can be computed by an
    ordinary Riemann integral:
    $\int_\gamma f = \int_a^b f(\gamma(t)) \gamma'(t) dt$.
:::

::: {.proof}
The first is @thm-integral-continuous-exists and @thm-smooth-bounded-variation.
The second is @thm-Riemann-Stieltjes-substitution with $f \circ \gamma$ in
place of $f$. The third is @thm-Riemann-Stieltjes-smooth-Riemann.
:::

Finally we prove a Fundamental Theorem of Calculus for path integrals:

::: {#thm-FTC .theorem}
**(Fundamental Theorem of Calculus)** 
Let $\gamma:[a,b] \to {\mathbb C}$ be continuous with
bounded variation. Let $f:U \to {\mathbb C}$ be continuous on an open
set $U$ containing $im(\gamma)$ with primitive $F$ (i.e. $F'=f$). Then
$$\int_\gamma f(z) dz = F(\gamma(b)) - F(\gamma(a))$$
:::

::: {.proof}
Notice that $F$ is continuously differentiable on the compact
set $\gamma([a,b])$, so @thm-uniform-approximation-of-q
applies. Consider the absolute difference between the integral estimate
with partition $P$ of $[a,b]$ (with endpoints $t_i$ and tags $\tau_i$)
and the right hand side of the above equation:

\begin{align}
    &\modulus{\sum_{i=1}^{m} f(\gamma(\tau_i))(\gamma(t_{i}) - \gamma(t_{i-1}))  - (F(\gamma(b)) - F(\gamma(a)))} \\
    =& \modulus{\sum_{i=1}^{m} f(\gamma(\tau_i))(\gamma(t_{i}) - \gamma(t_{i-1}))  - \sum_{i=1}^m F(\gamma(t_i)) - F(\gamma(t_{i-1})) }\\
    =& \modulus{\sum_{i=1}^{m} \left(F'(\gamma(\tau_i)) - \frac{F(\gamma(t_i)) - F(\gamma(t_{i-1}))}{\gamma(t_i) - \gamma(t_{i-1})}\right)(\gamma(t_{i}) - \gamma(t_{i-1}))} \\
    \leq & \sum_{i=1}^{m} \modulus{F'(\gamma(\tau_i)) - \frac{F(\gamma(t_i)) - F(\gamma(t_{i-1}))}{\gamma(t_i) - \gamma(t_{i-1})}}\modulus{\gamma(t_{i}) - \gamma(t_{i-1})} \\
\end{align}

Let ${\varepsilon}>0$ and choose $\rho>0$ according to @thm-uniform-approximation-of-q
so that
$w \neq z\in B(z_0, \rho) \cap \gamma([a,b]) \to \modulus{F'(z_0) - \frac{F(z)-F(w)}{z-w}} < \frac{{\varepsilon}}{v(\gamma)}$.
By uniform continuity of $\gamma$ choose $\delta>0$ so that
$\modulus{x-y}<\delta \to \modulus{\gamma(x)-\gamma(y)}<\rho$.
Then for any partition $P$ with $\norm{P}<\delta$ we
have
$\modulus{F'(\gamma(\tau_i)) - \frac{F(\gamma(t_i)) - F(\gamma(t_{i-1}))}{\gamma(t_i) - \gamma(t_{i-1})}} < \frac{{\varepsilon}}{v(\gamma)}$.
Then
$$\sum_{i=1}^{m} \modulus{F'(\gamma(\tau_i)) - \frac{F(\gamma(t_i)) - F(\gamma(t_{i-1}))}{\gamma(t_i) - \gamma(t_{i-1})}}\modulus{\gamma(t_{i}) - \gamma(t_{i-1})} < \sum_{i=1}^{m} \frac{{\varepsilon}}{v(\gamma)}\modulus{\gamma(t_{i}) - \gamma(t_{i-1})} \leq \frac{{\varepsilon}}{v(\gamma)} v(\gamma) = {\varepsilon}$$
It follows that $\int_\gamma f = F(\gamma(b)) - F(\gamma(a))$ as
desired. 
:::

::: {#thm-closed-path-primitive-zero-integral .cor}
Let $f = F'$ on $\gamma$, a *closed* path. Then
$\int_\gamma f =0$.
:::

Our proof does not rely upon the Fundamental Theorem of Calculus for
real integrals, so we may safely deduce it as a corollary.

::: {#thm-real-FTC .corollary}
**(Fundamental Theorem of Calculus, Real Case)** 
Let $f:[a,b] \to {\mathbb R}$ be a continuous with antiderivative $F$ (i.e.
$F'=f$). Then $$\int_a^b f(x) dx = F(b) - F(a)$$
:::

::: {.proof}
Use the identity function for $\gamma:[a,b] \to [a,b]$ in the
previous theorem.  
:::

::: {#exr-real-FTC}
 Deduce the real Fundamental Theorem of Calculus
directly from @thm-uniform-approximation-of-q -- 
without using a path $\gamma$ -- as directly and simply as possible,
by using @thm-FTC as a guide.
:::

::: {#exr-integration-z-inverse}
In this exercise we compute
$\int_\gamma \frac{1}{z} dz$ for a circle $\gamma$. Specifically,
$\gamma(t) = e^{it}$ on the domain $[0, 2\pi]$.

1.  Explain why $\ln(z)$ is not an antiderivative of $\frac{1}{z}$
    suitable for use with the fundamental theorem of calculus for this
    problem.
2.  Breaking the integral into two parts using
    $\gamma_1 = \gamma|_{[0,\pi]}$ and
    $\gamma_2 = \gamma_{[\pi, 2\pi]}$, calculate it using the
    fundamental theorem of calculus for path integrals (twice). Be very
    specific about the choices of antiderivatives. Provide pictures
    illustrating the path decomposition.
3.  Starting over, calculate the integral using 
    @thm-Riemann-Stieltjes-smooth-Riemann
    without breaking it
    into two parts. Your answer should agree with the previous part.
4.  Using the previous parts of this problem and the fundamental
    theorem, prove that $\frac{1}{z}$ does not have an antiderivative on
    (all of) the unit circle.
:::

# Complex Integrals

## Integrals over circular paths

When it comes to calculating integrals, the Fundamental Theorem of
Calculus is key. It allows us to calculate any integral over any smooth
path, provided we can find an antiderivative.

::: { .example}
Let $\gamma:[0,1]$ be any smooth path starting from
$\gamma(0) = \pi$ and ending at $\gamma(1)=i$. Then
$\int_\gamma (\cos(z)+z^2) dz = (\sin(i)+\frac{i^3}{3}) - (\sin(\pi)+\frac{\pi^3}{3})$
:::

We can give hundreds of similar examples. Most math majors have ample
practice calculating integrals via antiderivatives in Calculus II, and
all those methods -- substitution, integration by parts, partial
fractions, double angle formulas, etc -- apply so long as the
antiderivatives in question are continuously differentiable on
${\mathbb C}$, or at least on $\gamma([a,b])$. However, we must use
caution that certain real functions with a "reputation" for continuity,
in particular $\ln(x)$ and $\sqrt[n]{x}$ have complex versions with
discontinuities along the negative real axis. They cannot be used as
antiderivatives if $\gamma([a,b])$ contains a negative real number.

::: { .example}
Let $\gamma:[0, 2\pi] \to {\mathbb C}$ be a "loop
around $a$ of radius $r$": $\gamma(t) = a+re^{it}$ ($r>0$), and let
$f(z) = \frac{1}{z-a}$. Then $\int_\gamma f(z) dz = 2\pi i$.
:::

::: {.proof}
Since $\gamma$ is smooth we use Theorem
@thm-path-integral-summary
$$\int_\gamma f = \int_0^{2\pi} f(\gamma(t))\gamma'(t) dt = \int_0^{2\pi} \frac{1}{a+re^{it}-a} ire^{it} dt = \int_0^{2\pi} i dt = 2\pi i$$ 
:::

There is much to learn from this simple example. First, notice that the
Fundamental Theorem would suggest the antiderivative $\ln(x-a)$ and the
answer $\ln(\gamma(2\pi)-a) - \ln(\gamma(0)-a) =
\ln((a+r)-a)-\ln((a+r)-a)=0$. Why is it wrong? Because $\ln(z-a)$ is
discontinuous (and therefore not an antiderivative!) when $z-a$ is a
negative real number, which occurs on the image of $\gamma$: In
particular $\gamma(\pi) = a-r$, so $\ln(\gamma(\pi))= \ln(-r)$. It's
important to remember the locus of discontinuity of $\ln(z)$!

Next, notice that the answer is independent of the radius $r$. A fast
path around a big circle and a slow path around a small circle yield the
same path integral. In a sense to be made precise later, the only thing
that matters here is that $\gamma$ winds once counterclockwise around
the point $z=a$. It could travel in a square or a trace a picture of
Olaf the Snowman and still yield $2\pi i$.

Finally, notice that the value $2\pi i$ of the integral is exactly the
size of the jump discontinuity of $\ln(z)$ at any negative real point.
If $\ln(z)$ could somehow take multiple values according to the context
of the integral, it could remain continuous and would yield $2\pi i$ by
the fundamental theorem, but of course a function can't do that. (Can
it?)

::: {#exr-integral-z-inverse-redux}
 In this exercise you'll calculate
$\int_\gamma \frac{1}{z} dz$ in two parts using the Fundamental Theorem
and both logarithms. Here for convenience
$\gamma:[-\pi/2,3\pi/2] \to {\mathbb C}$ by $\gamma(t) = e^{it}$. The
altered domain of $\gamma$ doesn't change the answer.

1.  Explain how we know that $f(z) = \frac{1}{z}$ has an antiderivative
    defined on ${\mathbb C}- (-\infty,0]$.
2.  Find an antiderivative for $f(z) = \frac{1}{z}$ defined on
    ${\mathbb C}- [0,\infty)$. (No need to prove correctness.)
3.  Let $\gamma:[-\pi/2,3\pi/2] \to {\mathbb C}$ by
    $\gamma(t) = e^{it}$. Describe the geometry of the path.
4.  Calculate $\int_\gamma \frac{1}{z} dz$ by dividing the integral into
    $\int_{-\pi/2}^{\pi/2} + \int_{\pi/2}^{3\pi/2}$ and using the
    fundamental theorem of calculus, twice.
5.  Deduce *from your previous answer* that $\frac{1}{z}$ cannot have an
    antiderivative on its entire domain.
:::

What if the point at which $f$ is undefined is not the center of the
circle? Everything works the same:

::: {.example}
Let $\gamma:[0, 2\pi] \to {\mathbb C}$ be a "loop
around $a$ of radius $r$": $\gamma(t) = a+re^{it}$ ($r>0$), and let
$f(z) = \frac{1}{z-b}$, with $b \in B(a,r)$. Then
$\int_\gamma f(z) dz = 2\pi i$.
:::

::: {.proof}
By the previous example, it suffices to show
$\int_\gamma \frac{1}{z-a} dz - \int_\gamma \frac{1}{z-b} dz =0$. It
suffices to find an antiderivative for $\frac{1}{z-a} - \frac{1}{z-b}$.
Now $\ln(z-a)-\ln(z-b)$ is not a good answer because each part may be
discontinuous. We have better luck with $\ln(\frac{z-a}{z-b})$, which
has different discontinuities. The value $\frac{z-a}{z-b}$ is negative
exactly when $z-a$ is a negative real multiple of $z-b$. As vectors,
$z-a$ and $z-b$ point in opposite directions, so $z$ is on the line
segment from $a$ to $b$. Therefore $\ln(\frac{z-a}{z-b})$ is
differentiable on the complement in ${\mathbb C}$ of this segment, and
the reader may check its derivative is indeed
$\frac{1}{z-a} - \frac{1}{z-b}$. This set includes $\gamma$, so the
fundamental theorem applies. 
:::

Notice that this proof does more than advertised: It works when $\gamma$
is any path at all disjoint from the line segment from $a$ to $b$,
telling us
$\int_\gamma \frac{1}{z-b} dz = \int_\gamma \frac{1}{z-a} dz$. This will
be useful later, but for now we can't calculate
$\int_\gamma \frac{1}{z-a} dz$ except for circular paths!

## Cauchy's Theorem

Early complex integration theory centers around two types of related
theorems. The first type asserts that $\int_\gamma f(z) dz = 0$ for a
differentiable function $f$ and a certain kind of path $\gamma$. We'll
prove several such theorems. Students should note that they differ not
in the strength of their conclusion, but in the generality of the path
$\gamma$ to which they apply. In a way, @thm-closed-path-primitive-zero-integral
begins this story, but
applies only when $f$ has a primitive. The second type asserts that if
$f$ is analytic, its values within a region may be predicted from its
values on the boundary of a region, if only one can compute the integral
of a related function, differentiable except at one point. Again we have
several versions of this theorem, differing chiefly in the paths and
regions used. We begin with our most specific zero-integral theorem.

::: {#thm-Cauchy-theorem-triangle .theorem}
**(Cauchy's Theorem -- triangle)**
Let $f$ be differentiable on a triangle
$T = \triangle ABC$. Then $\int_{dT} f(z) dz =0$
:::

::: {.proof}
Our strategy is Goursat's. Suppose the given integral were
nonzero. We describe a decomposition of the triangle into four pieces,
so that on at least one the integral is "still large." Continuing gives
a shrinking sequence of triangles, converging to some point $z_0$. Since
$f$ is differentiable at $z_0$, we use the tangent line approximation to
reduce to the error function $g$. The limit property of $g$, coupled
with the lower bound on $\int g dz$ will give a contradiction.

Let $T_0 = T = \triangle ABC$. Let
$C=\modulus{\int_{\partial T} f(z) dz}$. Let $p$ and $d$ be
the perimeter and diameter of $T$. Let $D$, $E$, and $F$ be the
midpoints of $BC$, $CA$, and $AB$ respectively. Then
$\partial \triangle ABC = \partial \triangle AFE + \partial \triangle FBD + \partial \triangle DEF + \partial \triangle EDC$.
For at least one of these, which we call $T_1$, we have
$|\int_{\partial T_1} f(z) dz| \geq C/4$. Continuing in this way gives
triangles $T_n$ so that $|\int_{\partial T_n} f(z) dz| \geq C/4^n$. Note
that $T_n$ has perimeter $P/2^n$ and diameter $d/2^n$. Let $z_0$ be the
point in $\bigcap T_n$ (by compactness).

Let $f = L + g$ be the linear approximation at $z_0$, with
$\lim_{w \to z_0} \frac{g(w)}{w-z_0} =0$. Since $L$ has a primitive,
$\int_{\partial T_n} f(z) dz = \int_{\partial T_n} g(z) dz$. For any
${\varepsilon}>0$, for $n$ sufficiently large we have for all
$w \in T_n$:
$\modulus{\frac{g(w)}{w-z_0}} < {\varepsilon}$,
so
$\modulus{g(w)} \leq {\varepsilon}\modulus{w-z_0} < {\varepsilon}d/2^n$.
By the ML-inequality,
$$\modulus{\int_{\partial T_n} f(z) dz} = \modulus{\int_{\partial T_n} g(z) dz} \leq {\varepsilon}d/2^n P/2^n = \frac{{\varepsilon}d P}{4^n}$$
For ${\varepsilon}$ sufficiently small, this is inconsistent
with the lower bound $C/4^n$ above. 
:::



Since the property $\int_{dT} f(z) dz =0$ applies only to triangle
paths, it may seem too specialized to be useful. But it forces $f$ to
have a primitive, as the next theorem shows.

::: {.definition}
For any $z_1, z_2 \in {\mathbb C}$ we write
$[z_1,z_2]$ for the path $\gamma:[0,1] \to {\mathbb C}$ by
$\gamma(t) = z_1 + t(z_2-z_1)$.
:::

::: {#thm-triangle-closed-exact .theorem}
Let $f$ be continuous on a convex set $D$. If for any
triangle $T = \triangle ABC$ in $D$ we have $\int_{d T}f(z) dz=0$, then
$f$ has a primitive $f=F'$.
:::

::: {.proof}
Fix $A \in D$, and let $F(B) = \int_{[A,B]}f(z) dz$. Now fix
$B \in D$. Using triangle $\triangle ABC$ we calculate
$\displaystyle \frac{F(C)-F(B)}{C-B} = \frac{\int_{[A,C]}f(z) dz - \int_{[A ,B]}f(z) dz}{C-B} = \frac{\int_{[B,C]}f(z) dz}{C-B}$.
To show $F'(B)=f(B)$, we must prove
$\displaystyle\lim_{C \to B}\frac{\int_{[B,C]}f(z) dz}{C-B} = f(B)$.
Since obviously
$\displaystyle\lim_{C \to B}\frac{\int_{[B,C]}f(B) dz}{C-B} = f(B)$ it
suffices to show
$\displaystyle\lim_{C \to B}\frac{\int_{[B,C]}(f(z)-f(B)) dz}{C-B} = 0$.
The last is a simple application of the continuity of $f$ at $B$ and the
ML inequality. 
:::



This brings us to our first version of Cauchy's theorem:

::: {#thm-Cauchys-theorem-convex .theorem}
**(Cauchy's Theorem on a Convex Domain)** Let $f$ be
differentiable on a convex set $D$. Then $f$ has a primitive on $D$ and
$\int_\gamma f=0$ for any closed path in $D$.*
:::

::: {.proof}
Assemble @thm-Cauchy-theorem-triangle, @thm-triangle-closed-exact, and @thm-closed-path-primitive-zero-integral
:::

The integral $\int_\gamma f(z) dz$ of a differentiable function around a
loop in a convex domain is zero. Under the right conditions, it follows
that $\int_\gamma f(z) dz = \int_\sigma f(z) dz$ if $f$ is
differentiable on the region "between" the loops:

::: {.theorem}
Let $z \in B(z,r) \subseteq B(z_0,R)$, with boundary
paths $\gamma(t) = z_0+Re^{it}$ and $\sigma(t) = 
z+re^{it}$. If $f$ is differentiable on $\overline{B(z_0,R)} - z$,
then 
$$\int_\gamma f(z) dz = \int_\sigma f(z) dz$$
:::

::: {.proof}
Disassemble the irregular annulus into three sections,
producing three paths whose sum is $\gamma-\sigma$, each of which is
contained in a convex set where $f$ is differentiable. 
:::



According to the previous theorem, if $f$ is differentiable on a convex
domain *except* at $z$, then a wide variety of loops $\gamma$ around $z$
all produce the same integral value $\int_\gamma f(w) dw$. The next
theorem explains how to use the behavior of $f$ on a neighborhood of $z$
to predict the common value of these integrals.

This suggests that $\int_\gamma f(w) dw$ can be calculated by replacing
$\gamma$ with a very small loop $\sigma$ with the same center $z_0$. One
might hope to approximate:

$$\int_\gamma f(w) dw = \int_\sigma f(w) dw = \int_\sigma \frac{f(w)(w-z_0)}{w-z_0} dz \approx \int_\sigma \frac{L}{w-z_0} dz = 2\pi i L$$ 
where $L$ is the limit of the term it replaces and the
approximation is driven by the smallness of $\sigma$. The next theorem
makes this idea precise.

::: {.theorem}
Let $f$ be differentiable on
$\overline{B(z_0,R)} - z_0$. Let $\gamma(t) = z_0+Re^{it}$ be the boundary
path. Then 
$$\int_\gamma f(w) dw = 2\pi i \lim_{w \to z_0} f(w)(w-z_0)$$
provided the limit exists.
:::

::: {.proof}
Let $L= \lim_{w \to z_0} f(w)(w-z_0)$. Let
${\varepsilon}>0$ and choose $r$ so that for all
$w \in \overline{B(z_0,r)}$ we have
$\modulus{f(w)(w-z_0) - L} < {\varepsilon}$. By
the previous theorem, we may replace $\gamma$ with any path
$\sigma(t) = 
    z_0+re^{it}$ of small radius around $z_0$. We know that
$\int_\sigma \frac{L}{w-z_0} dw = 2\pi i L$, so we calculate the
difference: 
\begin{align}
\modulus{\int_\sigma f(w) dw - 2\pi i L} =& 
    \modulus{ \int_\sigma f(w) dw - \int_\sigma \frac{L}{w-z_0} dw }\\ 
    =& \modulus{ \int_\sigma \left( f(w)-\frac{L}{w-z_0} \right) dw }\\
    =& \modulus{\int_\sigma \left( \frac{f(w)(w-z_0)-L}{w-z_0} \right) dw}\\
    \leq & \frac{{\varepsilon}}{r} 2\pi r = 2\pi {\varepsilon}&\text{By the ML inequality}
\end{align} 
Since this can be made arbitrarily small by choice of $\sigma$, we have equality. 
:::



::: {#exr-integrals-zn-sinz}
 Let $\gamma:[0,2\pi] \to {\mathbb C}$ by
$\gamma(t) = e^{it}$. Calculate $$\int_\gamma z^n \sin(z) dz$$ for every
integer $n$. Hints: The answers are not all equal. There is not need to
integrate by parts.
:::

::: {#thm-Cauchy-integral-formula-disk .theorem}
**(Cauchy's Integral Formula for the Disk)** 
Let $f$ be differentiable on $\overline{B(z_0,R)}$. 
Let $\gamma(t) = z_0+Re^{it}$
be the boundary path. Then
$$f(z) = \frac{1}{2\pi i }\int_\gamma \frac{f(w)}{w-z} dw$$
:::

::: {.proof}
The work is done in the previous theorem. We need only
calculate
$$\frac{1}{2\pi i }\int_\gamma \frac{f(w)}{w-z} dw = \frac{1}{2\pi i } 2 \pi i \lim_{w \to z} \frac{f(w)}{w-z} (w-z) = f(z)$$ 
:::

At first glance, the Cauchy Integral Formula looks like a method of
evaluating a rather unlikely integral, but it is much more. It gives a
formula for $f(z)$ for any $z \in B(z_0,R)$ in terms of the values of
$f$ on the circle. It not only demonstrates that any differentiable
function on $D$ is entirely determined by its boundary values, but gives
an explicit method for performing such a calculation.

To illustrate its power, we will next show how it can be used to produce
a power series for any differentiable function. We first need a lemma
helping us pass an integral across a limit or sum:



::: {.lemma}
Let $X \subseteq {\mathbb C}$ and let $f_n$ be a
sequence of functions converging uniformly to $f$ on $X$, and let
$\gamma$ be a path of bounded variation $v(\gamma)<\infty$ in $X$. Then
$$\lim_{n \to \infty} \int_\gamma f_n(z) dz = \int_\gamma f(z) dz$$ 
If
instead $f(z) = \sum_{n=0}^\infty f_n(z)$, with uniform convergence on
$X$, then
$$\sum_{n=0}^\infty \int_\gamma f_n(z) dz = \int_\gamma f(z) dz$$
:::



::: {.proof}
For the first claim, let ${\varepsilon}>0$ and
choose $N$ so that for $n>N$ we have
$\modulus{f_n(z)-f(z)}<{\varepsilon}/v(\gamma)$
*uniformly* on $X$. Then
$$\modulus{\int_\gamma f_n(z) dz - \int_\gamma f(z) dz} = \modulus{\int_\gamma f_n(z)-f(z) dz} \leq \frac{{\varepsilon}}{v(\gamma)} v(\gamma) = {\varepsilon}$$
The second claim follows from the first since integrals commute with
finite sums. 
:::



::: {#thm-differentiable-analytic .theorem}
Let $f$ be differentiable on $\overline{B(z_0,R)}$.
Then $f$ has a power series expansion
$$f(z) = \sum_{n=0}^\infty a_n (z-z_0)^n$$ 
with coefficients
$$a_n = \frac{1}{2\pi i } \int_\gamma \frac{f(w)}{(w-z_0)^{n+1}} dw$$
and radius of convergence at least $R$.
:::



::: {.proof}
We begin with a geometric series for $\frac{1}{w-z}$, centered
at $z_0$:
$$\frac{1}{w-z} = \frac{1}{(w-z_0) - (z-z_0)} = \frac{1}{w-z_0} \cdot \frac{1}{1-\frac{z-z_0}{w-z_0}} =  \frac{1}{w-z_0} \cdot \sum_{n=0}^\infty \left(\frac{z-z_0}{w-z_0}\right)^n$$
For fixed $z \in B(z_0,R)$ and all $w$ on the boundary,
$\modulus{\frac{z-z_0}{w-z_0}}<1$ is constant in $w$, so we
have uniformly convergence 
\begin{align}
 f(z) =  \frac{1}{2\pi i }\int_\gamma \frac{f(w)}{w-z} dw 
    =& \frac{1}{2\pi i }\int_\gamma f(w) \frac{1}{w-z_0} \cdot \sum_{n=0}^\infty \left(\frac{z-z_0}{w-z_0}\right)^n dw\\
    =& \sum_{n=0}^\infty (z-z_0)^n \frac{1}{2\pi i } \int_\gamma \frac{f(w)}{(w-z_0)^{n+1}} dw\\
\end{align}
:::

This theorem sets complex analysis apart from real analysis more clearly
than any other. For real functions the conditions of differentiability,
continuous differentiability, twice differentiability, infinite
differentiability, etc. are all distinguishable, but this theorem tells
us that differentiability on an open set gives us infinite
differentiability. It is of course a powerful tool, and we will now see
major theorems begin to fall like dominoes.

::: {#thm-zero-power-series-constant .theorem}
Let $f$ be differentiable on an open set $U$, and let
$a \in U$. If $\forall n \enspace f^{(n)}(a)=0$, then $f$ is constantly
zero on a neighborhood of $a$. Moreover the set $S$ of points $a$ for
which $\forall n \enspace f^{(n)}(a)=0$ is clopen. If $U$ is connected
and any such point exists, then $f=0$ on $U$.
:::

::: {.proof}
Since $f$ is differentiable on a neighborhood of $a$, it has a
convergent power series with nonzero radius of convergence. Its
coefficients $f^{(n)}(a)/n!$ are all zero, so $f=0$ on an open
neighborhood $B(a,r)$ of $a$. Furthermore the power series for $f$ at
any point $b \in B(a,r)$ is clearly zero as well. This proves that $S$
is open. Since $S$ is the intersection of preimages
$(f^{(n)})^{-1}(\{0\})$ of closed sets under continuous maps, $S$ is
closed. 
:::

::: {#thm-Moreras-theorem .theorem}
**(Morera's Theorem)** Let $V \subset {\mathbb C}$ be
open, and let $f$ be continuous on $V$. If $\int_{\partial T} f(z) dz=0$
for any triangle $T \subset V$ then $f$ is infinitely differentiable.
:::

::: {.proof}
On any (convex!) ball $B(z_0,R) \subseteq V$, $f$ has a
primitive $F$, and $F'=f$. Since $F$ has a power series, it is twice (in
fact infinitely) differentiable, so $f$ is differentiable
(infinitely). 
:::

::: {#thm-Cauchy-estimates .theorem}
**(Cauchy's Estimates)** Let $f$ be differentiable on
$\overline{B(z_0,R)}$, and assume $|f(z)|\leq M$ on the boundary. Then
$\modulus{f^{(n)}(z_0)} \leq \frac{Mn!}{R^n}$.*
:::

::: {.proof}
From the power series expansion @thm-differentiable-analytic, we know
$\modulus{f^{(n)}(z_0)} = \modulus{n!\frac{1}{2\pi i } \int_\gamma \frac{f(w)}{(w-z_0)^{n+1}} dw}$.
The ML-inequality bounds the integral by
$n! \frac{1}{2\pi} \frac{M}{R^{(n+1)}} 2 \pi R = \frac{Mn!}{R^n}$. 
:::

::: {.definition}
A function $f:{\mathbb C}\to {\mathbb C}$ is called
**entire** if it is defined and differentiable on all of ${\mathbb C}$.
:::

::: {#thm-Liouville .theorem}
**(Liouville's Theorem)** Any bounded entire function is
constant.
:::

::: {.proof}
Assume $\modulus{f(z)} \leq M$ for all $z$. Fix
$z_0 \in {\mathbb C}$. Then $\modulus{f'(z_0)} \leq M/R$,
for all $R$, so $f'(z_0)=0$. Since $f$ has constant zero derivative (and
${\mathbb C}$ is connected), $f$ is constant. 
:::

Our next theorem is taught even in high school. It 
is an old joke that the Fundamental Theorem of Algebra is neither
fundamental, nor a theorem of algebra.

::: {#thm-fundamental-theorem-algebra .theorem}
**(Fundamental Theorem of Algebra)** Let $P(x) \in {\mathbb C}[x]$ be a nonconstant polynomial with complex coefficients. Then $P$ has a root in ${\mathbb C}$.
:::

::: {.proof}
Certainly $P(z)$ is entire. If $P(z)$ has no root, then
$1/P(z)$ is also entire. Let $a_nz^n$ be the leading coefficient. Now
$\modulus{P(z)} = \modulus{z^n}\modulus{a_n + a_{n-1}z^{-1} + \ldots + a_0z^{-n}} \geq \modulus{z^n}(\modulus{a_n} - \modulus{a_{n-1}z^{-1}} - \ldots - \modulus{a_{0}z^{-n}})$.
Whenever $|z| \geq R = 2n\max(a_i/a_n,1)$, we continue
$P(x) \geq \modulus{z^n}\left(\modulus{a_n} - \frac{\modulus{a_{n-1}a_n}}{2na_{n-1}} - \ldots - \frac{\modulus{a_{0}a_n}}{2na_0} \right) = \modulus{z^n}\modulus{\frac{a_n}{2}} \geq \modulus{\frac{a_n}{2}}$.
Thus when $z \geq R$ we have
$|\frac1{P(z)}| \leq \modulus{\frac{2}{a_n}}$. On the other
hand, $\frac{1}{P(z)}$ is bounded on $\overline{B(z,R)}$ by continuity
(if $P(z)$ has no roots) and compactness. Thus $\frac{1}{P(z)}$ is
constant and so is $P(z)$. 
:::

Our next formula can be interpreted as a generalized Pythagorean
theorem. It is also significant in Fourier analysis, where it says that
the energy in a waveform $f$ is the sum of the energies represented in
each fourier component.

::: {#thm-Parsevals-formula .theorem}
**(Parseval's Formula)** Let
$f(z) = \sum_{n=0}^\infty a_n(z-a)^n$ be a power series with radius of
convergence $R$, and let $r<R$. Then
$$\frac{1}{2\pi} \int_0^{2\pi} \modulus{f(a+re^{it})}^2 dt = \sum_{n=0}^\infty \modulus{a_nr^n}^2$$
:::

Notice the connection with Fourier series:
$f(a+re^{it}) = \sum_{n=0}^\infty a_n(re^{it})^n = 
\sum_{n=0}^\infty a_nr^ne^{int} =\sum_{n=0}^\infty a_nr^n (\cos(nt) + i \sin(nt))$,
a Fourier series with coefficients $a_nr^n$.

::: {.proof}
Consider the inner product
$\innerprod{f,g} \equiv_\text{def} \frac{1}{2\pi}\int_0^{2\pi} f(t)\overline{g(t)}dt$
and functions $b_n(t) = e^{int}$ for $n \in {\mathbb N}$. Now
$\int_0^{2\pi} e^{int} dt= \left.\frac{1}{in} e^{int}\right\vert_0^{2\pi}=0$
unless $n=0$, when $\int_0^{2\pi} e^{int} dt = 2\pi$. It follows that
$\innerprod{b_m,b_n} = 1$ if $m=n$ and $0$
otherwise. The power series expresses $f(a+re^{it})$ in terms of this
basis:
$f(a+re^{it}) = \sum_{n=0}^\infty a_n(re^{it})^n = \sum_{n=0}^\infty a_nr^n b_n(t)= \lim s_N$,
where $s_N(t) =\sum_{n=0}^N a_nr^n b_n(t)$. Now the convergence
$s_N \to f$ is uniform on $\overline{B(a,r)}$ since $r<R$, and the same
is true of
$\modulus{s_N}^2 \to \modulus{f}^2$. Therefore
\begin{align}
    \frac{1}{2\pi} \int_0^{2\pi} \modulus{f(a+re^{it})}^2 dt 
    =& \lim_{N \to \infty}  \frac{1}{2\pi} \int_0^{2\pi} \modulus{s_N(t)}^2 dt\\
    =& \lim_{N \to \infty}\frac{1}{2\pi} \int_0^{2\pi} s_N(t)\overline{s_N(t)} dt \\
    =& \lim_{N \to \infty} \frac{1}{2\pi} \int_0^{2\pi} \sum_{m=0}^N a_mr^m b_m(t)\overline{\sum_{n=0}^N a_nr^n b_n(t)} dt \\
    =& \lim_{N \to \infty} \frac{1}{2\pi}  \sum_{m=0}^N \sum_{n=0}^N \int_0^{2\pi} a_mr^m b_m(t)\overline{ a_nr^n b_n(t)} dt \\
    =& \lim_{N \to \infty} \frac{1}{2\pi} \sum_{n=0}^N \modulus{a_nr^n}^2  = \frac{1}{2\pi} \sum_{n=0}^\infty \modulus{a_nr^n}^2 \text{ as desired.}\\
\end{align}
:::

::: {#thm-maximum-modulus .theorem}
**(Maximum Modulus Theorem)** Let $f$ be differentiable
and nonconstant on a connected open set $U$. Then
$\modulus{f}$ does not achieve a local maximum on $U$.
:::

::: {.proof}
Let $a \in U$. On some ball $B(a,R)$ we have a convergent power
series $f(z) = \sum_{n=0}^\infty a_n(z-a)^n$, and for some smaller ball
$B(a,r)$, Parceval's formula holds. For some $n>0$ we have $a_n \neq 0$
by @thm-zero-power-series-constant. Suppose
$\modulus{f(a+re^{it})} \leq \modulus{f(a)}$
for all $t$. Then
$$|f(a)|^2 = \modulus{a_0}^2 <  \sum_{n=0}^\infty \modulus{a_nr^n}^2 = \frac{1}{2\pi} \int_0^{2\pi} \modulus{f(a+re^{it})}^2 dt \leq \frac{1}{2\pi} 2\pi \modulus{f(a)}^2 =\modulus{f(a)}^2$$
by @thm-Parsevals-formula and the @thm-ML-inequality. 
This contradiction shows $a$ cannot be a
local maximum of $\modulus{f(z)}$. 
:::

If we consider a compact domain, such as $\overline{B(0,R)}$, then of
course $\modulus{f}$ attains a maximum value. The Maximum
Modulus Theorem guarantees that it occurs on the boundary.

## General Cauchy Integral Theorem

The theorems of the previous section testify to the strength of @thm-Cauchy-integral-formula-disk. In this section we will develop 
a version for more general
paths $\gamma$. We follow Dixon's approach.

Throughout this section, let $\gamma:[\alpha,\beta] \to {\mathbb C}$ be
a path. We assume $\gamma$ is continuous, and bounded variation (for
example, piecewise smooth). Fix $a$ and consider
$\int_{\gamma} \frac{1}{w-a} dw$. Naively we may wish to calculate
$\int_{\gamma} \frac{1}{w-a} dw = \log(\gamma(\beta))-\log(\gamma(\alpha)) = 0$,
but of course this is wrong even for the circular path
$\gamma = z+e^{it}$, because $\log(w-a)$ is not an antiderivative of
$1/(w-a)$ when $w-a\in (-\infty,0]$. The next proposition assures us
that this wrong calculation is, at worst, off by a multiple of $2\pi i$.

::: {.proposition}
Let $a \in {\mathbb C}$. Let
$\gamma:[\alpha,\beta] \to {\mathbb C}- \{a\}$. Then
$$\int_{\gamma} \frac{1}{w-a} dw = \log(\gamma(\beta))-\log(\gamma(\alpha)) + 2 \pi i n$$
for some $n \in {\mathbb Z}$.*
:::

::: {.proof}
We consider $x \in [\alpha,\beta]$. Let $X$ be the set of all
$x \in [\alpha,\beta]$ for which the theorem is true for
$\gamma\rvert_{[\alpha,x]}$. Now fix $x_1$. Let $\gamma(x_1) = z_1$. If
$z_1-a$ is not a negative real, choose ${\varepsilon}>0$ so
that $\log(w-a)$ is continuous on $B(z_1, {\varepsilon})$ and
$\delta>0$ so that
$\gamma(B(x_1,\delta)) \subseteq B(z_1, {\varepsilon})$. Let
$x_2 \in B(x_1,\delta)$. Let $\gamma_1 = \gamma\rvert_{[\alpha,x_1]}$,
$\gamma_2 = \gamma\rvert_{[\alpha,x_2]}$, and
$\gamma_\Delta = \gamma\rvert_{[x_1,x_2]}$, so
$\int_{\gamma_2} = \int_{\gamma_1} +\int_{\gamma_\Delta}$ Now $\log$ is
an antiderivative for the integral
$\int_{\gamma_\Delta} \frac{1}{w-a} dz = \log(\gamma(x_2)) - \log(\gamma(x_1))$.
Thus the theorem statement is true for $x_1$ if and only if it is true
for $x_2$.

Now if $z_1-a$ is a negative real, consider the function
$\log'(z) = \ln(\modulus{z}) + i \arg'(z)$, where
$\arg'(z) \in [0,2\pi)$. Then $\log'(z) - \log(z) \in \{0, 2\pi i \}$.
Moreover, $\log'(w-a)$ is an antiderivative of $\frac{1}{w-a}$ unless
$w-a$ is a *positive* real. Using $\log'$ in place of $\log$, the above
argument goes through again.

We conclude that $x_1 \in X$ iff $x_2 \in X$. This shows that $X$ is
both open and closed. Since $\alpha \in X$, we deduce $\beta \in X$ as
desired. 
:::

In the case of a closed curve $\gamma$,
$\log(\gamma(\beta))-\log(\gamma(\alpha))=0$. The number $n$ simply
counts the number of times $\gamma$ winds around $z$ in the
counterclockwise direction. We cannot assert this as a theorem without
the algebraic topology to define "winds", so instead we take it as a
definition:

::: {.definition}
Let $a \in {\mathbb C}$. Let
$\gamma:[\alpha,\beta] \to {\mathbb C}- \{a\}$, $v(\gamma)<\infty$. The
**Winding number** of $\gamma$ around $a$ is:
$$n(\gamma, a) \equiv_{def} \frac{1}{2\pi i} \int_{\gamma} \frac{1}{w-a} dw$$
:::

::: {.proposition}
For fixed $\gamma$ with $v(\gamma)<\infty$, the
winding number $W(\gamma,z)$ is a locally constant function of
$z \in {\mathbb C}- im(\gamma)$.
:::

::: {.proof}
This is essentially a continuity argument. Fix
$z \notin im(\gamma)$. Since $\gamma$ is continuous, $im(\gamma)$ is
compact, so closed. Let $B(z,{\varepsilon}_1)$ be disjoint
from $\gamma$, and consider
${\varepsilon}_2<{\varepsilon}_1$ to be decided.
Let $z' \in B(z,{\varepsilon}_1)$. Then
$$W(\gamma,z) - W(\gamma,z') = \frac{1}{2\pi i}\int_{\gamma} \frac{1}{w-z}- \frac{1}{w-z'} dw = \frac{1}{2\pi i}\int_{\gamma} \frac{z-z'}{(w-z)(w-z')}dw$$
This integral can be bounded above (ML inequality) by
$\frac{v(\gamma) {\varepsilon}_2}{2\pi {\varepsilon}_1^2}$.
For sufficiently small
${\varepsilon}_2<{\varepsilon}_1$, this is less
than $1$, so the $W(\gamma,z) - W(\gamma,z') =0$ as desired. 
:::

Here's another proof, arguably a better proof:

::: {.proof}
It suffices to show that $\int_{\gamma} \frac{1}{w-z} dw$ is a
locally constant function of $z$, so let
$z, z' \in B(z, {\varepsilon})$, where
$B(z,{\varepsilon})$ lies in one component of
${\mathbb C}- \{\gamma\}$. Then
$$\int_{\gamma} \frac{1}{w-z} dw - \int_{\gamma} \frac{1}{w-z'} dw = \int_{\gamma} \frac{1}{w-z}-\frac{1}{w-z'} dw$$
As we've proved earlier, this integrand has an antiderivative
$\log\left(\frac{w-z}{w-z'} \right)$ everywhere except the line segment
connecting $z$ to $z'$. By the fundamental theorem of calculus, the
integral is zero. 
:::

We take for granted that the complement of a path
${\mathbb C}- im(\gamma)$ has exactly one unbounded component. A path
$\gamma$ can't wind around a point in that component. This is obvious
geometrically, but not from our integral definition.

::: {#thm-unbounded-component-no-winding .prop}
If $\gamma: [\alpha,\beta] \to {\mathbb C}$, with
$v(\gamma)<\infty$. Let $z$ be in the unbounded component of
${\mathbb C}-im(\gamma)$. Then $W(\gamma,z)=0$.
:::

::: {.proof}
By local constancy, $W(\gamma,z)$ is constant on the component
of interest. When $z$ is sufficiently far from $im(\gamma)$, (distance
$\geq M$, say) we have $\modulus{\frac{1}{w-z}} < 1/M$, so
$\modulus{W(\gamma,z)} \leq \frac{v(\gamma)}{2\pi M}$. For
$M$ sufficiently large, this is close to $0$, so equal to $0$. Since
$W(\gamma,z)$ is constant for such $z$, $W(\gamma,z)=0$ for all $z$ in
the component. 
:::

## Singularities

We turn our attention to **singularities** of a function $f$ -- points
where $f$ fails to be defined. Properties of singularities $z_0$ depend
not on $f(z_0)$, which does not exist, but on $f(z)$ for $z$ nearby
$z_0$.

::: {.definition}
**Definition 5.25**. Let $z_0 \in {\mathbb C}$.

1.  A **deleted neighborhood** of $z_0$ is a set of the form
    $U-\{z_0\}$, where $z_0 \in U$ and $U$ is open.

2.  A **singularity** of a function $f$ is a point $z_0$ so that
    $f(z_0)$ is analytic on a deleted neighborhood of $z_0$ but
    undefined or not analytic at $z_0$.

3.  If $z_0 \in {\mathbb C}$, the phrase **near $z_0$** means "on some
    deleted neighborhood of $z_0$. For example, "$f$ is constant near
    $z_0$" means there is some open set $U \ni z$ for which
    $f|_{U -\{z_0\}}$ is constant.
:::

Notice that by definition a singularity $a$ is isolated in the sense
that some neighborhood of $a$ has no singularities.

::: {.example}
Some common singularities.

1.  The function $$f(z) = \frac{e^z}{(z-3)^2}$$ is undefined at $z_0=3$.
    As $z$ approaches $3$, the numerator approaches $e^3 \approx 20.1$
    and the denominator approaches $0$, so the fraction is unbounded.
    Thus, there is no value which can be assigned to $f(3)$ which makes
    it continuous at $3$. We call this singularity a **pole of order
    2**.

2.  The function $$g(z) = \frac{z^2-9}{(z-3)}$$ is undefined at $z_0=3$.
    For all $z \neq z_0$, we have $g(z) = z+3$. We call this singularity
    **removable** because the function can be assigned a value at $z_0$
    which repairs the problem.

3.  The function $$h(z) = \frac{(z-3)^2(z-4)^2}{(z-3)}$$ is undefined at
    $z_0=3$. Again we can cancel, removing the singularity. In this case
    the resulting function has a root at $3$.

4.  The function $$k(z) = e^{1/z}$$ is undefined at $z_0=0$. As $z$
    approaches $z_0=0$, the exponent goes to infinity. Because *the
    exponent* goes to infinity, the function $k(z)$ goes to infinity
    very quickly and has some strange properties. This is an example of
    an **essential** singularity.
:::

::: {.definition}
Let $f$ have a singularity at $z_0$. If there is
some value $w$ such that the function
$$\hat{f}(z) = \begin{cases} f(z) & z \neq z_0 \\ w & z = z_0 \end{cases}$$

is analytic at $z_0$, we call $z_0$ a **removable** singularity of $f$.
:::

::: {.theorem}
**(Riemann Continuation Theorem)** If $z_0$ is a
singularity of $f$ and $f$ is bounded near $z_0$, then $z_0$ is
removable.
:::

::: {.proof}
$$\text{Let } g(z) = \begin{cases} f(z)(z-a)^2 & z \neq a\\ 0 & z=0 \end{cases}$$
If $z \neq z_0$ then $g'(z)$ can be calculated by the product rule.
$g'(z_0) = \lim_{z \to z_0} f(z)(z-z_0) = 0$ since $z-z_0 \to 0$ and
$f(z)$ is bounded near $z_0$. It follows that $g$ has a power series
expansion $g(z) = \sum_{n=0}^\infty a_n(z-z_0)^n$, and $a_0=a_1=0$. We
may divide by $(z-z_0)^2$ termwise to find a power series expansion for
$f(z)$ centered at $a$. 
:::

The Riemann Continuation Theorem means that complex function theory has
nothing like the "jump discontinuities" from ordinary real Calculus.

Roots and Poles should be understood as opposites, but first we need to
understand functions which have neither:

::: {.proposition}
Let $g$ be analytic on a neighborhood of $z_0$.
(So $z_0$ is not a singularity of $g$.) Then the following are
equivalent:

1.  $g(z_0) \neq 0$

2.  $1/g$ is analytic on some (possibly smaller) neighborhood of $z_0$

3.  The power series expansion of $g$ at $z_0$ is of the form
    $g(z) = \sum_{n=0}^\infty a_n(z-z_0)^n$ with $a_0 \neq 0$.
:::

::: {.proof}
From prior work, $f$ has a power series expansion with positive
radius of convergence, and $f(z_0) = a_0$. Thus $1 \leftrightarrow 3$
follows. Moreover $2 \to 1$ is obvious. For $1 \to 2$, note that $f$ is
nonzero on some neighborhood $z_0$ by continuity, and on this
neighborhood $1/f$ is analytic by the quotient rule. 
:::

::: {.definition}
Let $f$ be analytic on a neighborhood of $z_0$. If
$f(z) = (z-z_0)^kg(z)$ (for positive integer $k$) and $g(z_0) \neq 0$,
we call $z_0$ a **root of order $k$** of $f$.
:::

::: {.definition}
Let $f$ be analytic near $z_0$. If
$f(z) = (z-z_0)^{-k}g(z)$ (for positive integer $k$) and
$g(z_0) \neq 0$, we call $z_0$ a **pole of order $k$** of $f$.
:::

::: {.definition}
Let $f$ be analytic near $z_0$. The **valuation**
$v_{z_0}(f)$ of $f$ at $z_0$ is defined to be
$$v_{z_0}(f) = \begin{cases} 0 &  \text{$f$ if analytic at $z_0$ and $f(z_0) \neq 0$}\\ k &  \text{$f$ has a root of order $k$ at $z_0$.}\\ -k &  \text{$f$ has a pole of order $k$ at $z_0$.}\\ \infty &  \text{$f=0$ on a neighborhood of $z_0$.}\\ \text{(undefined)} & \text{otherwise} \end{cases}$$
:::

::: {.proposition}
Let $f$ be analytic near $z_0$.

1.  If $f$ has a root of order $k$ at $z_0$ then $f$ has power series
    expansion at $z_0$: $$f(z) = \sum_{n=0}^\infty a_n(z-z_0)^n$$ and
    $a_k \neq 0$ is the first nonzero coefficient.

2.  If $f$ has a pole of order $k$ at $z_0$ then near $z_0$, $f$ can be
    written $$f(z) = \sum_{n=-k}^\infty a_n(z-z_0)^n$$ and
    $a_{-k} \neq 0$. This is called the **Laurent Series Expansion** of
    $f$ at $z_0$.

3.  If $f$ has a root (pole) of order $k$ at $z_0$ then $1/f$ has a
    pole (root) of order $k$ at $z_0$

4.  $v_{z_0}(f)$ is the index of the first nonzero term in the Laurent
    (or power) series expansion of $f$.

5.  $v_{z_0}(fg) = v_{z_0}(f) v_{z_0}(g)$ if the right hand side is
    defined.
:::

::: {.proof}
Directly from the definitions, using properties of $g$ proved
above. 
:::

Just as locally bounded functions must have removable singularities,
functions which become locally bounded when multiplied by $(z-z_0)^k$
must have poles:

::: {.proposition}
If $f$ is not bounded near $a$, but
$f(z)(z-z_0)^k$ is bounded near $z_0$ for some $k$, and if $k$ is
minimal with this property, then $f$ has a pole of order $k$ at $z_0$.
:::

::: {.proof}
After multiplying by $(z-z_0)^k$ we may invoke the Riemann
Continuation theorem. Subsequently dividing by $(z-z_0)^k$ we get a
Laurent series whose first nonzero term is $a_{-k}(z-z_0)^{-k}$, which
indicates a pole of order $k$. The coefficient $a_{-k}$ is nonzero by
the minimality of $k$. 
:::

::: {.definition}
Let $U \subset {\mathbb C}$ be open. A
**meromorphic function on $U$** is a function $f$ analytic on $U$ except
on a set of points where $f$ has poles. (Of course $f$ may also have
zeroes.) The set of all meromorphic functions on $U$ is written
${\mathcal M}(U)$.
:::

::: {.proposition}
Let $U \subset {\mathbb C}$ be open. Then
${\mathcal M}(U)$ is a field under function addition and
multiplication.
:::

::: {.proof}
We know that function addition and multiplication obey the
field axioms. The point of the proposition is to identify additive and
multiplicative identities and prove that if $f$ and $g$ are meromorphic,
then so are $-f$, $f+g$, $fg$. Also, if $g \neq 0$ then $1/g$ must be
meromorphic. Each part makes a nice exercise. Work locally at each
singularity $z_0$. 
:::

We have described functions bounded near $z_0$, which have removable
singularities. We have described functions that become bounded only when
multiplied by $(z-z_0)^k$, which have poles. The next theorem addresses
the only other case. It describes the most exotic type of singularity.

::: {.theorem}
**(Casorati-Weierstrass)** If $f(z)(z-z_0)^n$ is not
bounded near $z_0$ for any $n$, then
$f(B(z_0,{\varepsilon}))$ is dense in ${\mathbb C}$ for every
${\varepsilon}>0$. In this case we say that $f$ has an
**essential singularity.**
:::

::: {.proof}
If $f(B(z_0,{\varepsilon})-\{z_0\})$ is not dense,
choose an open ball $B(b, \delta)$ disjoint from its image. Then the
function $g(z) = \frac{1}{f(z)-b}$ is analytic and nonzero on
$B(z_0,{\varepsilon}) - \{z_0\}$ and bounded above by
$1/\delta$. Since $g$ is bounded it may be continued to $z_0$ (so we
assume $g(z_0)$ exists). Solving for $f$ gives:
$$f(z) = \frac{1}{g(z)} + b$$ 
Thus $f$ is meromorphic on some
neighborhood of $B(z_0, {\varepsilon})$. It follows that
$f(z)(z-z_0)^n$ is bounded near $z_0$ for some $n$. This proves (the
contrapositive of) the claim. 
:::

### Generalized Cauchy Integral Formula

::: {.lemma}
Let $g(z,w)$ be a continuous function of $z$ and $w$ on
a domain $U \times V$, analytic in $z$ for each $w$. Assume $U$ is open
and $V$ is locally compact. Then the partial derivative function
$\frac{\partial}{\partial z} g(z,w) = g_z(z,w)$ is likewise a continuous
function of two variables. (and of course analytic in $z$)
:::

::: {.proof}
Fix $z_0$ and $w_0$.

Case 1: Assume $g(z_0,w_0) = g_z(z_0,w_0)=0$. By the definition of $g_z$
we have $\lim_{z \to z_0} \frac{g(z,w_0)}{z-z_0}=0$. Let
${\varepsilon}>0$ and choose $r$ so that
$\overline{B(z_0,2r)} \subseteq U$ and whenever
$\modulus{z-z_0} \leq 2r$ then
$\modulus{\frac{g(z,w_0)}{z-z_0}}<{\varepsilon}/2$.
Thus on $B(z_0,2r) \times \{w_0\}$ we have
$|g(z,w)| < r{\varepsilon}/2$ Notice that Cauchy's bound for
$f'(z)$ says
$\modulus{g_z(z_0,w_0)} \leq \frac{\frac{r{\varepsilon}}{2} 1!}{r} = {\varepsilon}/2$,
which of course we already knew. We wish to extend this bound to a
neighborhood of $(z_0,w_0)$. On the compact region
$\overline{B(z_0,2r)} \times \overline{B(w_0,r)}$ choose $\delta>0$
(with also $\delta<r$) for $r {\varepsilon}/2$ in the uniform
continuity of $g$. We imagine an annulus in $U$ with radii $r-\delta$
and $r+\delta$, given a thickness $2\delta$ in the $V$-direction. It
follows by the triangle inequality that if
$r-\delta < \modulus{z-z_0} < r+\delta$ and
$\modulus{w-w_0}<\delta$ then
$|g(z,w)| = \modulus{g(z,w) - g(z,w_0) + g(z,w_0)} \leq  \modulus{g(z,w) - g(z,w_0)} + \modulus{g(z,w_0)} <r{\varepsilon}$.
This bounds $g$ along the boundary of any ball (in the $U$-direction) of
radius $r$ around any $(z_1, w_1)$ in the neighborhood
$B(z_0, \delta) \times B(w_0, \delta)$. Then for any such $(z_1, w_1)$,
Cauchy's bound gives
$\modulus{g_z(z_1,w_1)}<{\varepsilon}$ as
desired. This shows that $g$ is a continuous function of two variables
at $z_0, w_0$ in this case.

Case 2: Apply Case 1 to the function
$g(z,w) - g_z(z_0,w_0)(z-z_0) - g(z_0,w_0)$, a function of $z$ and $w$
whose partial with respect to $z$ is $g_z(z,w) - g_z(z_0,w_0)$. This
shows that $g_z(w,z)$ plus a constant is continuous, thus so is
$g_z(w,z)$. 
:::

::: {.theorem}
**(Leibniz Integral Formula)** Let $g(z, w)$ a continuous
function of two variables, and analytic in $z$ for each $w$. Let
$\gamma$ be a continuous, bounded variation path. Then
$$\frac{d}{dz} \int_\gamma g(z,w) dw = \int_\gamma g_z(z,w) dw$$
:::

::: {.proof}
Fix $z_0$. For each $w$ consider the tangent line approximation
$g(z,w) = g_z(z_0,w)(z-z_0) + g(z_0,w) + e(z,w)$ where
$\lim_{z \to z_0} \frac{e(z,w) }{z-z_0} = 0$. By the previous lemma,
$g_z(z_0,w)$ is a continuous function of $w$, so $e(z,w)$ is a
continuous function of $z$ and $w$.
$$\left(\frac{d}{dz} \int_\gamma g(z,w) dw \right) - \int_\gamma g_z(z,w) dw = \lim_{z \to z_0} \left[\frac{\int_\gamma g(z,w) dw - \int_\gamma g(z_0,w) dw}{z-z_0} - \int_\gamma g_z(z_0,w) dw \right] = \lim_{z \to z_0} \int_\gamma \frac{e(z,w)}{z-z_0} dw$$
On a compact region
$\overline{B(z_0,{\varepsilon})} \times im(\gamma)$, the
function $e$ is uniformly continuous, and by @cor-limit-commutes-integral
the limit commutes with the integral:
$$\lim_{z \to z_0} \int_\gamma \frac{e(z,w)}{z-z_0} dw = \int_\gamma \lim_{z \to z_0} \frac{e(z,w)}{z-z_0} dw= 0$$ 
:::

::: {.definition}
Let $U \subseteq {\mathbb C}$ be open. Let $\gamma$
be a closed path in $U$. We call $\gamma$ **homologous to zero in $U$**
if $W(\gamma, a)=0$ for all $a \notin U$.
:::

::: {.theorem}
**(Cauchy Integral Formula, general case)** Let
$U \subseteq {\mathbb C}$ be open, and let $\gamma$ be homologous to
zero in $U$. Let $f$ be analytic on $U$. Then for all $z \in U$
$$\int_\gamma \frac{f(w)}{w-z} dw = 2\pi i W(\gamma,z) f(z)$$
:::

::: {.proof}
Now consider a path $\gamma$ and a function $f$. Write $E$ for
the union of the components of ${\mathbb C}- \{\gamma\}$ on which
$W(\gamma,z)=0$. Notice that $E$ includes the unbounded component of
${\mathbb C}- \{\gamma\}$, by @thm-unbounded-component-no-winding. 
Let us assume $f$ is
differentiable on $U$, and $U \cup E = {\mathbb C}$. As before,
$$\text{let } q(z,w) = \left\{\begin{array}{ll}\frac{f(w)-f(z)}{w-z}  & \text{ if $w \neq z$} \\ f'(z)& \text{ if $w= z$} \end{array} \right.$$ 
        Since $f$ is
differentiable, it is continuously so, and $q$ is uniformly continuous
on any compact set. For fixed $z$, $q(z,w)$ is a differentiable function
of $w$ and continuous at $w=z$, where it therefore has a removable
singularity. Thus $q$ is analytic in each variable separately.
$$\text{Let } h(z) = \left\{\begin{array}{ll} \int_\gamma q(z,w) dw  & \text{ if $z \in U$} \\[1em] \int_\gamma \frac{f(w)}{w-z} dw &\text{if $z \in E$} \end{array}\right.$$ 
On the (open!) overlap $U \cap E$, these
agree because $\int_\gamma \frac{f(z)}{w-z}=0$ by assumption. We claim
$h(z)$ is entire. On $U$, the Leibniz rule applies and
$h'(z) = \frac{d}{dz} \int_\gamma q(z,w) dw = \int_{\gamma} q_z(z,w) dw$.
Notice $q_z$ is a continuous function $w$, in fact of two variables, so
the integral exists, so $h'$ exists.

On $E - U$, Leibniz rule gives
$\frac{d}{dz} \int_\gamma \frac{f(w)}{w-z} dw = \int_\gamma \frac{f(w)}{(w-z)^2} dw$.
Again this is continuous since $w \neq z$ for $w \in \{\gamma\}$.

However, for $z$ sufficiently far from the compact set $\{\gamma\}$ (say
when $d(z, \{\gamma\})>R$) we bound
$h(z) = \int_\gamma \frac{f(w)}{w-z} dw$ by ML:
$$\modulus{\int_\gamma \frac{f(w)}{w-z} dw} \leq \max_{w \in \{\gamma\}} \modulus{f(w)} \frac{1}{R}\modulus{v(\gamma)}$$
That is, $h$ is bounded for $\{z\in {\mathbb C}| d(z, \{\gamma\})>R\}$,
and bounded on $\{z\in {\mathbb C}| d(z, \{\gamma\})\leq R\}$ by
compactness. It follows that $h$ is constant. Since $R$ is arbitrary in
the bound
$\modulus{f(w)} \frac{1}{R}\modulus{v(\gamma)}$,
$h$ is the zero function.

Therefore, for all $z \in U$, we have
$$\int_\gamma \frac{f(w)-f(z)}{w-z} dw=0$$

That is,
$$\int_\gamma \frac{f(w)}{w-z} dw=\int_\gamma \frac{f(z)}{w-z} dw = 2 \pi i f(z) W(\gamma,z)$$ 
:::

::: {.corollary}
Let $U \subseteq {\mathbb C}$ be open, and let $f$
be analytic on $U$, $\gamma$ closed and homologous to zero in $U$. Then
$\int_\gamma f(w) dw=0$.
:::

::: {.proof}
$f(w) = f(w)(w-z) / (w-z)$. 
:::

::: {.corollary}
Let $U \subseteq {\mathbb C}$ be open, and let $f$
be meromorphic on $U$, $\gamma$ closed and homologous to zero in $U$.
Then $\int_\gamma f(w) dw=2\pi i \sum_i W(\gamma,z_i) Res(f,z_i)$.
:::

::: {.proof}
Subtract off higher negative power terms b/c they have
antiderivatives. Subtract $\prod R_i/(w-z_i)$ and remove singularities
to produce analytic function. Apply previous corollary. 
:::

## Using the method of residues to calculate real integrals

The residue theorem is so powerful that it can solve many ordinary real
integrals, particularly improper ones:

::: {.example}
We calculate
$\displaystyle \int_0^\infty \frac{1}{1+x^2} dx$.

With some familiarity with inverse trigonometric functions, one
calculates the integral as
$\lim_{b \to \infty} \arctan(b)-\arctan(0) = \pi/2$. In contrast,
complex analysis solves the problem without leaving the domain of
rational functions.

First we notice that the function is even and has residues at $i$ and
$-i$. We double the integral to produce the more convenient problem
$\displaystyle \int_{-\infty}^\infty \frac{1}{1+x^2} dx$, replace it
with the finite version $\displaystyle \int_{-R}^R \frac{1}{1+x^2} dx$,
and regard this straight line real integral as the lower part of a path
integral on $\gamma$, a path which proceeds from $-R$ to $R$ along the
real line, and then from $R$ to $-R$ along a complex upper semicircle
centered at $0$. If we can calculate both the residue at $i$ (interior
to this path) and the integral along the semicircle, we can deduce the
straight line integral from Cauchy's integral formula. The residue at
$i$ is
$\lim_{z \to i}(z-i)\frac{1}{1+z^2} = \lim_{z \to i} \frac{1}{z+i} = \frac1{2i}$.
The semicircular integral is harder to calculate, but the ML inequality
bounds it at $\frac{2 \pi R}{R^2-1}$, which goes to zero at $R$ goes to
infinity. In the limit, then, we have

$$\lim_{R \to \infty} \int_{-R}^R \frac{1}{1+z^2} dz = 2 \pi i \frac{1}{2i} = \pi$$

Remember we have doubled the original problem, so the answer is $\pi/2$
as expected from trigonometry.
:::

::: {.example}
We calculate
$\displaystyle \int_{-\infty}^\infty \frac{1}{1+x^4} dx$. It's possible
to factor this into two irreducible quadratics, complete squares, and
apply trigonometric substitutions, but it's not fun. Instead we
integrate as above. Again the semicircular integral is approaches zero,
so we have

$$\lim_{R \to \infty} \int_{-R}^R \frac{1}{1+z^4} dz = 2 \pi i (\text{sum of residues})$$

So we need the poles and residues. The roots are $z^4+1$ are
$e^{\frac14\pi i }$, $e^{\frac34\pi i }$, $e^{\frac54\pi i }$, and
$e^{\frac74\pi i }$. Setting $\alpha = e^{\frac14\pi i }$, we write
$\alpha^3$, $\alpha^5$, and $\alpha^7$. Only $\alpha$ and $\alpha^3$ are
in the upper half plane, so we calculate the residues there. Note of
course $\alpha^4 = -1$.

\begin{align}
    \lim_{z \to \alpha} (z-\alpha) \frac{1}{z^4+1} &= \lim_{z \to \alpha}  \frac{(z-\alpha)}{(z-\alpha)(z-\alpha^3)(z-\alpha^5)(z-\alpha^7)} \\
    &= \lim_{z \to \alpha} \frac{1}{(z-\alpha^3)(z-\alpha^5)(z-\alpha^7)} \\
    &= \frac{1}{(\alpha-\alpha^3)(\alpha-\alpha^5)(\alpha-\alpha^7)} \\
    &= \frac{1}{\alpha^3(1-\alpha^2)(1-\alpha^4)(1-\alpha^6)} \\
    &= \frac{\alpha}{(-1)(1-i)(2)(1+i)} \\
    &= \frac{-\alpha}{4}
\end{align}

A sneakier calculation is to recognize the limit
$\lim_{z \to \alpha} (z-\alpha) \frac{1}{z^4+1}$ as the reciprocal of
the derivative of $f(z) = z^4+1$ at $z=\alpha$, which is $4 \alpha^3$.
The reciprocal is $-\alpha/4$. SImilarly, the residue at $\alpha^3$ is
the reciprocal of $4\alpha^{9} = 4 \alpha$, or $-\alpha^3/4$. The sum of
the residues is $\frac{-1}4(\alpha + \alpha^3) = 
\frac{-\alpha}4(1+\alpha^2) = \frac{-\alpha}4(1+i) = \frac{-\alpha \sqrt{2}\alpha}{4} = \frac{-\sqrt{2}i}{4}$.
We conclude:

$$\lim_{R \to \infty} \int_{-R}^R \frac{1}{1+4^2} dz = 2 \pi i \frac{-\sqrt{2}i}{4} = \frac{\pi}{\sqrt{2}}$$
:::
